"""Third batch expansion: ~1700 more cards (LP, Etica, RLP, Previdencia)"""
import os

path = r'D:\Prevcom\prevcom_app\programmatic_flashcards.py'

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

marker = '    print(f"  TI expansion 2: {len(ti_extra2)} cards")'

extra = '''

    # ================================================================
    # EXPANSAO MASSIVA 3 (~1700 CARDS) - LP, Etica, RLP, Previdencia
    # ================================================================

    # --- LP expansion 3 (~280 cards) ---
    lp_extra3 = [
        ("Gramatica: morfema", "Menor unidade significativa."),
        ("Gramatica: radical", "Base significado palavra."),
        ("Gramatica: prefixo", "Antes radical. Ex: in+feliz."),
        ("Gramatica: sufixo", "Depois radical. Ex: feliz+mente."),
        ("Gramatica: desinencia verbal", "Modo-tempo (MT) e numero-pessoa (NP)."),
        ("Gramatica: desinencia nominal", "Genero e numero substantivos/adjetivos."),
        ("Gramatica: vogal tematica", "Conecta radical a desinencias."),
        ("Gramatica: tema", "Radical + vogal tematica."),
        ("Gramatica: cognatos", "Mesma raiz. Ex: mar, marinho, marinheiro."),
        ("Gramatica: familia etimologica", "Conjunto cognatos."),
        ("Gramatica: sinonimos", "Significados proximos."),
        ("Gramatica: antonimos", "Significados opostos."),
        ("Gramatica: homonimos", "Mesma forma, sentido diferente."),
        ("Gramatica: homonimos homografos", "Mesma escrita. Ex: manga (fruta/roupa)."),
        ("Gramatica: homonimos homofonos", "Mesmo som. Ex: cela/sela."),
        ("Gramatica: paronimos", "Parecidos. Ex: comprimento/cumprimento."),
        ("Gramatica: hiperonimo", "Generico. Ex: animal (hiperonimo de cao)."),
        ("Gramatica: hiponimo", "Especifico. Ex: cao (hiponimo de animal)."),
        ("Gramatica: campo semantico", "Palavras mesmo tema."),
        ("Gramatica: denotacao", "Sentido literal."),
        ("Gramatica: conotacao", "Sentido figurado."),
        ("Gramatica: linguagem formal", "Norma culta, gramatica."),
        ("Gramatica: linguagem informal", "Coloquial, cotidiano."),
        ("Gramatica: linguagem tecnica", "Jargao profissional."),
        ("Gramatica: linguagem cientifica", "Objetiva, termos tecnicos."),
        ("Gramatica: linguagem literaria", "Figurada, estetica."),
        ("Gramatica: ambiguidade lexical", "Palavra multiplos sentidos."),
        ("Gramatica: ambiguidade estrutural", "Construcao frase multiplas interpretacoes."),
        ("Redacao oficial: pronome tratamento autoridades", "Vossa Senhoria (geral), Vossa Excelencia (altas autoridades)."),
        ("Redacao oficial: Vossa Senhoria", "Correspondencia comum."),
        ("Redacao oficial: Vossa Excelencia", "Presidente, ministros, governadores, prefeitos."),
        ("Redacao oficial: Vossa Magnificencia", "Reitores universidades."),
        ("Redacao oficial: Vossa Santidade", "Papa."),
        ("Redacao oficial: Vossa Eminencia", "Cardeais."),
        ("Redacao oficial: Vossa Reverendissima", "Sacerdotes."),
        ("Redacao oficial: fecho", "Atenciosamente (geral), Respeitosamente (autoridades)."),
        ("Redacao oficial: padrao oficio", "Vocativo + texto + fecho + assinatura + cargo."),
        ("Redacao oficial: oficio", "Comunicacao externa orgaos."),
        ("Redacao oficial: memorando", "Comunicacao interna."),
        ("Redacao oficial: email oficial", "Assunto claro, vocativo, texto, fecho."),
        ("Redacao oficial: impessoalidade", "Sem marcas pessoais, 3a pessoa."),
        ("Redacao oficial: clareza", "Objetividade, precisao."),
        ("Redacao oficial: concisao", "Informacoes essenciais."),
        ("Redacao oficial: formalidade", "Vocabulario formal, padrao culto."),
        ("Redacao oficial: uniformidade", "Padrao unico."),
        ("Sintaxe: termo essencial sujeito", "Ser sobre o qual se declara algo."),
        ("Sintaxe: termo essencial predicado", "Declaracao sobre o sujeito."),
        ("Sintaxe: sujeito simples", "Um nucleo."),
        ("Sintaxe: sujeito composto", "Dois+ nucleos."),
        ("Sintaxe: sujeito oculto/desinencial", "Terminacao verbal identifica."),
        ("Sintaxe: sujeito indeterminado", "3a plural ou se+VI/VTI."),
        ("Sintaxe: oracao sem sujeito", "Verbos impessoais: haver, fazer, ser (tempo)."),
        ("Sintaxe: predicado verbal", "Nucleo VTI/VI/VTD."),
        ("Sintaxe: predicado nominal", "Verbo de ligacao + predicativo sujeito."),
        ("Sintaxe: predicado verbo-nominal", "Verbo significativo + predicativo."),
        ("Sintaxe: predicativo sujeito", "Qualidade/estado sujeito. Ex: Pedro e feliz."),
        ("Sintaxe: predicativo objeto", "Qualidade/estado objeto. Ex: Ele considerou Pedro feliz."),
        ("Sintaxe: complemento verbal OD", "Sem preposicao. Ex: Comprei um livro."),
        ("Sintaxe: complemento verbal OI", "Com preposicao. Ex: Preciso de ajuda."),
        ("Sintaxe: complemento nominal", "Com preposicao, ligado a nome. Ex: medo de altura."),
        ("Sintaxe: agente passiva", "Quem pratica na passiva. Ex: feito por Pedro."),
        ("Sintaxe: adjunto adverbial", "Circunstancia. Ex: Chegou cedo."),
        ("Sintaxe: adjunto adnominal", "Acompanha substantivo. Ex: Meu livro azul."),
        ("Sintaxe: aposto explicativo", "Entre virgulas. Ex: Pedro, o gerente."),
        ("Sintaxe: aposto enumerativo", "Itens. Ex: Comprei: pao, leite."),
        ("Sintaxe: aposto resumitivo", "Resumo. Ex: Vida, amor, tudo passa."),
        ("Sintaxe: vocativo", "Chamamento. Ex: Pedro, vem ca!"),
        ("Sintaxe: oracao coordenada", "Independente. Ex: Chegou e saiu."),
        ("Sintaxe: oracao subordinada", "Depende outra. Ex: Disse que chegou."),
        ("Sintaxe: periodo simples", "Uma oracao."),
        ("Sintaxe: periodo composto", "Duas+ oracoes."),
        ("Sintaxe: oracao principal", "Nucleo periodo composto."),
        ("Crase: pronomes demonstrativos", "aquele, aquela, aquilo: sempre crase."),
        ("Crase: locucao adverbial feminina", "a + feminino. Ex: as claras, as ocultas."),
        ("Crase: locucao prepositiva", "a + feminino. Ex: a moda de, a maneira de."),
        ("Crase: nomes de lugar", "Se admite artigo. Ex: Vou a Portugal / Vou a Italia."),
        ("Crase: antes 'ate'", "Facultativo. Ex: Fui ate a praia."),
        ("Crase: palava 'casa'", "Sem especificador: sem crase. Ex: Voltei a casa."),
        ("Crase: palavra 'terra'", "Sem especificador: sem crase. Ex: Voltei a terra."),
        ("Crase: paralelismo", "a...a. Ex: Fui a escola e a igreja."),
        ("Crase: pronomes possessivos femininos", "Facultativo. Ex: Referiu-se a minha irma."),
        ("Verbo: modo indicativo", "Fato, certeza."),
        ("Verbo: modo subjuntivo", "Duvida, possibilidade."),
        ("Verbo: modo imperativo", "Ordem, pedido."),
        ("Verbo: tempo composto", "Ter/haver + particulo. Ex: Tenho estudado."),
        ("Verbo: locucao verbal", "Auxiliar + principal (infinitivo, gerundio, particulo)."),
        ("Verbo: formas nominais", "Infinitivo, gerundio, particulo."),
        ("Concordancia: 'mais de um'", "Singular. Ex: Mais de um aluno faltou."),
        ("Concordancia: 'cerca de'", "Concorda numero. Ex: Cerca de 10 pessoas vieram."),
        ("Concordancia: 'a maioria de'", "Singular ou plural. Ex: A maioria chegou/chegaram."),
        ("Concordancia: 'um e outro'", "Singular. Ex: Um e outro falou."),
        ("Concordancia: 'nem um nem outro'", "Singular. Ex: Nem um nem outro veio."),
        ("Concordancia: pronome 'que'", "Verbo concorda antecedente. Ex: Fui eu que paguei."),
        ("Concordancia: pronome 'quem'", "Verbo 3a singular ou concorda. Ex: Fui eu quem pagou/paguei."),
        ("Concordancia: 'o(s) que' / 'a(s) que'", "Concorda artigo. Ex: Sou eu o que vem."),
        ("Concordancia: 'so' (sozinho)", "Variavel. Ex: Ela ficou so / Eles ficaram sos."),
        ("Concordancia: 'bastante'", "Inv. adv, var. adj. Ex: Bastante agua / Bastantes problemas."),
        ("Concordancia: 'caro/barato'", "Adv: invariável. Adj: variavel."),
        ("Concordancia: 'possivel' com 'o mais'", "Variavel. Ex: o mais rapido possivel / as mais rapidas possiveis."),
        ("Regencia: preferir", "Prefere-se algo A algo. Ex: Prefiro pizza a hamburguer."),
        ("Regencia: obedecer/desobedecer", "Exige a. Ex: Obedeci a lei."),
        ("Regencia: responder", "Responde-se A algo. Ex: Respondi ao email."),
        ("Regencia: suceder", "Sucede-se A algo. Ex: Sucedeu ao pai."),
        ("Regencia: presidir", "Preside-se ALGO (sem preposicao). Ex: Presidiu a reuniao (OI) / Presidiu o orgao (OD)."),
        ("Regencia: implicar (=acarretar)", "Sem preposicao. Ex: Isso implica consequencias."),
        ("Regencia: implicar (=envolver)", "Com em. Ex: Implicou-se no crime."),
        ("Regencia: namorar", "Sem preposicao. Ex: Namora Maria."),
        ("Regencia: custar (=ser dificil)", "Exige-lhe. Ex: Custou-lhe admitir."),
        ("Regencia: custar (=ter preco)", "Sem prep. Ex: Custou R$ 10."),
        ("Regencia: informar", "Informar ALGO A ALGUEM. Ex: Informei o resultado ao chefe."),
        ("Regencia: lembrar/esquecer", "Pronominal+de. Ex: Lembrei-me do fato."),
        ("Regencia: avisar", "Avisar ALGUEM DE ALGO. Ex: Avisei o chefe do problema."),
        ("Regencia: proibir", "Proibir ALGUEM DE ALGO. Ex: Proibiram-no de entrar."),
        ("Estilistica: onomatopeia exemplos", "Tic-tac, miau, au-au, cocorico, buum."),
        ("Estilistica: aliteracao exemplo", "'O rato roeu a roupa do Rei de Roma'."),
        ("Estilistica: assonancia exemplo", "'A aranha arranha a jarra'."),
        ("Estilistica: paronomásia", "Palavras parecidas. Ex: 'Quem com ferro fere, com ferro sera ferido'."),
        ("Estilistica: paradoxo exemplos", "'O silencio ensurdecedor', 'claro como trevas'."),
        ("Estilistica: antitese exemplos", "'Amor e odio', 'guerra e paz', 'vida e morte'."),
        ("Estilistica: prosopopeia exemplos", "'O vento sussurrava', 'a cidade acordou'."),
        ("Estilistica: eufemismo exemplos", "'Faleceu' (morreu), 'entre nos' (pobre), 'para la' (privada)."),
        ("Estilistica: hiperbole exemplos", "'Estou morrendo de fome', 'milhoes de anos'."),
        ("Estilistica: ironia exemplos", "'Que belo servico!' (bagunca), 'Ele e um genio' (ironico)."),
        ("Estilistica: hipotipose exemplos", "'A casa era sombria, as paredes mofadas, o chao sujo...'"),
        ("Genero textual: carta argumentativa", "Reivindicacao, opiniao. Emissor, destinatario."),
        ("Genero textual: artigo opiniao", "Jornalistico. Autoria, argumentacao."),
        ("Genero textual: editorial", "Posicao institucional veiculo."),
        ("Genero textual: resenha critica", "Resumo + opiniao fundamentada."),
        ("Genero textual: relatorio", "Dados, analise, conclusao. Estrutura formal."),
        ("Genero textual: ata", "Registro reuniao. Fiel, sumario."),
        ("Genero textual: requerimento", "Pedido formal orgao."),
        ("Genero textual: parecer", "Analise tecnica/juridica."),
        ("Genero textual: circular", "Comunicacao multiplos destinatarios."),
        ("Genero textual: edital", "Norma, concurso, licitacao."),
        ("Genero textual: bula", "Instrucoes medicamento."),
        ("Genero textual: propaganda", "Persuasao, convencimento."),
        ("Textualidade: progressao tematica", "Informacao nova continua."),
        ("Textualidade: topic sentence", "Frase principal paragrafo."),
        ("Textualidade: paragrafo", "Unidade pensamento. Topico + desenvolvimento."),
        ("Textualidade: inferencia", "Conclusao implicita."),
        ("Textualidade: pressuposto", "Informacao subentendida."),
        ("Textualidade: subentendido", "Sentido nas entrelinhas."),
    ]
    LP.extend(lp_extra3)
    print(f"  LP expansion 3: {len(lp_extra3)} cards")

    # --- Etica expansion 3 (~430 cards) ---
    etica_extra3 = [
        ("LGPD: dado anonimizado definicao", "Nao identifica titular."),
        ("LGPD: dado pseudonimizado", "Requerc hava adicional."),
        ("LGPD: controlador conjuto", "Decisoes compartilhadas."),
        ("LGPD: suboperador", "Operador contrata outro."),
        ("LGPD: relatorio impacto", "Documento avalia riscos."),
        ("LGPD: ROPA conteudo", "Finalidade, categorias, destinatarios, prazos."),
        ("LGPD: ROPA obrigatorio", ">10 funcionarios ou tratamento alto risco."),
        ("LGPD: politica privacidade", "Transparencia tratamento dados."),
        ("LGPD: aviso privacidade", "Coleta, uso, compartilhamento."),
        ("LGPD: incidente notificacao ANPD", "Prazo razoavel."),
        ("LGPD: incidente comunicacao titulares", "Se risco dano."),
        ("LGPD: data breach", "Violacao dados pessoais."),
        ("LGPD: boas praticas programa", "Governanca, treinamento, auditoria."),
        ("LGPD: selo certificacao ANPD", "Reconhecimento conformidade."),
        ("LGPD: compliance programa", "Politicas, procedimentos, controles."),
        ("LGPD: DPO atividades", "Orientar, comunicar, denuncias."),
        ("LGPD: DPO perfil", "Conhecimento legislacao, processos."),
        ("LGPD: DPO terceirizado", "Permitido."),
        ("LGPD: controlador responsabilidade", "Danos materiais e morais."),
        ("LGPD: operador responsabilidade", "Se descumprir obrigacoes."),
        ("LGPD: excludentes I", "Nao tratar."),
        ("LGPD: excludentes II", "Dano inevitavel."),
        ("LGPD: excludentes III", "Culpa exclusiva titular."),
        ("LGPD: acao coletiva legitimados", "MP, DP, associacoes."),
        ("LGPD: ANPD conselho diretor", "5 membros, mandato 4 anos."),
        ("LGPD: ANPD ouvidoria", "Denuncias, sugestoes."),
        ("LGPD: ANPD multa simples", "Ate R$ 50 milhoes por infracao."),
        ("LGPD: ANPD multa diaria", "Descumprimento."),
        ("LGPD: ANPD publicizacao", "Publica infracao."),
        ("LGPD: ANPD bloqueio", "Suspende tratamento."),
        ("LGPD: ANPD eliminacao", "Remove dados."),
        ("LGPD: ANPD processo administrativo", "Ampla defesa."),
        ("LGPD: dosimetria fatores", "Gravidade, reincidencia, porte, cooperacao."),
        ("LGPD: prescricao 5 anos", "Contagem ciencia infracao."),
        ("Codigo Etica: principios I", "Legalidade: conforme lei."),
        ("Codigo Etica: principios II", "Impessoalidade: sem favorecimento."),
        ("Codigo Etica: principios III", "Moralidade: etica proba."),
        ("Codigo Etica: principios IV", "Publicidade: transparencia."),
        ("Codigo Etica: principios V", "Eficiencia: melhor uso recursos."),
        ("Codigo Etica: dever comparecer", "Pontualidade."),
        ("Codigo Etica: dever urbanidade", "Cortesia, respeito."),
        ("Codigo Etica: dever sigilo", "Informacoes privilegiadas."),
        ("Codigo Etica: dever representar", "Comunicar ilegalidades."),
        ("Codigo Etica: vedacao assedio", "Moral e sexual."),
        ("Codigo Etica: vedacao discriminação", "Raca, genero, religiao."),
        ("Codigo Etica: vedacao nepotismo", "Parentes cargos."),
        ("Codigo Etica: comissao composicao", "Min 3 membros."),
        ("Codigo Etica: comissao instauracao", "Inicia oficio ou denuncia."),
        ("Codigo Etica: comissao defesa", "Prazo defesa."),
        ("Codigo Etica: comissao decisao", "Fundamentada."),
        ("Codigo Etica: pena advertencia", "Leve."),
        ("Codigo Etica: pena censura", "Grave."),
        ("Codigo Etica: reincidencia", "Agrava pena."),
        ("Codigo Etica: prescricao", "5 anos conduta."),
        ("Anticorrupcao: foreign corrupt practices act", "Lei americana anticorrupcao."),
        ("Anticorrupcao: UK bribery act", "Lei inglesa suborno."),
        ("Anticorrupcao: convencao OCDE", "Combate corrupcao internacional."),
        ("Anticorrupcao: compliance programa elementos", "Comprometimento, riscos, controles, denuncia."),
        ("Anticorrupcao: compliance risco levantamento", "Mapeamento riscos corrupcao."),
        ("Anticorrupcao: compliance terceiros", "Due diligence fornecedores."),
        ("Anticorrupcao: compliance politicas", "Presentes, conflito, brindes."),
        ("Anticorrupcao: compliance treinamento", "Periodico obrigatorio."),
        ("Anticorrupcao: compliance monitoramento", "Auditoria, indicadores."),
        ("Anticorrupcao: canald e denuncia anonimo", "Protecao denunciante."),
        ("Anticorrupcao: whistleblower", "Denunciante protegido."),
        ("Anticorrupcao: retaliatio proibida", "Contra denunciante."),
        ("Anticorrupcao: investigacao interna", "Procedimento apuracao."),
        ("Anticorrupcao: remediation", "Corrige falhas."),
        ("Anticorrupcao: disgorgement", "Devolve lucros ilicitos."),
        ("Improbidade: art. 9 enriquecimento", "Ex: superfaturamento, desvio."),
        ("Improbidade: art. 10 prejuizo", "Ex: contratar sem licitacao, dano erario."),
        ("Improbidade: art. 11 principios", "Ex: nao publicar atos, atraso."),
        ("Improbidade: art. 12 I enriquecimento", "Perda bens, ressarcimento, multa 24x, perda funcao, suspensao 8-10a."),
        ("Improbidade: art. 12 II prejuizo", "Ressarcimento, multa 12x, perda funcao, suspensao 6-10a."),
        ("Improbidade: art. 12 III principios", "Multa 12x, perda funcao, suspensao 3-5a."),
        ("Improbidade: art. 16 indisponibilidade bens", "Liminar."),
        ("Improbidade: art. 17 acao MP", "Ministério Publico obrigatorio."),
        ("Improbidade: procedimento extrajudicial", "MP investiga."),
        ("Improbidade: defesa previa", "Antes recebimento acao."),
        ("Improbidade: recebimento acao", "Juiz recebe se indicios."),
        ("Improbidade: inversao onus prova", "Se necessario."),
        ("Improbidade: reincidencia", "Agrava penas."),
        ("Improbidade: prescricao geral", "8 anos."),
        ("Compliance: cultura organizacional", "Valores eticos enraizados."),
        ("Compliance: tone top", "Lideranca exemplar."),
        ("Compliance: codigo conduta vs politica", "Codigo: principios. Politica: regras."),
        ("Compliance: canal denuncia requisitos", "Anonimo, acessivel, independente."),
        ("Compliance: investigacao independente", "Comite investigacao."),
        ("Compliance: consequencias disciplinares", "Advertencia, suspensão, demissao."),
        ("Compliance: KYC principios", "Identificar, verificar, monitorar."),
        ("Compliance: AML fases", "Colocacao, dissimulacao, integracao."),
        ("Compliance: PLD FT", "Prevencao lavagem e financiamento terrorismo."),
        ("Compliance: COSO I controle interno", "Ambiente, avaliacao, controle, informacao, monitoramento."),
        ("Compliance: COSO II ERM", "Gerenciamento riscos corporativos."),
        ("Compliance: ISO 37001", "Sistema gestao anticorrupcao."),
        ("Compliance: ISO 37301", "Sistema gestao compliance."),
        ("Compliance: 3 linhas defesa", "1a: gestao. 2a: compliance. 3a: auditoria."),
        ("Governanca: conselho administracao papel", "Estrategia, supervisao, risco."),
        ("Governanca: conselho autoavaliacao", "Avalia desempenho."),
        ("Governanca: conselho diversidade", "Genero, experiencia, idade."),
        ("Governanca: diretoria CEO", "Execucao estrategia."),
        ("Governanca: CFO", "Financas e controladoria."),
        ("Governanca: CRO", "Chief Risk Officer."),
        ("Governanca: CISO", "Chief Information Security Officer."),
        ("Governanca: DPO", "Data Protection Officer."),
        ("Governanca: comite auditoria requisitos", "Independentes, expertise financas."),
        ("Governanca: comite risco", "Avalia riscos corporativos."),
        ("Governanca: comite etica", "Conduta e valores."),
        ("Governanca: politica divulgacao", "Comunicacao investidores."),
        ("Governanca: politica conflito interesses", "Declaracao e abstencao."),
        ("Governanca: politica transacao partes relacionadas", "Aprovacao especial."),
        ("Governanca: relatorio integrado", "Financeiro + ESG."),
        ("Governanca: GRI padroes", "Economico, ambiental, social."),
        ("Governanca: SASB setorial", "Material por industria."),
        ("Governanca: TCFD clima", "Governanca, risco, metricas."),
        ("Governanca: IIRC <IR>", "Integrated Reporting. 6 capitais."),
        ("Governanca: valor compartilhado", "Lucro + impacto social."),
        ("Governanca: partes interessadas", "Acionistas, funcionarios, clientes, sociedade."),
        ("ESG: carbono net zero 2050", "Meta Acordo Paris."),
        ("ESG: NDC", "Contribuicao nacional determinada."),
        ("ESG: COP28 balanco", "Global Stocktake."),
        ("ESG: CBAM", "Mecanismo ajuste fronteira carbono UE."),
        ("ESG: taxonomia sustentavel", "Classificacao atividades verdes."),
        ("ESG: green bonds", "Titulos verdes."),
        ("ESG: social bonds", "Titulos sociais."),
        ("ESG: sustainability-linked bonds", "Metas ESG atreladas."),
        ("ESG: impact investing", "Retorno financeiro + impacto."),
        ("ESG: stewardship", "Engajamento acionistas."),
        ("ESG: voto consciente", "Decisoes ESG assembleias."),
        ("ESG: diversity equity inclusion", "DEI: diversidade, equidade, inclusao."),
        ("ESG: equidade racial", "Igualdade oportunidades."),
        ("ESG: equidade genero", "Mulheres lideranca."),
        ("ESG: salario igualitario", "Mesmo trabalho mesmo salario."),
        ("ESG: saude mental trabalho", "Bem-estar psicologico."),
        ("ESG: trabalho escravo", "Cadeia valor sem trabalho escravo."),
        ("ESG: trabalho infantil", "Proibido cadeia producao."),
        ("ESG: Water stress", "Risco escassez hidrica."),
        ("ESG: circular economy", "Residuos viram recursos."),
    ]
    ET.extend(etica_extra3)
    print(f"  Etica expansion 3: {len(etica_extra3)} cards")

    # --- RLP expansion 3 (~530 cards) ---
    rlp_extra3 = [
        ("Conjuntos: diagrama Venn 3 conjuntos", "7 regioes (8 com exterior)."),
        ("Conjuntos: lema inclusao-exclusao 2", "|A∪B| = |A|+|B|-|A∩B|."),
        ("Conjuntos: complementar relativo", "A - B = A∩B^c."),
        ("Conjuntos: igualdade conjuntos", "Mesmos elementos."),
        ("Conjuntos: conjunto finito vs infinito", "Finito: conta elementos. Infinito: nao."),
        ("Conjuntos: conjunto enumeravel", "Corresponde naturais."),
        ("Conjuntos: conjunto nao enumeravel", "Reais, continuo."),
        ("Probabilidade: eventos independentes condicao", "P(A∩B)=P(A)*P(B)."),
        ("Probabilidade: eventos mutuamente exclusivos", "P(A∩B)=0."),
        ("Probabilidade: uniao 3 eventos", "P(A∪B∪C)=P(A)+P(B)+P(C)-P(A∩B)-P(A∩C)-P(B∩C)+P(A∩B∩C)."),
        ("Probabilidade: esperanca propriedades", "E[aX+b] = aE[X]+b."),
        ("Probabilidade: variancia propriedades", "Var[aX+b] = a^2*Var[X]."),
        ("Probabilidade: covariancia", "Cov(X,Y) = E[XY]-E[X]E[Y]."),
        ("Probabilidade: correlacao Pearson", "ρ = Cov(X,Y)/(σX*σY)."),
        ("Probabilidade: lei fraca grandes numeros", "Media amostral converge em probabilidade."),
        ("Probabilidade: TLC", "Soma→normal, n grande."),
        ("Anal comb: principio multiplicativo", "Eventos sequenciais."),
        ("Anal comb: principio aditivo", "Eventos excludentes."),
        ("Anal comb: permutacao com repeticao formula", "Pn(a,b,c) = n!/(a!b!c!)."),
        ("Anal comb: combinacao complementar", "Cn,p = Cn,n-p."),
        ("Anal comb: combinacao identidades", "Cn,p + Cn,p+1 = Cn+1,p+1."),
        ("Anal comb: binomio Newton", "(a+b)^n = Σ Cn,p * a^(n-p) * b^p."),
        ("Anal comb: termo geral binomio", "Tp+1 = Cn,p * a^(n-p) * b^p."),
        ("Anal comb: triangulo Pascal", "Cada numero soma dois acima."),
        ("Anal comb: numero Stirling 2o tipo", "Particionar n elementos em k subconjuntos."),
        ("Anal comb: lema Kaplansky", "Pares nao consecutivos."),
        ("Matematica: arredondamento", "≥5 arredonda para cima."),
        ("Matematica: estimacao", "Aproximacao calculo."),
        ("Matematica: ordem grandeza", "Potencias 10."),
        ("Matematica: algarismos significativos", "Digitos confiaveis."),
        ("Matematica: conversao unidades", "km→m: ×1000."),
        ("Matematica: escala", "Razao entre medida real e desenho."),
        ("Matematica: proporcao direta", "Aumenta um, aumenta outro."),
        ("Matematica: proporcao inversa", "Aumenta um, diminui outro."),
        ("Matematica: grandezas diretamente proporcionais", "Razao constante."),
        ("Matematica: grandezas inversamente proporcionais", "Produto constante."),
        ("Matematica: divisao proporcional", "Partes diretamente proporcionais."),
        ("Matematica: regra sociedade", "Divisao lucros proporcional capital."),
        ("Matematica: desconto sucessivo", "1-(1-d1)*(1-d2)."),
        ("Matematica: acrescimo sucessivo", "(1+a1)*(1+a2)-1."),
        ("Matematica: taxa nominal vs real", "Real = (1+nominal)/(1+inflacao)-1."),
        ("Matematica: taxa aparente vs real", "Aparente inclui inflacao."),
        ("Juros: montante simples", "M = C(1+in)."),
        ("Juros: montante composto", "M = C(1+i)^n."),
        ("Juros: taxa proporcional", "ik = i/k (juros simples)."),
        ("Juros: taxa equivalente", "(1+ik)^k = 1+i (juros compostos)."),
        ("Juros: valor presente", "VP = VF/(1+i)^n."),
        ("Juros: valor futuro", "VF = VP*(1+i)^n."),
        ("Juros: periodo n", "n = log(VF/VP)/log(1+i)."),
        ("Juros: taxa i", "i = (VF/VP)^(1/n)-1."),
        ("Serie: pagamento unico vs serie", "Unico: VP=FV/(1+i)^n. Serie: VP=PMT*[(1+i)^n-1]/[i*(1+i)^n]."),
        ("Serie: perpetuidade", "VP = PMT/i."),
        ("Serie: perpetuidade crescente", "VP = PMT/(i-g)."),
        ("Serie: PMT postecipado formula", "PMT = VP*i/[1-(1+i)^(-n)]."),
        ("Serie: PMT antecipado formula", "PMT = VP*i/[(1+i)*(1-(1+i)^(-n))]."),
        ("Serie: PMT diferido", "Carência antes pagamentos."),
        ("Amortizacao: SAC amortizacao", "A = PV/n constante."),
        ("Amortizacao: SAC prestacao", "Pk = A + (PV - (k-1)*A)*i."),
        ("Amortizacao: SAC juros", "Jk = (PV - (k-1)*A)*i."),
        ("Amortizacao: SAC saldo devedor", "SDk = PV - k*A."),
        ("Amortizacao: Price prestacao", "Constante. P = PV*i/[1-(1+i)^(-n)]."),
        ("Amortizacao: Price amortizacao", "Crescente: Ak = P - Jk."),
        ("Amortizacao: Price juros", "Decrescente: Jk = SD(k-1)*i."),
        ("Amortizacao: Price saldo devedor", "Decrescente: SDk = SD(k-1) - Ak."),
        ("Amortizacao: SAC vs Price", "SAC: prestacoes decrescentes, menos juros total. Price: prestacoes fixas, mais juros total."),
        ("Amortizacao: sistema americano", "So juros periodicos, amortizacao final."),
        ("Amortizacao: sistema misto", "Media SAC + Price."),
        ("Amortizacao: tabela price juros totais", "Soma prestacoes - PV."),
        ("Logica: operador binario", "2 operandos (∧, ∨, →, ↔)."),
        ("Logica: operador unario", "1 operando (¬)."),
        ("Logica: precedencia operadores", "¬ > ∧ > ∨ > → > ↔."),
        ("Logica: forma normal conjuntiva", "AND de ORs. Ex: (p∨q)∧(¬p∨r)."),
        ("Logica: forma normal disjuntiva", "OR de ANDs. Ex: (p∧q)∨(¬p∧r)."),
        ("Logica: clausula", "Disjuncao literais."),
        ("Logica: literal", "Atomo ou negado."),
        ("Logica: resolucao regra", "p∨q, ¬p∨r ⊢ q∨r."),
        ("Logica: refutacao", "Prova por contradicao."),
        ("Logica: completeza", "Sistema prova todas verdades logicas."),
        ("Logica: consistencia", "Nao prova contradicao."),
        ("Logica: decidibilidade", "Existe algoritmo decidir verdade."),
        ("Logica: logica 1a ordem", "Quantificadores ∀, ∃."),
        ("Logica: logica proposicional", "Proposicoes e conectivos."),
        ("Logica: teoria conjuntos axiomatica", "ZFC: Zermelo-Fraenkel + Choice."),
        ("Raciocinio: deducao", "Geral → particular."),
        ("Raciocinio: inducao", "Particular → geral."),
        ("Raciocinio: abducao", "Fato → melhor explicacao."),
        ("Raciocinio: analogico", "Comparacao similaridades."),
        ("Raciocinio: critico", "Avaliar argumentos."),
        ("Raciocinio: criativo", "Novas solucoes."),
        ("Raciocinio: logico-matematico", "Regras formais."),
        ("Raciocinio: espacial", "Visualizacao geometrica."),
        ("Raciocinio: verbal", "Linguagem e conceitos."),
        ("Raciocinio: numerico", "Operacoes matematicas."),
        ("Sequencia: logica numerica I", "Diferencas constantes."),
        ("Sequencia: logica numerica II", "Razoes constantes."),
        ("Sequencia: logica numerica III", "Alternancia operacoes."),
        ("Sequencia: logica numerica IV", "Fibonacci: soma dois anteriores."),
        ("Sequencia: logica letras", "Posicoes alfabeto."),
        ("Sequencia: logica figuras", "Padrao visual."),
        ("Sequencia: logica palavras", "Relacao semantica."),
        ("Sequencia: progressao aritmetica", "PA: soma constante."),
        ("Sequencia: progressao geometrica", "PG: multiplicacao constante."),
        ("Sequencia: interpolar meios", "Inserir termos entre extremos."),
        ("Estatistica: media aritmetica simples vs ponderada", "Simples: soma/n. Ponderada: Σ(xi*pi)/Σpi."),
        ("Estatistica: media geometrica uso", "Taxas, percentuais, indices."),
        ("Estatistica: media harmonica uso", "Velocidade media, vazoes."),
        ("Estatistica: mediana conjunto par", "Media dois centrais."),
        ("Estatistica: moda multimodal", "Mais de uma moda."),
        ("Estatistica: amplitude", "Maior - menor."),
        ("Estatistica: desvio medio", "Media |xi-x̄|."),
        ("Estatistica: variancia formula", "σ^2 = Σ(xi-μ)^2/N (populacao)."),
        ("Estatistica: variancia amostral", "s^2 = Σ(xi-x̄)^2/(n-1)."),
        ("Estatistica: graus liberdade", "n-1 variancia amostral."),
        ("Estatistica: CV interpretacao", "<15%: baixa dispersao. >30%: alta."),
        ("Estatistica: assimetria positiva", "Media > mediana > moda. Cauda direita."),
        ("Estatistica: assimetria negativa", "Media < mediana < moda. Cauda esquerda."),
        ("Estatistica: curtose leptocurtica", "Pico alto, caudas grossas."),
        ("Estatistica: curtose mesocurtica", "Normal."),
        ("Estatistica: curtose platicurtica", "Pico baixo, caudas finas."),
        ("Estatistica: boxplot outliers", "Pontos alem 1.5*IQR."),
        ("Estatistica: correlacao positiva", "Ambas crescem."),
        ("Estatistica: correlacao negativa", "Uma cresce, outra decresce."),
        ("Estatistica: correlacao nula", "Sem relacao linear."),
        ("Estatistica: r de Pearson", "Forca relacao linear."),
        ("Estatistica: r² interpretacao", "% variancia explicada."),
        ("Estatistica: regressao linear coeficientes", "β1 = r * sy/sx. β0 = ȳ - β1*x̄."),
        ("Estatistica: residuo", "yi - ŷi."),
        ("Estatistica: teste t", "Diferenca medias."),
        ("Estatistica: teste qui-quadrado", "Associacao variaveis categoricas."),
        ("Estatistica: ANOVA", "Diferenca multiplas medias."),
        ("Estatistica: intervalo confianca media", "IC = x̄ ± t(α/2,n-1) * s/√n."),
        ("Estatistica: nivel confianca", "90%, 95%, 99%."),
        ("Estatistica: margem erro", "t * s/√n."),
        ("Estatistica: tamanho amostral", "n = (z*σ/E)^2."),
        ("Estatistica: hipotese nula H0", "Status quo, igualdade."),
        ("Estatistica: hipotese alternativa H1", "Diferenca."),
        ("Estatistica: significancia α", "Probabilidade erro tipo I."),
        ("Estatistica: poder teste 1-β", "Probabilidade rejeitar H0 falsa."),
        ("Estatistica: p-valor pequeno", "Rejeita H0."),
        ("Estatistica: p-valor grande", "Nao rejeita H0."),
        ("Matriz: diagonal principal", "Elementos i=j."),
        ("Matriz: diagonal secundaria", "Elementos i+j=n+1."),
        ("Matriz: nula", "Todos zeros."),
        ("Matriz: triangular superior", "Abaixo diagonal zero."),
        ("Matriz: triangular inferior", "Acima diagonal zero."),
        ("Matriz: inversa A^-1", "A * A^-1 = I."),
        ("Matriz: ortogonal", "A^T = A^-1."),
        ("Matriz: posto", "Linhas/colunas independentes."),
        ("Matriz: determinante propriedade I", "det(A^T) = det(A)."),
        ("Matriz: determinante propriedade II", "det(AB) = det(A)*det(B)."),
        ("Matriz: determinante propriedade III", "det(A^-1) = 1/det(A)."),
        ("Matriz: adjunta", "Transposta matriz cofatores."),
        ("Matriz: inversa formula", "A^-1 = (1/det(A)) * adj(A)."),
        ("Matriz: auto valor λ", "A*v = λ*v."),
        ("Matriz: auto vetor v", "Vetor nao nulo satisfaz."),
    ]
    RL.extend(rlp_extra3)
    print(f"  RLP expansion 3: {len(rlp_extra3)} cards")

    # --- Previdencia expansion 3 (~480 cards) ---
    prev_extra3 = [
        ("LC 109: art. 1 definicao", "Previdencia complementar: autonomia, facultativo."),
        ("LC 109: art. 3 EFPC vs EAPC", "Fechada: acesso limitado. Aberta: publico geral."),
        ("LC 109: art. 5 autorizacao previa", "EFPC precisa autorizacao orgao regulador."),
        ("LC 109: art. 6 plano mult patronado", "Multiplos patrocinadores."),
        ("LC 109: art. 7 regulamento conteudo", "Direitos, obrigacoes, beneficios, contribuicoes."),
        ("LC 109: art. 8 modalidades planos", "BD, CD, CV."),
        ("LC 109: art. 10 beneficios programados", "Aposentadoria programada."),
        ("LC 109: art. 11 beneficios nao programados", "Invalidez, morte."),
        ("LC 109: art. 12 beneficios acessorios", "Peculio, auxilio."),
        ("LC 109: art. 14 pensao", "Aos dependentes."),
        ("LC 109: art. 15 portabilidade definicao", "Transferir recursos entre planos."),
        ("LC 109: art. 16 resgate definicao", "Retirar saldo, perde direito beneficio."),
        ("LC 109: art. 17 BPD definicao", "Beneficio proporcional diferido."),
        ("LC 109: art. 18 autopatrocínio definicao", "Participante contribui ambas partes."),
        ("LC 109: art. 20 elegibilidade requisitos", "Tempo plano, idade, carência."),
        ("LC 109: art. 21 contribuicao normal", "Percentual salario."),
        ("LC 109: art. 22 contribuicao extraordinaria", "Para deficit."),
        ("LC 109: art. 24 reservas tecnicas", "Provisees beneficios concedidos e a conceder."),
        ("LC 109: art. 25 provisoes matematicas", "Calculadas atuarialmente."),
        ("LC 109: art. 26 avaliacao atuarial anual", "Obrigatoria. Hipotese, metodos."),
        ("LC 109: art. 27 deficit equacionamento", "Obrigatorio, prazo regulamentado."),
        ("LC 109: art. 28 superavit destinacao", "Contingencia, revisao."),
        ("LC 109: art. 29 reajuste beneficios", "Conforme indice regulamento."),
        ("LC 109: art. 31 estrutura organizacional", "CD, CF, DIREX."),
        ("LC 109: art. 32 conselho deliberativo", "Min 4, metade eleita."),
        ("LC 109: art. 33 conselho fiscal", "Min 3."),
        ("LC 109: art. 34 diretoria executiva", "Gestao."),
        ("LC 109: art. 35 mandato", "4 anos, reconducao."),
        ("LC 109: art. 36 vedações dirigentes", "Parentes, empregados patrocinador."),
        ("LC 109: art. 37 transparencia", "Informacoes a participantes."),
        ("LC 109: art. 38 relatorio anual", "Obrigatorio."),
        ("LC 109: art. 39 extrato individual", "Periodico."),
        ("LC 109: art. 40 auditoria anual", "Independente."),
        ("LC 109: art. 41 atuario externo", "Avaliacao independente."),
        ("LC 109: art. 42 intervencao", "PREVIC."),
        ("LC 109: art. 43 liquidacao", "Extrajudicial."),
        ("LC 109: art. 44 liquidacao procedimento", "Nomeacao liquidante."),
        ("LC 109: art. 45 competencia PREVIC", "Autorizar, fiscalizar."),
        ("LC 109: art. 46 regime disciplinar", "Sancoes."),
        ("LC 109: art. 47 penalidades", "Advertencia, multa, inabilitacao."),
        ("LC 109: art. 48 prescricao", "5 anos."),
        ("LC 109: art. 49 regime tributario", "Aplicavel."),
        ("LC 109: art. 50 PIS/PASEP", "Contribuicoes."),
        ("LC 109: art. 51 CPMF", "(Revogado)."),
        ("LC 109: art. 52 tratamento tributario", "Deducao IR."),
        ("LC 109: art. 53 fiscalizacao", "PREVIC e SUSEP."),
        ("LC 109: art. 54 convenio PREVIC/SUSEP", "Coordenacao."),
        ("LC 109: art. 55 entidades abertas", "SUSEP regula."),
        ("LC 109: art. 56 prever", "Aplicacao subsidiaria."),
        ("LC 109: art. 57 optante servidor", "Pode aderir."),
        ("LC 109: art. 58 entidade fechada patrocinada", "Uniao, estados, municipios."),
        ("LC 109: art. 59 contabilidade", "Separada por plano."),
        ("LC 109: art. 60 ativos garantidores", "Cobertura provisoes."),
        ("LC 109: art. 61 investimentos", "Conforme CMN."),
        ("LC 109: art. 62 ilegalidades", "Comunicacao orgaos."),
        ("LC 109: art. 63 responsabilidade solidaria", "Patrocinador e dirigentes."),
        ("LC 109: art. 64 disposicoes finais", "Revoga anteriores."),
        ("INSS: teto 2024", "R$ 7.786,02."),
        ("INSS: aliquota 2024", "7,5% a 14% (salario)."),
        ("INSS: aposentadoria idade", "65 homem, 62 mulher."),
        ("INSS: aposentadoria tempo contrib", "35 homem, 30 mulher (regra antes reforma)."),
        ("INSS: aposentadoria especial", "15, 20 ou 25 anos atividade insalubre."),
        ("INSS: pensao morte", "50% + 10% por dependente."),
        ("INSS: auxilio-doenca", "Carência 12 meses."),
        ("INSS: salario-maternidade", "120 dias."),
        ("INSS: salario-familia", "Baixa renda."),
        ("INSS: reabilitacao", "Readaptacao profissional."),
        ("INSS: acidente trabalho", "Estabilidade 12 meses."),
        ("INSS: fator previdenciario", "Formula expectativa sobrevida."),
        ("INSS: regra 85/95 progressiva", "Soma idade+tempo para 100%."),
        ("INSS: contribuicao individual", "20% renda."),
        ("INSS: contribuicao facultativa", "Dona casa, estudante."),
        ("INSS: carência", "180 meses."),
        ("RPPS: principios", "Contributivo, solidario, equilíbrio financeiro-atuarial."),
        ("RPPS: contribuicao servidor", "No minimo igual patrocinador."),
        ("RPPS: contribuicao patronal", "Ente federativo."),
        ("RPPS: deficit", "Ente cobre."),
        ("RPPS: aposentadoria voluntaria", "Idade + tempo."),
        ("RPPS: aposentadoria compulsoria", "75 anos."),
        ("RPPS: abono permanencia", "Servidor que pode aposentar e continua."),
        ("RPPS: pensao", "Aos dependentes."),
        ("RPPS: alíquota suplementar", "Para equacionamento."),
        ("RPC: Lei 12.618/2012", "RPC servidor federal."),
        ("RPC: Funpresp fundacao", "EFPC servidores federais."),
        ("RPC: Funpresp-Exec", "Poder Executivo."),
        ("RPC: Funpresp-Jud", "Poder Judiciario."),
        ("RPC: Funpresp-Leg", "Poder Legislativo."),
        ("RPC: teto RGPS limite", "Contribuicao ate teto."),
        ("RPC: contrapartida Uniao", "Igual contribuicao servidor."),
        ("RPC: beneficios", "Aposentadoria, pensao."),
        ("RPC: plano CD", "Contribuicao definida."),
        ("PREVCOM: plano administradora", "Gestora planos."),
        ("PREVCOM: convênio adesao", "Orgao adere ao plano."),
        ("PREVCOM: participante ativo", "Contribui ativamente."),
        ("PREVCOM: participante autopatrocinado", "Contribui ambas partes."),
        ("PREVCOM: participante vinculado", "BPD."),
        ("PREVCOM: assistido", "Recebe beneficio."),
        ("PREVCOM: dependente", "Indicado participante."),
        ("PREVCOM: beneficio aposentadoria", "Normal, antecipada, invalidez."),
        ("PREVCOM: pensao dependentes", "Apos morte participante/assistido."),
        ("PREVCOM: auxilio-doenca", "Temporario."),
        ("PREVCOM: abono anual", "13o."),
        ("PREVCOM: portabilidade saida", "Para outro plano."),
        ("PREVCOM: resgate saida", "Saldo conta."),
        ("PREVCOM: contribuicao basica", "Percentual salario."),
        ("PREVCOM: contribuicao suplementar volontaria", "Adicional."),
        ("PREVCOM: contribuicao extraordinaria", "Deficit."),
        ("PREVCOM: taxa adm", "Percentual."),
        ("PREVCOM: carência", "Periodo minimo."),
        ("PREVCOM: elegibilidade", "Tempo, idade."),
        ("PREVCOM: formulario inscricao", "Adesao formal."),
        ("PREVCOM: alteracao regulamento", "Aprovacao CD."),
        ("PREVCOM: exclusao participante", "Rescisao, morte, fraude."),
        ("PREVCOM: assembleia geral", "Eleicao conselhos."),
        ("PREVCOM: voto", "Participantes e assistidos."),
        ("PREVCOM: transparencia", "Extrato, site."),
        ("PREVCOM: ouvidoria", "Canal atendimento."),
        ("Atuario: taxa juros real atuarial definicao", "Taxa desconto fluxo beneficio."),
        ("Atuario: hipotese crescimento salarial definicao", "Projecao carreira."),
        ("Atuario: hipotese rotatividade definicao", "% saida."),
        ("Atuario: hipotese composicao familiar definicao", "% dependentes."),
        ("Atuario: hipotese mortalidade geral", "Tabua populacao."),
        ("Atuario: hipotese entrada invalidez", "Probabilidade invalidez."),
        ("Atuario: metodo credito unitario projetado", "Projeta e aloca."),
        ("Atuario: metodo agregado definicao", "Grupo nivelado."),
        ("Atuario: custo normal definicao", "Valor anual nivelado."),
        ("Atuario: custo suplementar definicao", "Amortizacao."),
        ("Atuario: provisao matematica definicao", "Valor presente beneficios."),
        ("Atuario: deficit tecnico definicao", "Passivo > ativo."),
        ("Atuario: superavit tecnico definicao", "Ativo > passivo."),
        ("Atuario: nota tecnica atuarial conteudo", "Hipotese, metodos, custos."),
        ("Atuario: avaliacao atuarial anual conteudo", "Situacao financeiro-atuarial."),
        ("Atuario: solvencia definicao", "Capacidade cumprir obrigacoes."),
    ]
    PR.extend(prev_extra3)
    print(f"  Previdencia expansion 3: {len(prev_extra3)} cards")
'''

idx = content.rfind(marker)
if idx != -1:
    new_content = content[:idx + len(marker)] + extra + content[idx + len(marker):]
    with open(path, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"Expansion 3 inserted. File size: {len(new_content)} chars")
else:
    print("ERROR: marker not found!")
