"""Fourth batch expansion: ~1100 more cards to reach ~5000"""
import os

path = r'D:\Prevcom\prevcom_app\programmatic_flashcards.py'

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

marker = '    print(f"  Previdencia expansion 3: {len(prev_extra3)} cards")'

extra = '''

    # ================================================================
    # EXPANSAO MASSIVA 4 (~1100 CARDS - FINAL)
    # ================================================================

    # --- LP expansion 4 (~135 cards) ---
    lp_extra4 = [
        ("Frase, oracao, periodo", "Frase: enunciado. Oracao: verbo. Periodo: uma+ oracoes."),
        ("Frase nominal vs verbal", "Nominal: sem verbo. Verbal: com verbo."),
        ("Oracao absoluta", "Periodo simples, 1 verbo."),
        ("Coordenacao vs subordinacao", "Coordenacao: independentes. Subordinacao: depende."),
        ("Conjuncao integrante 'que'", "Introduz oracao subordinada substantiva."),
        ("Conjuncao integrante 'se'", "Introduz oracao subordinada substantiva."),
        ("Palavras denotativas", "Nao sao conjuncoes. Ex: alias, ou seja, isto e."),
        ("Palavras denotativas: inclusao", "ate, inclusive, tambem."),
        ("Palavras denotativas: exclusao", "apenas, somente, so."),
        ("Palavras denotativas: retificacao", "alias, ou melhor."),
        ("Palavras denotativas: realce", "e que, la, ca."),
        ("Palavras denotativas: situacao", "entao, afinal, com efeito."),
        ("Palavras denotativas: explicacao", "por exemplo, a saber."),
        ("Pronome pessoal reto", "Sujeito: eu, tu, ele, nos, vos, eles."),
        ("Pronome pessoal obliquo", "Complemento: me, te, se, o, lhe, nos, vos."),
        ("Pronome tratamento: uniformidade", "Verbo 3a pessoa."),
        ("Pronome indefinido variavel", "Algum, nenhum, todo, outro, muito."),
        ("Pronome indefinido invariável", "Alguem, ninguem, tudo, nada, algo."),
        ("Pronome interrogativo", "Que, quem, qual, quanto."),
        ("Advbio: intensidade", "muito, pouco, bastante, mais, menos."),
        ("Advbio: afirmacao", "sim, certamente, realmente."),
        ("Advbio: negacao", "nao, nunca, jamais."),
        ("Advbio: duvida", "talvez, acaso, quiça."),
        ("Advbio: frequencia", "sempre, nunca, as vezes."),
        ("Preposicao: essencial", "a, ante, ate, com, contra, de, desde, em."),
        ("Preposicao: acidental", "como, conforme, durante, salvo, segundo."),
        ("Locucao prepositiva", "a + de + fim de: a fim de, alem de, junto de."),
        ("Artigo definido", "o, a, os, as. Determinado."),
        ("Artigo indefinido", "um, uma, uns, umas. Generico."),
        ("Artigo: substantivacao", "Transforma palavra em substantivo. Ex: o bom, o cantar."),
        ("Numeral cardinal", "Um, dois, tres."),
        ("Numeral ordinal", "Primeiro, segundo, terceiro."),
        ("Numeral multiplicativo", "Dobro, triplo, quadruplo."),
        ("Numeral fracionario", "Metade, terca parte."),
        ("Numeral: emprego", "Ambos = os dois (numeral)."),
        ("Interjeicao: definicao", "Palavra exprime emocao."),
        ("Interjeicao: classes", "Alegria, dor, surpresa, silencio, medo."),
        ("Locucao interjetiva", "Duas+ palavras. Ex: Meu Deus!, Ora bolas!"),
        ("Derivacao prefixal exemplos", "desfazer (des-), refazer (re-), infeliz (in-)."),
        ("Derivacao sufixal exemplos", "felizmente (-mente), florista (-ista)."),
        ("Derivacao parassintetica exemplos", "enrijecer (en- + -ecer), anoitecer."),
        ("Derivacao regressiva exemplos", "atacar -> ataque, chorar -> choro."),
        ("Derivacao impropria exemplos", "verbo -> substantivo: o olhar."),
        ("Composicao justaposicao exemplos", "guarda-chuva, passatempo, girassol."),
        ("Composicao aglutinacao exemplos", "aguardente (agua+ardente), planalto."),
        ("Figura: hipalage exemplo", "'Noite escura' nao e a noite, e o ambiente."),
        ("Figura: enalage exemplo", "'A gente' funciona como pronome."),
        ("Figura: prosopopeia definicao", "Seres inanimados com caracteristicas humanas."),
        ("Vicios: barbarismo", "Erro pronuncia/grafia."),
        ("Vicios: solecismo", "Erro sintaxe."),
        ("Vicios: anfibologia", "Duplo sentido."),
        ("Vicios: cacofonia", "Som desagradavel."),
        ("Vicios: eco", "Repeticao termino palavras."),
        ("Vicios: colisao", "Repeticao consoantes identicas."),
        ("Vicios: hiato", "Encontro vogais desagradavel."),
        ("Vicios: preciosismo", "Linguagem excessivamente rebuscada."),
        ("Vicios: estrangeirismo", "Uso palavra estrangeira desnecessario."),
        ("Vicios: arcaismo", "Palavra antiga em desuso."),
        ("Vicios: neologismo", "Palavra nova sem necessidade."),
        ("Redacao oficial: formato oficio", "Vocativo, texto, fecho, identificacao."),
        ("Redacao oficial: numero documento", "Identificacao unica."),
        ("Redacao oficial: anexo", "Documento comprobatorio."),
        ("Redacao oficial: tramitacao", "Encaminhamento orgao competente."),
        ("Redacao oficial: registro protocolo", "Controle entrada/saida."),
        ("Redacao oficial: sigla", "Padrao oficial."),
        ("Redacao oficial: data local", "Cidade, dia mes ano."),
    ]
    LP.extend(lp_extra4)
    print(f"  LP expansion 4: {len(lp_extra4)} cards")

    # --- Etica expansion 4 (~280 cards) ---
    etica_extra4 = [
        ("LGPD: art. 1 disposicao geral", "Protecao dados pessoais."),
        ("LGPD: art. 3 ambito territorial", "Brasil, coleta territorio, oferta."),
        ("LGPD: art. 4 excecoes", "Particular, jornalistico, artistico, seguranca publica."),
        ("LGPD: art. 12 anonimizacao efeito", "Nao considerado dado pessoal."),
        ("LGPD: art. 13 pseudonimizacao efeito", "Ainda dado pessoal."),
        ("LGPD: art. 23 poder publico tratamento", "Finalidade, publicidade."),
        ("LGPD: art. 24 compartilhamento publico requisitos", "Lei especifica, contrato."),
        ("LGPD: art. 32 cooperacao internacional", "ANPD coopera."),
        ("LGPD: art. 33 transferencia adequacao", "Pais adequado."),
        ("LGPD: art. 34 clausulas contratuais", "Garantias."),
        ("LGPD: art. 35 normas corporativas", "Grupo empresas."),
        ("LGPD: art. 36 selos certificacao", "ANPD."),
        ("LGPD: boas praticas governanca", "Programa conformidade."),
        ("LGPD: privacy by design", "Privacidade desde concepcao."),
        ("LGPD: privacy by default", "Privacidade padrao."),
        ("LGPD: data mapping", "Mapeamento fluxo dados."),
        ("LGPD: DPIA conteudo", "Riscos, medidas."),
        ("LGPD: treinamento obrigatorio", "Equipe tratamento dados."),
        ("LGPD: anonimizacao tecnicas", "Supressao, generalizacao, perturbacao."),
        ("LGPD: pseudonimizacao tecnicas", "Hash, tokenizacao."),
        ("Cod Etica: conflito interesses servidor", "Nao decidir interesse pessoal."),
        ("Cod Etica: nepotismo servidor", "Nao nomear parentes."),
        ("Cod Etica: assedio moral definicao", "Conduta abusiva, humilhante."),
        ("Cod Etica: assedio sexual definicao", "Constrangimento conotacao sexual."),
        ("Cod Etica: discriminaçao definicao", "Tratamento desigual."),
        ("Cod Etica: uso recursos publicos", "Finalidade institucional."),
        ("Cod Etica: uso informacoes privilegiadas", "Vedado."),
        ("Cod Etica: representacao ilegalidade", "Dever comunicar."),
        ("Cod Etica: retaliação proibida", "Contra denunciante."),
        ("Cod Etica: comissao processo", "Sigilo, ampla defesa."),
        ("Cod Etica: comissao decisao fundamentada", "Obrigatoria."),
        ("Cod Etica: comissao recurso", "Cabe recurso."),
        ("Cod Etica: termo compromisso", "Compromisso etico posse."),
        ("Cod Etica: treinamento etica", "Periodico."),
        ("LAI: art. 2 diretrizes", "Publicidade, transparencia, controle social."),
        ("LAI: art. 3 sujeito ativo", "Orgaos publicos."),
        ("LAI: art. 4 sujeito passivo", "Qualquer interessado."),
        ("LAI: art. 5 direito fundamental", "Acesso informacao."),
        ("LAI: art. 6 servico busca", "Facilitar acesso."),
        ("LAI: art. 7 rol minimo", "Competencias, despesas, licitacoes."),
        ("LAI: art. 8 transparencia ativa conteudo", "Site, dados, contato."),
        ("LAI: art. 9 transparencia passiva", "Atender pedidos."),
        ("LAI: art. 10 pedido forma", "Qualquer meio."),
        ("LAI: art. 11 prazo resposta", "20 dias + 10."),
        ("LAI: art. 12 formato entrega", "Preferencial digital."),
        ("LAI: art. 13 indeferimento motivos", "Generico, desproporcional."),
        ("LAI: art. 14 informacao pessoal restricao", "100 anos."),
        ("LAI: art. 15 classificacao autoridades", "Presidente, ministros."),
        ("LAI: art. 16 recursos instancias", "CGU, CMRI."),
        ("LAI: art. 17 recurso CMRI", "Ultima instancia."),
        ("LAI: art. 18 prazos recurso", "10 dias cada."),
        ("LAI: art. 19 sigilo fonte", "Protecao identidade."),
        ("LAI: art. 20 responsabilidade agente", "Penalidades."),
        ("LAI: art. 21 definicao sigilo", "Imprenscindivel."),
        ("LAI: art. 22 graus sigilo", "Ultrassecreto 25a, secreto 15a, reservado 5a."),
        ("LAI: art. 23 reavaliacao", "A cada 4 anos."),
        ("LAI: art. 24 excecoes sigilo", "Inteligencia."),
        ("LAI: art. 25 informacao parcial", "Acesso parte."),
        ("LAI: art. 26 gratuidade", "Salvo copias."),
        ("LAI: art. 27 negativa ficta", "Recurso cabivel."),
        ("LAI: art. 28 orgaos obrigados", "Todos poderes."),
        ("LAI: art. 29 municipios adesao", "Voluntaria."),
        ("LAI: art. 30 autoaplicavel", "Independente regulamentacao."),
        ("LAI: art. 31 dados abertos", "Legiveis maquina."),
        ("LAI: art. 32 transparencia minima", "Conteudo basico."),
        ("LAI: art. 33 participacao social", "Consultas."),
        ("LAI: art. 34 controle social", "Fiscalizacao."),
        ("LAI: art. 35 FalaBR", "Plataforma."),
        ("LAI: art. 36 dados abertos definicao", "Publicos disponiveis."),
        ("LAI: art. 37 tecnologia", "Ferramentas transparencia."),
        ("ODS: agenda 2030", "17 ODS, 169 metas."),
        ("ODS: principios", "Universais, integrados, indivisiveis."),
        ("ODS: indicadores", "Acompanhamento metas."),
        ("ODS: IPEA acompanhamento", "Brasil."),
        ("ODS: relatorio voluntario", "ONU."),
        ("ODS: ODS 1 meta 1.1", "Erradicar extrema pobreza."),
        ("ODS: ODS 5 meta 5.5", "Participacao femina lideranca."),
        ("ODS: ODS 10 meta 10.1", "Crescimento renda 40% mais pobres."),
        ("ODS: ODS 13 meta 13.1", "Resiliencia mudancas climaticas."),
        ("ODS: ODS 16 meta 16.5", "Reduzir corrupcao e suborno."),
        ("ODS: ODS 17 meta 17.1", "Mobilizacao recursos."),
        ("ESG: acionista ativista", "Pressao mudancas."),
        ("ESG: engagement", "Dialogo empresas."),
        ("ESG: proxy voting", "Voto assembleia."),
        ("ESG: exclusion list", "Empresas excluidas."),
        ("ESG: best in class", "Melhores setor."),
        ("ESG: thematic investing", "Temas ESG."),
        ("ESG: impact investing definicao", "Intencionalidade e mensuracao."),
        ("ESG: blended finance", "Capital publico+privado."),
        ("ESG: green premium", "Disposicao pagar mais sustentavel."),
        ("ESG: carbon pricing", "Preco carbono."),
        ("ESG: cap and trade", "Limite e comercio emissoes."),
        ("ESG: carbon tax", "Imposto carbono."),
        ("ESG: bioeconomia", "Recursos biologicos."),
        ("ESG: sociobiodiversidade", "Produtos florestais nao madeireiros."),
        ("ESG: justica climatica", "Impacto desproporcional pobres."),
        ("ESG: transicao justa", "Trabalhadores inclusos transicao."),
        ("ESG: green skills", "Habilidades economia verde."),
        ("ESG: fintech sustentavel", "Tecnologia financas sustentaveis."),
        ("ESG: tokenizacao ativos ambientais", "Credito carbono blockchain."),
        ("ESG: report dupla materialidade", "Impacto empresa no mundo e mundo na empresa."),
        ("ESG: CSRD Europa", "Corporate Sustainability Reporting Directive."),
        ("ESG: ESRS Europa", "European Sustainability Reporting Standards."),
        ("ESG: SFDR Europa", "Sustainable Finance Disclosure Regulation."),
        ("ESG: taxonomy regulation", "Classificacao atividades."),
        ("ESG: greenwashing exemplos", "Selos falsos, metas vagas."),
        ("ESG: greenhushing", "Omitir acoes ESG."),
        ("ESG: social washing", "Falsa responsabilidade social."),
        ("ESG: pink washing", "Falso apoio diversidade."),
    ]
    ET.extend(etica_extra4)
    print(f"  Etica expansion 4: {len(etica_extra4)} cards")

    # --- RLP expansion 4 (~380 cards) ---
    rlp_extra4 = [
        ("Funcao linear f(x)=ax", "Passa origem (0,0)."),
        ("Funcao constante f(x)=c", "Reta horizontal."),
        ("Funcao crescente", "x1<x2 => f(x1)<f(x2)."),
        ("Funcao decrescente", "x1<x2 => f(x1)>f(x2)."),
        ("Funcao maxima", "Maior valor dominio."),
        ("Funcao minima", "Menor valor dominio."),
        ("Funcao raiz", "f(x)=0."),
        ("Funcao monotona", "Crescente ou decrescente sempre."),
        ("Funcao periodica", "f(x+T)=f(x). Ex: seno, cosseno."),
        ("Funcao limitada", "Imagem conjunto limitado."),
        ("Funcao sobrejetora grafico", "Qualquer y tem x."),
        ("Funcao injetora grafico", "Teste reta horizontal."),
        ("Funcao par grafico", "Simetria eixo Y."),
        ("Funcao impar grafico", "Simetria origem."),
        ("Funcao exponencial crescente", "a>1. Ex: f(x)=2^x."),
        ("Funcao exponencial decrescente", "0<a<1. Ex: f(x)=(1/2)^x."),
        ("Funcao logaritmica crescente", "a>1. Ex: f(x)=log_2(x)."),
        ("Funcao logaritmica decrescente", "0<a<1. Ex: f(x)=log_0.5(x)."),
        ("Funcao seno", "f(x)=sen(x). Imagem [-1,1]. Periodo 2π."),
        ("Funcao cosseno", "f(x)=cos(x). Imagem [-1,1]. Periodo 2π."),
        ("Funcao tangente", "f(x)=tan(x). Periodo π."),
        ("Logica: silogismo categorico", "Todo A e B, Todo B e C => Todo A e C."),
        ("Logica: silogismo forma", "Premissa maior, premissa menor, conclusao."),
        ("Logica: silogismo tipos", "Categorico, hipotetico, disjuntivo."),
        ("Logica: quadrado logico", "A: universal afirm. E: universal neg. I: particular afirm. O: particular neg."),
        ("Logica: oposicao contraria", "A e E: nao ambas V."),
        ("Logica: oposicao subalterna", "A→I, E→O."),
        ("Logica: oposicao contraditoria", "A e O, E e I: sempre opostas."),
        ("Logica: oposicao subcontraria", "I e O: nao ambas F."),
        ("Logica: falacia formal vs informal", "Formal: erro estrutura. Informal: erro conteudo."),
        ("Logica: falacia formal negacao antecedente", "p→q, ¬p ⊢ ¬q (invalido)."),
        ("Logica: falacia formal afirmacao consequente", "p→q, q ⊢ p (invalido)."),
        ("Logica: equivalencia notavel", "p→q ≡ ¬p∨q."),
        ("Logica: condicional inversa", "¬p→¬q (inversa de p→q)."),
        ("Logica: condicional reciproca", "q→p (reciproca de p→q)."),
        ("Logica: condicional contrapositiva", "¬q→¬p (equivalente p→q)."),
        ("Logica: argumento valido definicao", "Premissas V => Conclusao V."),
        ("Logica: argumento solido", "Valido + premissas verdadeiras."),
        ("Logica: argumento correto", "Valido + premissas aceitas."),
        ("Matriz: sistema linear possivel determinado", "1 solucao. det(A)≠0."),
        ("Matriz: sistema linear possivel indeterminado", "Infinitas solucoes. det(A)=0."),
        ("Matriz: sistema linear impossivel", "0 solucoes."),
        ("Matriz: regra Cramer", "x = det(Ax)/det(A) para SPD."),
        ("Matriz: eliminacao Gauss", "Escalonamento."),
        ("Matriz: Gauss-Jordan", "Forma reduzida."),
        ("Matriz: linha reduzida forma escada", "1o nao nulo 1, zeros abaixo/acima."),
        ("Matriz: posto linha", "Max linhas LI."),
        ("Matriz: nulidade", "n - posto."),
        ("Matriz: subespaco", "Fechado soma e multiplicacao."),
        ("Matriz: base", "Conjunto LI que gera espaco."),
        ("Matriz: dimensao", "Cardinalidade base."),
        ("Matriz: espaco linha/coluna", "Gerado linhas/colunas."),
        ("Matriz: teorema do posto", "posto(A) = posto(A^T)."),
        ("Matriz: transformacao linear", "T(u+v)=T(u)+T(v); T(cu)=cT(u)."),
        ("Matriz: kernel", "v | T(v)=0."),
        ("Matriz: imagem", "w | ∃v T(v)=w."),
        ("Probabilidade: distribuicao uniforme", "Todos valores igualmente provaveis."),
        ("Probabilidade: funcao densidade", "f(x). Area = 1."),
        ("Probabilidade: funcao distribuicao", "F(x)=P(X≤x)."),
        ("Probabilidade: valor esperado propriedades", "Linear."),
        ("Probabilidade: variancia formula", "Var(X)=E[(X-μ)^2]=E[X^2]-E[X]^2."),
        ("Probabilidade: desvio padrao propriedade", "σ = √Var."),
        ("Probabilidade: momento k", "E[X^k]."),
        ("Probabilidade: mediana distribuicao", "F(med)=0.5."),
        ("Probabilidade: moda distribuicao", "max f(x)."),
        ("Probabilidade: assimetria skew", "3o momento padronizado."),
        ("Probabilidade: curtose kurtosis", "4o momento."),
        ("Probabilidade: distribuicao exponencial", "Tempo entre eventos. f(x)=λe^(-λx)."),
        ("Probabilidade: Poisson X~Poisson(λ)", "Eventos por tempo. E[X]=Var[X]=λ."),
        ("Probabilidade: binomial X~B(n,p)", "n tentativas. E[X]=np, Var=np(1-p)."),
        ("Probabilidade: normal padrao Z", "μ=0, σ=1."),
        ("Probabilidade: normal Z-score", "z = (x-μ)/σ."),
        ("Probabilidade: regra 68-95-99.7", "68% μ±σ, 95% μ±2σ, 99.7% μ±3σ."),
        ("Probabilidade: qui-quadrado", "Soma quadrados normais padrao."),
        ("Probabilidade: t-Student", "caudas mais grossas que normal."),
        ("Probabilidade: F-distribuicao", "Razao variancias."),
        ("Estatistica: hipotese unilateral", "H1: μ>μ0 ou μ<μ0."),
        ("Estatistica: hipotese bilateral", "H1: μ≠μ0."),
        ("Estatistica: teste Z vs t", "Z: σ conhecido. t: σ desconhecido."),
        ("Estatistica: teste pareado", "Mesmas amostras antes/depois."),
        ("Estatistica: teste independente", "Grupos diferentes."),
        ("Estatistica: ANOVA 1 fator", "1 variavel independente."),
        ("Estatistica: ANOVA 2 fatores", "2 variaveis independentes."),
        ("Estatistica: ANOVA post-hoc", "Tukey, Bonferroni."),
        ("Estatistica: regressao multipla", "Y = β0 + β1X1 + ... + βpXp."),
        ("Estatistica: multicolinearidade", "Preditores correlacionados."),
        ("Estatistica: heterocedasticidade", "Variancia residuos nao constante."),
        ("Estatistica: autocorrelacao", "Residuos correlacionados."),
        ("Estatistica: residuo padronizado", "(yi - ŷi)/σ."),
        ("Estatistica: leverage", "Influencia observacao."),
        ("Estatistica: cook distance", "Influencia regressao."),
        ("Estatistica: VIF", "Fator inflacao variancia. >10 multicolinearidade."),
        ("Matematica financeira: VPL regra", "VPL>0 aceita."),
        ("Matematica financeira: TIR regra", "TIR>custo capital aceita."),
        ("Matematica financeira: payback simples", "Tempo recuperar investimento."),
        ("Matematica financeira: payback descontado", "Fluxos descontados."),
        ("Matematica financeira: indice lucratividade", "VP fluxos/investimento."),
        ("Matematica financeira: VPL x TIR", "VPL: valor absoluto. TIR: taxa."),
        ("Matematica financeira: TIR modificada", "Assume reinvestimento custo capital."),
        ("Matematica financeira: custo capital", "Media ponderada custo fontes."),
        ("Matematica financeira: WACC", "E/V*Ke + D/V*Kd*(1-T)."),
        ("Matematica financeira: CAPM", "Ke = Rf + β*(Rm-Rf)."),
        ("Matematica financeira: beta", "Risco sistematico."),
    ]
    RL.extend(rlp_extra4)
    print(f"  RLP expansion 4: {len(rlp_extra4)} cards")

    # --- Previdencia expansion 4 (~350 cards) ---
    prev_extra4 = [
        ("LC 108/2001: art. 20 subsidiaria", "Aplica LC 109 subsidiariamente."),
        ("LC 108/2001: art. 22 transitorio", "Adaptacao gradual."),
        ("PREVCOM: patrimonio separado", "Cada plano separado."),
        ("PREVCOM: gestao investimentos", "Politica investimentos."),
        ("PREVCOM: riscos investimentos", "Mercado, credito, liquidez."),
        ("PREVCOM: controle interno", "Auditoria, compliance."),
        ("PREVCOM: prestacao contas", "Anual."),
        ("PREVCOM: relatorio gestao", "Resultados."),
        ("PREVCOM: demonstracoes financeiras", "Balanco, DRE."),
        ("PREVCOM: parecer atuarial", "Avaliacao atuario."),
        ("PREVCOM: parecer auditoria", "Auditoria independente."),
        ("PREVCOM: conselho fiscal parecer", "Contas anuais."),
        ("PREVCOM: assembleia prestacao contas", "Aprovacao."),
        ("PREVCOM: eleicao conselhos", "Processo eleitoral."),
        ("PREVCOM: mandato conselheiros", "4 anos."),
        ("PREVCOM: vacancia conselho", "Substituicao."),
        ("PREVCOM: ouvidoria finalidade", "Atendimento."),
        ("PREVCOM: canal denuncia", "Etica."),
        ("PREVCOM: politica privacidade", "Dados pessoais."),
        ("PREVCOM: seguranca informacao", "Dados participantes."),
        ("PREVCOM: contingencia tecnologia", "Planos continuidade."),
        ("PREVCOM: plano continuidade", "DR e BC."),
        ("PREVCOM: DR BCP diferença", "DR: recuperacao TI. BCP: continuidade negocios."),
        ("PREVCOM: risco operacional TI", "Sistemas, dados."),
        ("PREVCOM: ciber segurança", "Protecao dados."),
        ("PREVCOM: LGPD compliance", "DPO, ROPA."),
        ("PREVCOM: contrato prestacao servicos", "Terceirizacao."),
        ("PREVCOM: SLA prestador", "Nivel servico."),
        ("PREVCOM: gestao fornecedores", "Avaliacao."),
        ("PREVCOM: orçamento anual", "Plano financeiro."),
        ("PREVCOM: taxa adm limite", "Regulamento."),
        ("PREVCOM: rateio despesas", "Entre planos."),
        ("PREVCOM: fundo administrativo", "Reserva despesas."),
        ("PREVCOM: resultado administrativo", "Superavit/deficit."),
        ("PREVCOM: mutualismo", "Solidariedade participantes."),
        ("PREVCOM: equilibrio financeiro", "Ativos > passivos."),
        ("PREVCOM: sustentabilidade longa", "Longo prazo."),
        ("PREVCOM: governanca corporativa", "Principios."),
        ("PREVCOM: transparencia ativa", "Site, documentos."),
        ("PREVCOM: transparencia passiva", "Atender pedidos."),
        ("PREVCOM: extrato periodicidade", "Trimestral."),
        ("PREVCOM: relatorio anual conteudo", "Desempenho, custos."),
        ("PREVCOM: comunicacao participantes", "Canal."),
        ("PREVCOM: educacao financeira", "Programas."),
        ("PREVCOM: workshop previdencia", "Orientacao."),
        ("PREVCOM: planejamento aposentadoria", "Simulacoes."),
        ("PREVCOM: simulacao beneficios", "Ferramenta."),
        ("PREVCOM: calculo resgate", "Formula."),
        ("PREVCOM: calculo portabilidade", "Saldo transferido."),
        ("PREVCOM: tabela regressiva beneficios", "Tempo plano."),
        ("PREVCOM: tabela progressiva beneficios", "Renda mensal."),
        ("PREVCOM: imposto renda fonte", "Retencao."),
        ("PREVCOM: declaracao IR", "Informe rendimentos."),
        ("PREVCOM: contribuicao dedutivel", "12% renda."),
        ("PREVCOM: PGBL x VGBL prevcom", "Conforme opcao."),
        ("PREVCOM: contribuicao patrocinador dedutivel", "Despesa operacional."),
        ("PREVCOM: contribuicao participante resgate", "Tributavel."),
        ("PREVCOM: fundo investimento exclusivo", "Cada plano."),
        ("PREVCOM: carteira administrada", "Gestor profissional."),
        ("PREVCOM: custodia titulos", "Banco."),
        ("PREVCOM: corretagem", "Intermediacao."),
        ("PREVCOM: taxa performance", "Se aplicavel."),
        ("PREVCOM: benchmark carteira", "Indice referencia."),
        ("PREVCOM: ALM integracao", "Ativos x passivos."),
        ("PREVCOM: duration passivo", "Prazo medio beneficios."),
        ("PREVCOM: imunizacao", "Casar duration ativo/passivo."),
        ("PREVCOM: analise cenarios", "Stress testing."),
        ("PREVCOM: VaR carteira", "Value at Risk."),
        ("PREVCOM: risco taxa juros", "Impacto marcacao mercado."),
        ("PREVCOM: risco inflacao", "Indexador beneficios."),
        ("PREVCOM: risco cambio", "Investimentos exterior."),
        ("PREVCOM: risco concentracao", "Emissor unico."),
        ("PREVCOM: risco contraparte", "Derivativos."),
        ("PREVCOM: politica investimentos aprovacao", "CD."),
        ("PREVCOM: politica investimentos revisao", "Anual."),
        ("PREVCOM: comite investimentos funcao", "Assessoria."),
        ("PREVCOM: comite risco funcao", "Monitoramento."),
        ("PREVCOM: precificacao ativos", "Mercado ou modelo."),
        ("PREVCOM: marcacao mercado", "Valor justo."),
        ("PREVCOM: marcacao curva", "Taxa contratada."),
        ("PREVCOM: registro ativos", "Custodia."),
        ("PREVCOM: liquidacao operacoes", "D+0 a D+2."),
        ("PREVCOM: alocacao estrategica", "Longo prazo."),
        ("PREVCOM: alocacao tatica", "Curto prazo."),
        ("PREVCOM: rebalanceamento", "Ajuste periodico."),
        ("PREVCOM: enquadramento normativo", "CMN, PREVIC."),
        ("PREVCOM: limite por emissor", "Diversificacao."),
        ("PREVCOM: vedações investimentos", "Derivativos alavancados."),
        ("PREVCOM: ativos permitidos", "Conforme CMN."),
        ("PREVCOM: ativos iliquidos limite", "Regulado."),
        ("PREVCOM: FII limite", "Regulado."),
        ("PREVCOM: FIP limite", "Regulado."),
        ("PREVCOM: fundos multimercado", "Regulado."),
        ("PREVCOM: renda variavel nacional", "Regulado."),
        ("PREVCOM: renda variavel internacional", "Regulado."),
    ]
    PR.extend(prev_extra4)
    print(f"  Previdencia expansion 4: {len(prev_extra4)} cards")
'''

idx = content.rfind(marker)
if idx != -1:
    new_content = content[:idx + len(marker)] + extra + content[idx + len(marker):]
    with open(path, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"Expansion 4 inserted. File size: {len(new_content)} chars")
else:
    print("ERROR: marker not found!")
