"""Final batch expansion 2: ~470 more cards"""
import os

path = r'D:\Prevcom\prevcom_app\programmatic_flashcards.py'

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

marker = '    print(f"  Previdencia final: {len(prev_final)} cards")'

extra = '''

    # --- LP final 2 (~30 cards) ---
    lp_final2 = [
        ("Semantica: campo semantico", "Palavras mesmo tema."),
        ("Semantica: sinonimos perfeitos", "Mesmo significado. Raros."),
        ("Semantica: sinonimos imperfeitos", "Proximos significado."),
        ("Semantica: antonimos complementares", "Um exclui outro. Ex: vivo/morto."),
        ("Semantica: antonimos graduaveis", "Gradacao. Ex: quente/frio."),
        ("Semantica: antonimos reciprocos", "Pressupoem mutuamente. Ex: comprar/vender."),
        ("Semantica: homonimos perfeitos", "Mesma grafia e som, sentido diferente. Ex: manga."),
        ("Semantica: paronimos exemplos", "Comprimento/cumprimento, trafego/trafico."),
        ("Semantica: hiperonimo/hiponimo", "Generico/especifico. Ex: mobilia/cadeira."),
        ("Semantica: polissemia", "Palavra varios sentidos relacionados."),
        ("Semantica: denotacao x conotacao", "Literal x figurado."),
        ("Semantica: ambiguidade", "Mais de uma interpretacao."),
        ("Semantica: redundancia", "Repeticao desnecessaria."),
        ("Semantica: neologismo", "Palavra nova."),
        ("Semantica: arcaismo", "Palavra antiga."),
        ("Semantica: estrangeirismo", "Palavra de outra lingua."),
        ("Semantica: giria", "Linguagem grupo social."),
        ("Semantica: jargao", "Linguagem profissional."),
        ("Semantica: cliche/Chavao", "Expressao desgastada."),
        ("Semantica: eufemismo definicao", "Suavizar expressao."),
        ("Semantica: disfemismo definicao", "Engrossar expressao."),
        ("Textualidade: coesao por referencia", "Pronomes, artigos, adverbios."),
        ("Textualidade: coesao por substituicao", "Sinonimos, hiperonimos."),
        ("Textualidade: coesao por elipse", "Omissao."),
        ("Textualidade: coesao por conjuncao", "Conectivos."),
        ("Textualidade: coesao lexical", "Repeticao, campo semantico."),
        ("Textualidade: coerencia interna", "Logica interna texto."),
        ("Textualidade: coerencia externa", "Adequacao contexto."),
    ]
    LP.extend(lp_final2)
    print(f"  LP final2: {len(lp_final2)} cards")

    # --- Etica final 2 (~120 cards) ---
    etica_final2 = [
        ("Improbidade: art. 9 I", "Receber vantagem."),
        ("Improbidade: art. 9 II", "Perceber bem."),
        ("Improbidade: art. 9 III", "Superfaturar contrato."),
        ("Improbidade: art. 9 IV", "Utilizar recursos em beneficio proprio."),
        ("Improbidade: art. 9 V", "Receber beneficio fiscal indevido."),
        ("Improbidade: art. 9 VI", "Adquirir bem com valor inferior."),
        ("Improbidade: art. 9 VII", "Perceber vantagem para intermediar."),
        ("Improbidade: art. 9 VIII", "Incorporar ao patrimonio."),
        ("Improbidade: art. 9 IX", "Usar bens publicos em beneficio."),
        ("Improbidade: art. 9 X", "Desviar bens publicos."),
        ("Improbidade: art. 9 XI", "Adquirir bens incompativel."),
        ("Improbidade: art. 9 XII", "Ocultar bens."),
        ("Improbidade: art. 10 I", "Dano ao erario."),
        ("Improbidade: art. 10 II", "Contratar sem licitacao."),
        ("Improbidade: art. 10 III", "Frustrar licitacao."),
        ("Improbidade: art. 10 IV", "Liberar verba irregular."),
        ("Improbidade: art. 10 V", "Beneficiar terceiro."),
        ("Improbidade: art. 10 VI", "Permitir acumulo ilegal."),
        ("Improbidade: art. 10 VII", "Conceder beneficio fiscal indevido."),
        ("Improbidade: art. 10 VIII", "Fazer operacao financeira irregular."),
        ("Improbidade: art. 10 IX", "Ordenar despesa sem autorizacao."),
        ("Improbidade: art. 10 X", "Atingir verba."),
        ("Improbidade: art. 10 XI", "Permitir desvio."),
        ("Improbidade: art. 10 XII", "Frustrar direito social."),
        ("Improbidade: art. 11 I", "Praticar ato visando fim proibido."),
        ("Improbidade: art. 11 II", "Retardar ato."),
        ("Improbidade: art. 11 III", "Revelar segredo."),
        ("Improbidade: art. 11 IV", "Negar publicidade."),
        ("Improbidade: art. 11 V", "Frustrar carater seletivo."),
        ("Improbidade: art. 11 VI", "Nomear parente nepotismo."),
        ("Improbidade: art. 11 VII", "Assumir obrigacao sem recurso."),
        ("Improbidade: art. 11 VIII", "Acumular cargos."),
        ("Improbidade: art. 11 IX", "Deixar de prestar contas."),
        ("Improbidade: art. 12 penas enriquecimento", "Perda bens, ressarcimento, multa 24x, perda funcao, suspensao 8-10a."),
        ("Improbidade: art. 12 penas prejuizo", "Ressarcimento, multa 12x, perda funcao, suspensao 6-10a."),
        ("Improbidade: art. 12 penas principios", "Multa 12x, perda funcao, suspensao 3-5a."),
        ("Improbidade: transacao", "Acordo antes decisao."),
        ("Improbidade: prescricao intercorrente", "Paralisacao processo."),
        ("Corrupcao: ativa definicao", "Oferecer vantagem a agente publico."),
        ("Corrupcao: passiva definicao", "Agente solicita/recebe vantagem."),
        ("Corrupcao: art. 317 CP", "Corrupcao passiva: 2-12 anos."),
        ("Corrupcao: art. 333 CP", "Corrupcao ativa: 1-8 anos."),
        ("Prevaricacao: art. 319 CP", "Retardar ato indevidamente."),
        ("Concussao: art. 316 CP", "Exigir vantagem indevida."),
        ("Excesso de exacao: 316 par", "Cobrar tributo indevido."),
        ("Advocacia administrativa: art. 321 CP", "Patrocinar interesse privado."),
        ("Lavagem: Lei 9.613/98", "Ocultacao bens."),
        ("Lavagem: art. 1 I", "Ocultar natureza bens."),
        ("Lavagem: art. 1 II", "Importar bens ocultos."),
        ("Lavagem: art. 1 III", "Adquirir bens ocultos."),
        ("Lavagem: art. 1 IV", "Manter bens ocultos."),
        ("Lavagem: penas", "3-10 anos."),
        ("Lavagem: COAF", "Unidade inteligencia financeira."),
        ("Lavagem: comunicacao obrigatoria", "Operacoes suspeitas."),
        ("Lavagem: due diligence cliente", "Identificacao."),
        ("Lavagem: PEP", "Pessoa exposta politicamente."),
        ("Lavagem: PEP monitoramento", "Redobrado."),
        ("Lavagem: BCB 36.292", "Norma COAF."),
    ]
    ET.extend(etica_final2)
    print(f"  Etica final2: {len(etica_final2)} cards")

    # --- RLP final 2 (~160 cards) ---
    rlp_final2 = [
        ("Matriz: Vandermonde", "det = produto (xi-xj)."),
        ("Matriz: diagonalizacao", "A = PDP^-1."),
        ("Matriz: forma quadratica", "x^T*A*x."),
        ("Matriz: definida positiva", "x^T*A*x >0 para todo x diferente 0."),
        ("Matriz: decomposicao LU", "A = L*U."),
        ("Matriz: Cholesky", "A = G*G^T para positiva definida."),
        ("Matriz: QR", "A = Q*R."),
        ("Matriz: SVD", "A = U*Sigma*V^T."),
        ("Matriz: pseudo-inversa", "A^+ = V*Sigma^+*U^T."),
        ("Logica: algebra boole", "Operacoes AND, OR, NOT."),
        ("Logica: algebra boole propriedades", "Comutativa, associativa, distributiva."),
        ("Logica: lei absorcao", "p OR (p AND q) equiv p."),
        ("Logica: lei identidade", "p OR F equiv p; p AND V equiv p."),
        ("Logica: lei complemento", "p OR NOT p equiv V."),
        ("Logica: lei idempotencia", "p AND p equiv p."),
        ("Logica: lei dominacao", "p OR V equiv V; p AND F equiv F."),
        ("Logica: dupla negacao", "NOT(NOT p) equiv p."),
        ("Logica: exportacao", "(p AND q) -> r equiv p -> (q -> r)."),
        ("Logica: importacao", "p -> (q -> r) equiv (p AND q) -> r."),
        ("Logica: comutatividade", "p AND q equiv q AND p."),
        ("Logica: associatividade", "(p AND q) AND r equiv p AND (q AND r)."),
        ("Logica: transitividade", "p->q, q->r portanto p->r."),
        ("Logica: correcao", "Tudo provavel e verdadeiro."),
        ("Logica: completude", "Tudo verdadeiro e provavel."),
        ("Logica: metalinguagem", "Linguagem sobre linguagem."),
        ("Logica: linguagem objeto", "Linguagem estudada."),
        ("Logica: formula bem formada", "Expressao sintaticamente correta."),
        ("Logica: escopo quantificador", "Regiao atuacao quantificador."),
        ("Logica: variavel livre", "Fora escopo quantificador."),
        ("Logica: variavel ligada", "Dentro escopo quantificador."),
        ("Logica: substituicao", "Troca variavel por termo."),
        ("Logica: unificacao", "Tornar termos iguais."),
        ("Matematica: numeros naturais N", "0,1,2,3,..."),
        ("Matematica: numeros inteiros Z", "...-2,-1,0,1,2,..."),
        ("Matematica: numeros racionais Q", "a/b, b diferente 0."),
        ("Matematica: numeros reais R", "Racionais + irracionais."),
        ("Matematica: numeros complexos C", "a+bi. i^2=-1."),
        ("Matematica: numero irracional", "Nao periodico, nao fracao. Ex: pi, sqrt2, e."),
        ("Matematica: inclusao conjuntos", "N contido Z contido Q contido R contido C."),
        ("Matematica: densidade Q em R", "Entre 2 reais ha racional."),
        ("Matematica: corpo ordenado", "R: ordenado, completo."),
        ("Matematica: supremo", "Menor limite superior."),
        ("Matematica: infimo", "Maior limite inferior."),
        ("Matematica: maximo", "Maior elemento conjunto."),
        ("Matematica: minimo", "Menor elemento conjunto."),
        ("Matematica: limite definicao", "L valor que funcao se aproxima."),
        ("Matematica: derivada definicao", "Taxa variacao instantanea."),
        ("Matematica: derivada regra poder", "d/dx x^n = n*x^(n-1)."),
        ("Matematica: derivada produto", "(fg)' = f'g + fg'."),
        ("Matematica: derivada quociente", "(f/g)' = (f'g - fg')/g^2."),
        ("Matematica: derivada cadeia", "f(g(x))' = f'(g(x))*g'(x)."),
        ("Matematica: integral definida", "Area sob curva."),
        ("Matematica: integral indefinida", "Primitiva + C."),
        ("Matematica: teorema fundamental", "Integral a~b f(x)dx = F(b)-F(a)."),
        ("Matematica: area entre curvas", "Integral (f(x)-g(x))dx."),
        ("Matematica: volume revolucao", "pi * Integral f(x)^2 dx."),
        ("Matematica: probabilidade integral", "Integral f(x)dx = 1."),
        ("Matematica: esperanca continua", "E[X] = Integral x*f(x)dx."),
        ("Matematica: variancia continua", "Var = Integral (x-mu)^2*f(x)dx."),
        ("Matematica: funcao gama", "Gamma(n) = (n-1)!."),
        ("Matematica: funcao beta", "B(a,b) = Integral t^(a-1)*(1-t)^(b-1) dt."),
    ]
    RL.extend(rlp_final2)
    print(f"  RLP final2: {len(rlp_final2)} cards")

    # --- Previdencia final 2 (~160 cards) ---
    prev_final2 = [
        ("PREVIC: instrucao normativa", "Interpretacao normas."),
        ("PREVIC: oficio circular", "Orientacoes."),
        ("PREVIC: supervisao direta", "In loco."),
        ("PREVIC: supervisao indireta", "Documentos."),
        ("PREVIC: monitoramento", "Indicadores."),
        ("PREVIC: rating entidades", "Classificacao risco."),
        ("PREVIC: matriz risco", "Classificacao supervisionada."),
        ("PREVIC: plano fiscalizacao", "Anual."),
        ("PREVIC: inspecao presencial", "Agendada ou surpresa."),
        ("PREVIC: nao conformidade", "Notificacao."),
        ("PREVIC: prazo adequacao", "Definido."),
        ("PREVIC: reincidencia", "Agravante."),
        ("PREVIC: processo adm fases", "Instauracao, instrucao, defesa, julgamento."),
        ("PREVIC: indiciamento", "Acusacao formal."),
        ("PREVIC: provas", "Documentais, testemunhais."),
        ("PREVIC: defesa escrita", "Prazo."),
        ("PREVIC: julgamento", "Diretor ou conselho."),
        ("PREVIC: recurso", "Conselho diretor."),
        ("PREVIC: prescricao 5 anos", "Contagem."),
        ("PREVIC: multa pessoa fisica", "Ate R$ 500 mil."),
        ("PREVIC: multa pessoa juridica", "Ate 10% faturamento."),
        ("PREVIC: publicacao sancao", "DOU e site."),
        ("PREVIC: inabilitacao temporaria", "5 anos."),
        ("PREVIC: inabilitacao permanente", "Casos graves."),
        ("PREVIC: intervencao motivos", "Irregularidades graves."),
        ("PREVIC: interventor poderes", "Gestao plena."),
        ("PREVIC: intervencao relatorios", "Periodicos."),
        ("PREVIC: intervencao termino", "Regularizacao ou liquidacao."),
        ("PREVIC: liquidacao extrajudicial", "Extincao entidade."),
        ("Direito prev: principio contributivo", "Beneficio vincula contribuicao."),
        ("Direito prev: principio solidariedade", "Grupo social."),
        ("Direito prev: principio equilibrio", "Financeiro e atuarial."),
        ("Direito prev: principio universalidade", "Cobertura todos."),
        ("Direito prev: principio seletividade", "Prestacoes essenciais."),
        ("Direito prev: principio equidade", "Formas participacao."),
        ("Direito prev: principio diversidade", "Base financiamento."),
        ("Direito prev: RGPS", "Regime geral trabalhadores privados."),
        ("Direito prev: RPPS", "Regime proprio servidores publicos."),
        ("Direito prev: RPC", "Regime complementar facultativo."),
        ("Direito prev: RGPS filiacao", "Obrigatoria empregados."),
        ("Direito prev: RGPS contribuinte individual", "Autonomos."),
        ("Direito prev: RGPS segurado facultativo", "Sem renda."),
        ("Direito prev: RGPS dependentes", "Conjuge, filhos, pais."),
        ("Direito prev: RGPS carencia", "180 meses aposentadoria."),
        ("Direito prev: EC 103/2019", "Reforma previdencia."),
        ("Direito prev: EC 103 idade minima", "65 homem, 62 mulher."),
        ("Direito prev: EC 103 tempo contrib", "20 homem, 15 mulher."),
        ("Direito prev: EC 103 calculo", "60% media + 2% por ano acima."),
        ("Direito prev: EC 103 regra transicao", "Pedagio, pontos, idade."),
        ("Direito prev: EC 103 professores", "Reducao 5 anos."),
        ("Direito prev: EC 103 policiais", "Regras especificas."),
        ("PREVCOM: investimento em FII", "Limite CMN."),
        ("PREVCOM: investimento em FIP", "Limite CMN."),
        ("PREVCOM: investimento exterior", "Limite CMN."),
        ("PREVCOM: derivativos protecao", "Hedge."),
        ("PREVCOM: vedado derivativos alavancados", "Proibido."),
        ("PREVCOM: emprestimos participantes", "Modalidade."),
        ("PREVCOM: emprestimos garantia", "Saldo conta."),
        ("PREVCOM: patrimonio minimo", "Regulamentado."),
        ("PREVCOM: capital minimo", "Regulamentado."),
        ("PREVCOM: provisoes tecnicas", "Atuariais."),
        ("PREVCOM: fundos garantidores", "Garantia."),
        ("PREVCOM: segregação planos", "Cada plano independente."),
        ("PREVCOM: contabilidade separada", "Por plano."),
        ("PREVCOM: demonstracoes consolidadas", "Entidade."),
        ("PREVCOM: notas explicativas", "Detalhamento."),
        ("PREVCOM: politica contabil", "Praticas contabeis."),
        ("PREVCOM: auditoria independente contratacao", "Assembleia."),
        ("PREVCOM: rodizio auditoria", "5 anos."),
        ("PREVCOM: servicos nao auditoria", "Limitados."),
        ("PREVCOM: comite auditoria", "Se aplicavel."),
        ("PREVCOM: gestao riscos estrutura", "Area especifica."),
        ("PREVCOM: riscos seguranca", "Cibernetico."),
        ("PREVCOM: riscos legal", "Normativo."),
        ("PREVCOM: riscos imagem", "Reputacional."),
        ("PREVCOM: riscos operacional", "Processos, pessoas, sistemas."),
        ("PREVCOM: continuidade negocios", "Plano."),
        ("PREVCOM: contingencia TI", "Plano."),
        ("PREVCOM: backup dados", "Rotina."),
        ("PREVCOM: seguranca informacao", "Politica."),
        ("PREVCOM: LGPD adequacao", "DPO, ROPA."),
        ("PREVCOM: privacidade dados", "Participantes."),
        ("PREVCOM: canal denuncia", "Ouvidoria."),
        ("PREVCOM: codigo conduta", "Etica."),
        ("PREVCOM: conflito interesses", "Declaracao."),
        ("PREVCOM: transparencia salarial", "Divulgacao."),
        ("PREVCOM: igualdade genero", "Politica."),
        ("PREVCOM: diversidade", "Quadro."),
        ("PREVCOM: responsabilidade social", "Programas."),
        ("PREVCOM: sustentabilidade", "ESG."),
        ("PREVCOM: relatorio sustentabilidade", "GRI."),
    ]
    PR.extend(prev_final2)
    print(f"  Previdencia final2: {len(prev_final2)} cards")
'''

idx = content.rfind(marker)
if idx != -1:
    new_content = content[:idx + len(marker)] + extra + content[idx + len(marker):]
    with open(path, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"Final expansion 2 inserted. File size: {len(new_content)} chars")
else:
    print('ERROR: marker not found!')
