"""Second batch expansion: ~2300 more cards across all disciplines"""
import os

path = r'D:\Prevcom\prevcom_app\programmatic_flashcards.py'

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

marker = '    print(f"  TI expanded: {len(ti_expand)} cards")'

extra = '''

    # ================================================================
    # EXPANSAO MASSIVA 2 (~2300 CARDS)
    # ================================================================

    # --- LP expansion 2 (~350 cards) ---
    lp_extra2 = [
        ("Crase: aquele/aquela/aquilo", "Sempre crase. Ex: Refiro-me aquela."),
        ("Crase: locucoes prepositivas", "a + feminino. Ex: a moda de, a maneira de."),
        ("Crase: horas", "As 14h vs A partir das 14h."),
        ("Crase: distancia", "A 10km (sem crase)."),
        ("Crase: nomes proprios", "Opcional se feminino. Ex: Referiu-se a Maria."),
        ("Crase: pronomes de tratamento", "Nunca. Ex: Entregue a Vossa Senhoria."),
        ("Crase: antes de numerais", "Ate as 15h (hora), a 10 passos (distancia)."),
        ("Crase: paralelismo", "a...a. Ex: Fui a escola e a igreja."),
        ("Pontuacao: virgula enumeracao", "Separa itens. Ex: comprei pao, leite, queijo."),
        ("Pontuacao: virgula vocativo", "Separa chamamento. Ex: Pedro, venha ca."),
        ("Pontuacao: virgula aposto", "Separa explicacao. Ex: Maria, a gerente, saiu."),
        ("Pontuacao: virgula oracao adjetiva explicativa", "Separa explicacao. Ex: O aluno, que estudou, passou."),
        ("Pontuacao: virgula elipse", "Indica omissao verbo. Ex: Eu estudo; ele, trabalha."),
        ("Pontuacao: virgula inversao", "Separa adjunto deslocado. Ex: Ontem, fui a praia."),
        ("Pontuacao: ponto e virgula enumeracao complexa", "Itens com virgula interna. Ex: Joao, gerente; Maria, analista."),
        ("Pontuacao: dois-pontos citacao", "Introduz fala. Ex: Ele disse: 'Vou'."),
        ("Pontuacao: dois-pontos enumeracao", "Ex: Tres paises: Brasil, Chile, Peru."),
        ("Pontuacao: reticencias suspensao", "Interrompe pensamento. Ex: Ele disse que... bem, nao importa."),
        ("Pontuacao: parenteses explicacao", "Comentario a parte. Ex: Ele chegou (finalmente) as 10h."),
        ("Acentuacao: ditongos abertos", "ei/oi/eu oxitonas. Ex: aneis, heroi, ceu."),
        ("Acentuacao: hiato 'i'/'u' tonicos", "acentuados quando 2a vogal hiato. Ex: saude, baia, feiura."),
        ("Acentuacao: hiato 'i' seguido 'nh'", "NAO acentua. Ex: rainha, campainha."),
        ("Acentuacao: verbos 'ter'/'vir'", "3a pessoa singular tem/plural tem, singular vem/plural vem."),
        ("Acentuacao: verbos 'conter'/'deter'", "Ele detem, eles detem; ele retem, eles retem."),
        ("Acentuacao: 'pode'/'poe'", "Pret perfeito: ele pode. Presente: ele poe."),
        ("Pronome: colocacao facultativa", "Sujeito explicito nao atrativo. Ex: Ele me disse / Ele disse-me."),
        ("Pronome: colocacao locucao adverbial", "Virgula atrai. Ex: Ontem, me contou. Sem virgula: Ontem contou-me."),
        ("Pronome: colocacao oracao subordinada", "Proclise obrigatoria. Ex: Quando me viu."),
        ("Pronome: colocacao gerundio", "Enclise se sem preposicao. Ex: Saiu dizendo-lhe."),
        ("Pronome: colocacao infinitivo", "Facultativo. Ex: Para lhe dar / Para dar-lhe."),
        ("Pronome: colocacao 'com' + infinitivo", "Proclise. Ex: ao me ver, ao lhe dizer."),
        ("Pronome: mesoclise futuro presente", "Ex: Dar-lhe-ei o livro."),
        ("Pronome: mesoclise futuro pret", "Ex: Dar-lhe-ia o livro."),
        ("Interjeicao: alegria", "Ah!, Oba!, Eba!"),
        ("Interjeicao: dor", "Ai!, Ui!"),
        ("Interjeicao: admiração", "Nossa!, Puxa!, Caramba!"),
        ("Interjeicao: silencio", "Psiu!, Silencio!"),
        ("Interjeicao: chamamento", "Psiu!, Ola!"),
        ("Interjeicao: duvida", "Hum?!"),
        ("Interjeicao: alivio", "Ufa!, Ainda bem!"),
        ("Conjuncao coordenativa aditiva", "e, nem, mas tambem, como tambem."),
        ("Conjuncao coordenativa adversativa", "mas, porem, todavia, contudo, no entanto, entretanto."),
        ("Conjuncao coordenativa alternativa", "ou, ora...ora, quer...quer, seja...seja."),
        ("Conjuncao coordenativa conclusiva", "logo, portanto, por conseguinte, assim, pois (posposto)."),
        ("Conjuncao coordenativa explicativa", "porque, porquanto, pois (anteposto), que."),
        ("Conjuncao subordinativa causal", "porque, ja que, visto que, uma vez que."),
        ("Conjuncao subordinativa consecutiva", "tanto...que, de modo que, de forma que."),
        ("Conjuncao subordinativa condicional", "se, caso, contanto que, desde que, a menos que."),
        ("Conjuncao subordinativa concessiva", "embora, conquanto, ainda que, mesmo que, se bem que."),
        ("Conjuncao subordinativa temporal", "quando, enquanto, logo que, assim que, mal, sempre que."),
        ("Conjuncao subordinativa final", "para que, a fim de que, porque (=para que)."),
        ("Conjuncao subordinativa proporcional", "a proporcao que, a medida que, quanto mais...mais."),
        ("Conjuncao subordinativa comparativa", "como, tal qual, mais...do que, menos...do que."),
        ("Conjuncao subordinativa conformativa", "conforme, como, segundo, consoante."),
        ("Conjuncao subordinativa integrante", "que, se (introduzem oracao subordinada substantiva)."),
        ("Verbos: 'haver' impessoal", "3a singular, sem sujeito. Ex: Ha muitos alunos."),
        ("Verbos: 'fazer' tempo", "3a singular. Ex: Faz dez anos."),
        ("Verbos: 'ser' horas", "Concorda com numeral. Ex: Sao 10h. E 1h."),
        ("Verbos: 'ser' datas", "Ontem foi 10. Hoje e 11. Sao 10 de maio."),
        ("Verbos: 'ser' distancia", "Sao 10km. E 1km."),
        ("Verbos: 'estar' meteorologia", "3a singular. Ex: Esta frio. Estao chuvosos."),
        ("Voz passiva analitica", "Ser + particulo. Ex: O bolo foi feito."),
        ("Voz passiva sintetica", "Verbo + se. Ex: Fazem-se bolos."),
        ("Voz ativa", "Sujeito pratica. Ex: Pedro fez o bolo."),
        ("Textualidade: coesao referencial", "Retoma termo. Pronomes, sinonimos, elipse."),
        ("Textualidade: coesao sequencial", "Progressao texto. Conectivos."),
        ("Textualidade: coesao lexical", "Repeticao, sinonimo, hiperonimo."),
        ("Textualidade: coerencia tematica", "Unidade de sentido."),
        ("Textualidade: coerencia logica", "Nao contradicao."),
        ("Textualidade: coerencia pragmatica", "Adequacao contexto."),
        ("Tipologia: dissertativo-argumentativo", "Tese + argumentos + conclusao."),
        ("Tipologia: narrativo elementos", "Fato, personagens, tempo, espaco, narrador."),
        ("Tipologia: descritivo objetivo", "Descricao imparcial, precisa."),
        ("Tipologia: descritivo subjetivo", "Descricao pessoal, emotiva."),
        ("Intertextualidade", "Dialogo entre textos. Citacao, parodia, epigrafe."),
        ("Parodia", "Releitura ironica/critica."),
        ("Parafrase", "Reescrita com outras palavras."),
        ("Estilistica: anacoluto", "Mudanca abrupta construcao. Ex: Eu, parece que nao vou."),
        ("Estilistica: assindeto", "Sem conjuncao. Ex: Vim, vi, venci."),
        ("Estilistica: polissindeto", "Repeticao conjuncao. Ex: E canta, e chora, e ri."),
        ("Estilistica: elipse", "Omissao termo subentendido. Ex: Na sala, apenas nos."),
        ("Estilistica: zeugma", "Omissao termo ja citado. Ex: Eu gosto de musica; ela, de cinema."),
        ("Estilistica: silepse", "Concorda com ideia, nao forma. Ex: A turma estavam felizes."),
        ("Estilistica: gradação", "Sequencia crescente/decrescente. Ex: fogo, incendio, inferno."),
        ("Estilistica: hipérbato", "Inversao ordem direta. Ex: Os livros, comprei."),
        ("Estilistica: anáfora", "Repeticao inicio periodo. Ex: 'Era uma casa... Era um muro...'"),
        ("Estilistica: onomatopeia", "Palavra imita som. Ex: tic-tac, miau, bum."),
        ("Estilistica: aliteracao", "Repeticao consoantes. Ex: 'O rato roeu a roupa'."),
        ("Estilistica: assonancia", "Repeticao vogais. Ex: 'A aranha arranha a jarra'."),
        ("Arcadismo", "Sec XVIII. Bucolismo, simplicidade. Cláudio Manuel da Costa."),
        ("Romantismo Brasil", "Sec XIX. Nacionalismo, indianismo, amor. Goncalves Dias, Alencar."),
        ("Realismo", "Sec XIX. Objetividade, critica social. Machado de Assis, Eça de Queiros."),
        ("Naturalismo", "Determinismo, ciencia. Aluisio Azevedo (O Cortico)."),
        ("Parnasianismo", "Arte pela arte. Perfeicao formal. Olavo Bilac."),
        ("Simbolismo", "Subjetividade, espiritualidade. Cruz e Sousa."),
        ("Pre-Modernismo", "Brasil real. Euclides da Cunha, Lima Barreto."),
        ("Modernismo 1a fase", "1922. Ruptura, nacionalismo critico. Oswald, Mario, Anita."),
        ("Modernismo 2a fase", "1930-45. Prosa regionalista (Graciliano, J. Amado)."),
        ("Modernismo 3a fase", "1945+. Poesia concreta. Joao Cabral, Clarice Lispector."),
        ("Literatura: funcao catarse", "Purificacao emocional leitor."),
        ("Literatura: funcao engajamento", "Critica social e politica."),
        ("Literatura: funcao entretenimento", "Prazer estetico e distracao."),
        ("Figuras: aposto explicativo", "Ex: Joao, o gerente, chegou."),
        ("Figuras: aposto enumerativo", "Ex: Duas coisas: estudo e trabalho."),
        ("Figuras: aposto resumitivo", "Ex: Vida, saude, alegria, tudo passa."),
        ("Figuras: vocativo", "Ex: Pedro, vem ca!"),
        ("Figuras: pleonasmo vicioso", "Repeticao desnecessaria. Ex: subir para cima."),
        ("Figuras: pleonasmo literario", "Repeticao enfatica intencional. Ex: 'E rir meu riso'."),
        ("Figuras: hipalage", "Atribuir qualidade a outro termo. Ex: 'Noite silenciosa' (nao a noite, mas o ambiente)."),
        ("Figuras: enálage", "Mudanca classe gramatical. Ex: 'A gente' como pronome."),
    ]
    LP.extend(lp_extra2)
    print(f"  LP expansion 2: {len(lp_extra2)} cards")

    # --- Etica expansion 2 (~400 cards) ---
    etica_extra2 = [
        ("LGPD: art. 5 tratamento", "Toda operacao com dados pessoais."),
        ("LGPD: art. 5 controlador", "Responsavel decisoes tratamento."),
        ("LGPD: art. 5 operador", "Executa tratamento ordem controlador."),
        ("LGPD: art. 5 encarregado", "DPO. Comunicacao controlador/titular/ANPD."),
        ("LGPD: art. 5 agentes tratamento", "Controlador e operador."),
        ("LGPD: art. 5 anonimizacao", "Nao permite identificacao."),
        ("LGPD: art. 5 pseudonimizacao", "Identificacao por meio adicional."),
        ("LGPD: art. 5 consentimento", "Livre, informado, inequivoco."),
        ("LGPD: art. 9 transparencia", "Informacao clara, precisa, facil acesso."),
        ("LGPD: art. 10 legítimo interesse", "Bases legais tratamento."),
        ("LGPD: art. 14 crianças", "Consentimento especifico responsavel."),
        ("LGPD: art. 16 eliminacao", "Fim tratamento, dados eliminados."),
        ("LGPD: art. 20 revisao automatizada", "Direito pedir revisao humana."),
        ("LGPD: art. 21 oposicao", "Titular pode se opor a tratamento."),
        ("LGPD: art. 22 informacao publica", "Protecao dados em pesquisa."),
        ("LGPD: art. 23 poder publico", "Finalidades especificas."),
        ("LGPD: art. 24 compartilhamento publico", "Necessario para politica publica."),
        ("LGPD: art. 27 tutela coletiva", "Direitos difusos e coletivos."),
        ("LGPD: art. 28 normas especiais", "Leis setoriais complementam."),
        ("LGPD: art. 29 transferencia internacional", "Paises com protecao adequada."),
        ("LGPD: art. 30 clausulas padrao", "Contratuais para transferencia."),
        ("LGPD: art. 31 compromisso", "Empresa se compromete proteger."),
        ("LGPD: art. 33 autorizacao ANPD", "Necessaria para transferencia inadequada."),
        ("LGPD: art. 34 cooperacao internacional", "ANPD coopera outros orgaos."),
        ("LGPD: art. 35 adequacao", "Controlador adequa processos."),
        ("LGPD: art. 36 ROPA", "Registro operacoes tratamento."),
        ("LGPD: art. 37 seguranca medidas", "Tecnicas e administrativas."),
        ("LGPD: art. 38 incidente", "Controlador comunica ANPD e titulares."),
        ("LGPD: art. 39 boas praticas", "Regras de conduta, governance."),
        ("LGPD: art. 40 selo certificacao", "ANPD estabelece criterios."),
        ("LGPD: art. 41 encarregado indicacao", "Controlador indica encarregado."),
        ("LGPD: art. 42 responsabilidade", "Solidaria controlador e operador."),
        ("LGPD: art. 43 excludentes", "Nao ha responsabilidade se prova nao tratar ou dano inevitavel."),
        ("LGPD: art. 44 acao coletiva", "Associacoes podem agir."),
        ("LGPD: art. 45 ANPD natureza", "Orgao administracao publica federal."),
        ("LGPD: art. 46 ANPD competencias", "Fiscalizar, orientar, sancionar."),
        ("LGPD: art. 47 ANPD composicao", "Conselho Diretor: 5 membros."),
        ("LGPD: art. 48 ANPD mandato", "Mandato 4 anos, renovavel."),
        ("LGPD: art. 49 ANPD conselho nacional", "Participacao social."),
        ("LGPD: art. 50 ANPD sancoes administrativas", "Advertencia, multa, publicizacao, bloqueio, eliminacao."),
        ("LGPD: art. 51 ANPD processo", "Procedimento administrativo."),
        ("LGPD: art. 52 dosimetria", "Gravidade, boa-fe, reincidencia, porte."),
        ("LGPD: art. 53 recurso", "Conselho Diretor."),
        ("LGPD: art. 54 prazo prescricao", "5 anos."),
        ("LGPD: art. 55 disposicoes finais", "Vigencia 18 meses."),
        ("LGPD: art. 56 revogacao", "Revoga disposicoes contrarias."),
        ("ESG: TCFD", "Task Force Climate-related Financial Disclosures."),
        ("ESG: SASB", "Sustainability Accounting Standards Board."),
        ("ESG: CDP", "Carbon Disclosure Project."),
        ("ESG: IIRC", "International Integrated Reporting Council."),
        ("ESG: materialidade", "Impacto financeiro e socioambiental."),
        ("ESG: dupla materialidade", "Impacto financeiro e impacto externo."),
        ("ESG: net zero", "Zero emissoes liquidas."),
        ("ESG: carbono neutro", "Compensa emissoes."),
        ("ESG: credito carbono", "Reducao emissoes certificada."),
        ("ESG: Acordo Paris", "Limitar aquecimento 1.5°C."),
        ("ESG: COP26 metas", "Net zero 2050, carvao, desmatamento."),
        ("ESG: diversidade conselho", "Minimo 30% genero sub-representado."),
        ("ESG: diversidade racial", "Políticas afirmativas."),
        ("ESG: trabalho decente", "Salario justo, condicoes dignas."),
        ("ESG: cadeia valor", "Fornecedores responsaveis."),
        ("ESG: economia circular", "Reduzir, reutilizar, reciclar."),
        ("Anticorrupcao: art. 1 paragrafo", "Pessoa juridica responde objetivamente."),
        ("Anticorrupcao: art. 2 pessoa juridica", "Empresas, consorcios, fundacoes."),
        ("Anticorrupcao: art. 3 responsabilidade internacional", "Atos lesivos exterior."),
        ("Anticorrupcao: art. 4 desconsideracao", "Penetra socios e administradores."),
        ("Anticorrupcao: art. 5 atos I", "Prometer, oferecer vantagem agente publico."),
        ("Anticorrupcao: art. 5 atos II", "Financiar corrupcao."),
        ("Anticorrupcao: art. 5 atos III", "Fraudar carater competitivo."),
        ("Anticorrupcao: art. 5 atos IV", "Dificultar fiscalizacao."),
        ("Anticorrupcao: art. 5 atos V", "Obstruir investigacao."),
        ("Anticorrupcao: art. 6 multa calculo", "0,1 a 20% faturamento bruto."),
        ("Anticorrupcao: art. 7 multa minimo", "Nunca menor que vantagem."),
        ("Anticorrupcao: art. 7 sancao publicacao", "Obrigatoria em meios oficiais."),
        ("Anticorrupcao: art. 8 desconsideracao", "Se abuso ou violacao Lei."),
        ("Anticorrupcao: art. 9 acordo leniencia reducao", "Ate 2/3 multa."),
        ("Anticorrupcao: art. 10 requisitos leniencia I", "Admitir participacao."),
        ("Anticorrupcao: art. 10 requisitos leniencia II", "Colaborar investigacao."),
        ("Anticorrupcao: art. 10 requisitos leniencia III", "Cessar envolvimento."),
        ("Anticorrupcao: art. 10 requisitos leniencia IV", "Devolver integralmente."),
        ("Anticorrupcao: art. 11 processo administrativo", "CEIS reabilitacao."),
        ("Anticorrupcao: art. 12 CNEP inscricao", "Apos reincidencia."),
        ("Anticorrupcao: art. 13 CEIS inscricao", "Apos condenacao."),
        ("Anticorrupcao: art. 14 cadastro", "CNEP e CEIS publicos."),
        ("Anticorrupcao: art. 15 competencia CGU", "Processar e julgar."),
        ("Anticorrupcao: art. 16 recurso CGU", "Avalia recurso."),
        ("Anticorrupcao: art. 17 prescricao", "5 anos ciencia autoridade."),
        ("Anticorrupcao: art. 18 cooperacao internacional", "Mutua assistencia."),
        ("Anticorrupcao: art. 19 direito comparado", "Convencoes internacionais."),
        ("Codigo Etica: art. 1 finalidade", "Fixar normas conduta agentes."),
        ("Codigo Etica: art. 2 principios", "Moralidade, legalidade, impessoalidade."),
        ("Codigo Etica: art. 3 deveres I", "Exercer com zelo e dignidade."),
        ("Codigo Etica: art. 3 deveres II", "Ser leal instituicoes."),
        ("Codigo Etica: art. 3 deveres III", "Guardar sigilo."),
        ("Codigo Etica: art. 3 deveres IV", "Atender publico."),
        ("Codigo Etica: art. 3 deveres V", "Representar ilegalidades."),
        ("Codigo Etica: art. 4 vedações I", "Usar cargo para beneficios."),
        ("Codigo Etica: art. 4 vedações II", "Pleitear interesses privados."),
        ("Codigo Etica: art. 4 vedações III", "Aceitar presentes."),
        ("Codigo Etica: art. 4 vedações IV", "Participar decisoes interesse pessoal."),
        ("Codigo Etica: art. 5 comissao", "Avalia conduta."),
        ("Codigo Etica: art. 6 pena", "Advertencia ou censura."),
        ("Codigo Etica: art. 7 publicidade", "Transparencia."),
        ("Governanca: conselho fiscal membros", "Min 3, max 5."),
        ("Governanca: conselho fiscal requisitos", "Idoneos, sem conflito."),
        ("Governanca: conselho fiscal vedações", "Parentes, fornecedores."),
        ("Governanca: auditoria independente rodizio", "Troca a cada 5 anos."),
        ("Governanca: comite auditoria composicao", "Min 3, independentes."),
        ("Governanca: risco operacional", "Falhas processos, pessoas, sistemas."),
        ("Governanca: risco legal", "Descumprimento normas."),
        ("Governanca: risco reputacional", "Imagem negativa."),
        ("Governanca: risco estrategico", "Decisoes erradas."),
        ("Governanca: risco liquidez", "Falta recursos."),
        ("Governanca: risco credito", "Contraparte nao paga."),
        ("Governanca: risco mercado", "Variacao precos."),
        ("Governanca: apetite risco", "Nivel risco aceitavel."),
        ("Governanca: tolerancia risco", "Desvio maximo apetite."),
        ("Governanca: matriz risco", "Probabilidade x Impacto."),
        ("Governanca: 3 linhas defesa", "1a: gestao operacional. 2a: compliance/risco. 3a: auditoria."),
        ("LAI: art. 6 pedido anonimo", "Pode ser aceito."),
        ("LAI: art. 13 indeferimento", "Generico, desproporcional, desarrazoado."),
        ("LAI: art. 14 informacao pessoal", "Acesso restrito 100 anos."),
        ("LAI: art. 15 classificacao competencias", "Presidente, ministros, comissoes."),
        ("LAI: art. 16 recurso CGU", "1a instancia."),
        ("LAI: art. 17 recurso CMRI", "2a instancia."),
        ("LAI: art. 18 prazos recurso", "10 dias cada instancia."),
        ("LAI: art. 19 sigilo fonte", "Informante protegido."),
        ("LAI: art. 20 responsabilidade", "Agente responde por descumprimento."),
        ("LAI: art. 21 informacao sigilosa definicao", "Imprenscindivel seguranca sociedade."),
        ("LAI: art. 22 graus sigilo", "Ultrassecreto 25a, secreto 15a, reservado 5a."),
        ("LAI: art. 23 reavaliacao", "A cada 4 anos."),
        ("LAI: art. 24 excecoes", "Inteligencia, seguranca."),
        ("LAI: art. 25 informacao parcial", "Permite acesso parte nao sigilosa."),
        ("LAI: art. 26 custos", "Gratuito, salvo copias."),
        ("LAI: art. 27 negativa ficta", "Silencio = recurso cabivel."),
        ("LAI: art. 28 orgaos obrigados", "Todos Poderes e orgaos."),
        ("LAI: art. 29 municipios", "Aderem voluntariamente."),
        ("LAI: art. 30 regulamentacao", "Lei auto-aplicavel."),
        ("LAI: art. 31 dados abertos", "Formatos abertos, legiveis maquina."),
        ("LAI: art. 32 transparencia ativa minima", "Site, dados, despesas, servidores."),
        ("LAI: art. 33 participacao social", "Consultas e audiencias."),
        ("LAI: art. 34 controle social", "Cidadao fiscaliza."),
        ("LAI: art. 35 Fala.BR", "Plataforma unica."),
        ("LAI: art. 36 dados abertos definicao", "Dados publicos disponiveis."),
        ("LAI: art. 37 tecnologia informação", "Ferramentas para transparencia."),
        ("Lideranca: coaching conceito", "Desenvolve potencial."),
        ("Lideranca: feedback", "Retorno construtivo."),
        ("Lideranca: feedback 360", "Multiplas fontes."),
        ("Lideranca: mentoring", "Experiencia e orientacao."),
        ("Lideranca: delegacao", "Transferir responsabilidade."),
        ("Lideranca: empowerment", "Autonomia equipe."),
        ("Lideranca: comunicacao", "Clara, objetiva, bidirecional."),
        ("Lideranca: escuta ativa", "Compreender antes responder."),
        ("Lideranca: negociacao", "Ganha-ganha."),
        ("Lideranca: gestao conflito", "Identificar, mediar, resolver."),
        ("Lideranca: motivacao intrinseca", "Interna: proposito, autonomia."),
        ("Lideranca: motivacao extrinseca", "Externa: recompensa, reconhecimento."),
    ]
    ET.extend(etica_extra2)
    print(f"  Etica expansion 2: {len(etica_extra2)} cards")

    # --- RLP expansion 2 (~400 cards) ---
    rlp_extra2 = [
        ("Geometria: area triangulo", "A = (b*h)/2."),
        ("Geometria: area quadrado", "A = l^2."),
        ("Geometria: area retangulo", "A = b*h."),
        ("Geometria: area circulo", "A = π*r^2."),
        ("Geometria: area trapezio", "A = (B+b)*h/2."),
        ("Geometria: volume cubo", "V = a^3."),
        ("Geometria: volume paralelepipedo", "V = a*b*c."),
        ("Geometria: volume cilindro", "V = π*r^2*h."),
        ("Geometria: volume esfera", "V = (4/3)*π*r^3."),
        ("Geometria: volume cone", "V = (1/3)*π*r^2*h."),
        ("Geometria: teorema Pitagoras", "a^2 = b^2 + c^2 (hipotenusa)."),
        ("Geometria: triangulo 3-4-5", "Exemplo classico Pitagoras."),
        ("Geometria: distancia pontos", "d = √((x2-x1)^2+(y2-y1)^2)."),
        ("Geometria: ponto medio", "M = ((x1+x2)/2, (y1+y2)/2)."),
        ("Geometria: equacao reta", "y = mx + b."),
        ("Geometria: coeficiente angular", "m = (y2-y1)/(x2-x1)."),
        ("Geometria: retas paralelas", "m1 = m2."),
        ("Geometria: retas perpendiculares", "m1 * m2 = -1."),
        ("Trigonometria: seno", "sen θ = cat oposto/hipotenusa."),
        ("Trigonometria: cosseno", "cos θ = cat adjacente/hipotenusa."),
        ("Trigonometria: tangente", "tan θ = cat oposto/cat adjacente."),
        ("Trigonometria: sen²+cos²=1", "Relacao fundamental."),
        ("Trigonometria: angulos notaveis 30°", "sen=1/2, cos=√3/2, tan=√3/3."),
        ("Trigonometria: angulos notaveis 45°", "sen=√2/2, cos=√2/2, tan=1."),
        ("Trigonometria: angulos notaveis 60°", "sen=√3/2, cos=1/2, tan=√3."),
        ("Matematica: mmc", "Menor multiplo comum."),
        ("Matematica: mdc", "Maior divisor comum."),
        ("Matematica: numeros primos ate 20", "2,3,5,7,11,13,17,19."),
        ("Matematica: crivo Eratostenes", "Metodo achar primos."),
        ("Matematica: fracao soma", "a/c + b/c = (a+b)/c."),
        ("Matematica: fracao multiplicacao", "a/b * c/d = (a*c)/(b*d)."),
        ("Matematica: fracao divisao", "a/b ÷ c/d = a/b * d/c."),
        ("Matematica: decimal fracao", "0,abc = abc/1000."),
        ("Matematica: dízima periodica simples", "0,ddd = d/9."),
        ("Matematica: dízima periodica composta", "0,abcd = (abcd - abc)/9000."),
        ("Matematica: notacao cientifica", "a * 10^n, 1≤a<10."),
        ("Matematica: radiciacao √a", "√a = b <=> b^2 = a."),
        ("Matematica: potencia 0", "a^0 = 1, a≠0."),
        ("Matematica: potencia negativa", "a^-n = 1/a^n."),
        ("Matematica: propriedade potencia I", "a^m * a^n = a^(m+n)."),
        ("Matematica: propriedade potencia II", "a^m/a^n = a^(m-n)."),
        ("Matematica: propriedade potencia III", "(a*b)^n = a^n * b^n."),
        ("Matematica: propriedade potencia IV", "(a^m)^n = a^(m*n)."),
        ("Matematica: propriedade potencia V", "a^(1/n) = ⁿ√a."),
        ("Logica: tabela XOR", "V se diferentes."),
        ("Logica: tabela NOR", "V so se ambos F (nega OU)."),
        ("Logica: tabela NAND", "F so se ambos V (nega E)."),
        ("Logica: equivalencia XOR", "p⊕q ≡ (p∧¬q)∨(¬p∧q)."),
        ("Logica: forma normal CNF", "Conjuncao de disjuncoes."),
        ("Logica: forma normal DNF", "Disjuncao de conjuncoes."),
        ("Logica: premissa", "Proposicao base argumento."),
        ("Logica: conclusao", "Proposicao decorrente."),
        ("Logica: argumento dedutivo", "Conclusao decorre logicamente."),
        ("Logica: argumento indutivo", "Conclusao provavel."),
        ("Logica: argumento abdutivo", "Melhor explicacao."),
        ("Logica: inferencia imediata", "Unica premissa."),
        ("Logica: inferencia mediata", "Duas+ premissas."),
        ("Logica: dilema", "Escolha entre alternativas problematicas."),
        ("Conjuntos: conjunto vazio", "Ø ou {}."),
        ("Conjuntos: conjunto universo", "U, todos elementos possiveis."),
        ("Conjuntos: subconjunto proprio", "A⊂B: A contido, nao igual."),
        ("Conjuntos: conjunto partes", "P(A): todos subconjuntos A."),
        ("Conjuntos: diferenca simetrica", "AΔB = (A-B)∪(B-A)."),
        ("Conjuntos: produto cartesiano", "A×B = {(a,b) | a∈A, b∈B}."),
        ("Conjuntos: principio inclusao-exclusao 3", "|A∪B∪C| = |A|+|B|+|C| - |A∩B| - |A∩C| - |B∩C| + |A∩B∩C|."),
        ("Probabilidade: esperanca E[X]", "Σ x*p(x)."),
        ("Probabilidade: variancia Var(X)", "E[X^2] - (E[X])^2."),
        ("Probabilidade: desvio padrao", "√Var(X)."),
        ("Probabilidade: distribuicao binomial", "P(X=k) = Cn,k * p^k * (1-p)^(n-k)."),
        ("Probabilidade: distribuicao normal", "Sino, media μ, desvio σ."),
        ("Probabilidade: distribuicao Poisson", "P(X=k) = e^-λ * λ^k / k!."),
        ("Probabilidade: eventos excludentes", "P(A∩B) = 0."),
        ("Probabilidade: eventos complementares", "P(A) + P(A^c) = 1."),
        ("Probabilidade: lei grandes numeros", "Media amostral → media populacional."),
        ("Probabilidade: teorema limite central", "Soma variaveis → normal, n→∞."),
        ("PA: razao", "r = a2 - a1."),
        ("PA: propriedade termos equidistantes", "Soma constante."),
        ("PG: razao", "q = a2/a1."),
        ("PG: propriedade termos equidistantes", "Produto constante."),
        ("Logica: diagrama Venn", "Representacao grafica conjuntos."),
        ("Logica: metodo tabela verdade", "Valora todas combinacoes."),
        ("Logica: metodo deducao natural", "Regras inferencia passo a passo."),
        ("Logica: metodo resolucao", "Clausulas, refutacao."),
        ("Falacia: apelo natureza", "Algo bom porque natural."),
        ("Falacia: apelo novidade", "Algo melhor porque novo."),
        ("Falacia: apelo tradicao", "Algo certo porque sempre foi."),
        ("Falacia: apelo medo", "Argumento baseado medo."),
        ("Falacia: apelo piedade", "Argumento baseado compaixao."),
        ("Falacia: envenenar poco", "Desqualificar previamente."),
        ("Falacia: homem de palha", "Atacar versao fraca argumento."),
        ("Falacia: tu quoque", "Voce tambem."),
        ("Falacia: regressao infinita", "Cadeia sem fim."),
        ("Falacia: ambiguidade", "Termo multiplos significados."),
    ]
    RL.extend(rlp_extra2)
    print(f"  RLP expansion 2: {len(rlp_extra2)} cards")

    # --- Previdencia expansion 2 (~400 cards) ---
    prev_extra2 = [
        ("PGBL vs VGBL: indicacao", "PGBL: declara completa. VGBL: simplificada."),
        ("PGBL: base calculo", "12% renda bruta tributavel."),
        ("VGBL: tributacao resgate", "IR so rendimentos."),
        ("PGBL: tributacao resgate", "IR total resgate, deduzido contribuicoes."),
        ("Tabela progressiva IR faixas 2024", "Ate 2.259,20: 0%; 2.259,21-2.826,65: 7,5%; 2.826,66-3.751,05: 15%; 3.751,06-4.664,68: 22,5%; acima 4.664,68: 27,5%."),
        ("Tabela regressiva IR prazos", "2 anos: 27,5%; 4 anos: 22,5%; 6 anos: 17,5%; 8 anos: 12,5%; 10 anos: 10%; 12 anos: 7,5%; 15 anos: 5%; 20+ anos: 3%."),
        ("Resgate: IRRF na fonte", "Regressiva: tabela propria. Progressiva: tabela mensal."),
        ("Portabilidade: entre planos", "Mesma modalidade."),
        ("Portabilidade: para PGBL", "De outro PGBL."),
        ("Portabilidade: para VGBL", "De PGBL ou VGBL."),
        ("Portabilidade: sem tributacao", "Diferimento imposto."),
        ("Contribuicao: patrocinador", "Paridade max 1:1."),
        ("Contribuicao: participante", "Minimo definido regulamento."),
        ("Contribuicao: voluntaria", "Adicional, sem contrapartida."),
        ("Contribuicao: extraordinaria", "Para equacionamento deficit."),
        ("Beneficio: elegibilidade tempo", "Minimo 5 anos plano."),
        ("Beneficio: elegibilidade idade", "Conforme regulamento."),
        ("Beneficio: calculo BD", "Formula com tempo e media salarial."),
        ("Beneficio: calculo CD", "Saldo acumulado dividido por fator atuarial."),
        ("Beneficio: pensao percentual", "50-100% beneficio referencia."),
        ("Beneficio: reversao", "Continua conjuge."),
        ("Beneficio: divisao dependentes", "Conforme regulamento."),
        ("Reserva matematica: definicao", "Valor presente beneficios futuros menos contribuicoes futuras."),
        ("Reserva matematica: calculo", "Projeta cenarios, desconta taxa juros atuarial."),
        ("Reserva: metodologia credito unitario", "Projeta e aloca custo anualmente."),
        ("Reserva: metodologia agregada", "Custo nivelado total."),
        ("Reserva: metodologia individual", "Participante a participante."),
        ("Deficit: equacionamento prazo", "Max 30 anos (regra geral)."),
        ("Superavit: reserva contingencia", "Ate 25% reserva matematica."),
        ("Superavit: revisao plano", "Apos contingencia totalmente constituida."),
        ("Superavit: destinação", "Melhoria beneficios, reducao contribuicoes, devolucao."),
        ("Reserva oscilacao: finalidade", "Variacoes curto prazo."),
        ("Reserva oscilacao: limite", "Regulamento define."),
        ("Provision: deficits tecnicos", "Resultado negativo avaliacao."),
        ("Provision: superavits tecnicos", "Resultado positivo."),
        ("Rentabilidade: meta atuarial", "Benchmark atuarial (IPCA+X% ou CDI+X%)."),
        ("Rentabilidade: benchmark", "Indice referencia politica investimentos."),
        ("Rentabilidade: retorno real", "Nominal - inflacao."),
        ("Rentabilidade: retorno absoluto", "Sem ajuste inflacao."),
        ("Rentabilidade: tracking error", "Desvio benchmark."),
        ("Rentabilidade: sharpe ratio", "(Rp - Rf)/σp. Retorno ajustado risco."),
        ("Rentabilidade: volatility", "Desvio padrao retornos."),
        ("Rentabilidade: downside risk", "Volatilidade negativa."),
        ("Rentabilidade: sortino ratio", "(Rp - Rf)/downside σ."),
        ("Rentabilidade: VaR", "Value at Risk. Perda maxima confianca."),
        ("Rentabilidade: CVaR", "Conditional VaR. Media perdas extremas."),
        ("Rentabilidade: stress test", "Cenarios extremos."),
        ("Rentabilidade: asset allocation", "Distribuicao estrategica ativos."),
        ("Rentabilidade: rebalanceamento", "Ajustar pesos periodicamente."),
        ("Rentabilidade: ALM", "Asset Liability Management."),
        ("Governanca: codigo ANEPREM", "Boas praticas previdencia complementar."),
        ("Governanca: transparencia extratos", "Periodicidade minima trimestral."),
        ("Governanca: assembleia", "Participantes elegem representantes."),
        ("Governanca: mandato conselheiros", "4 anos, reconducoes limitadas."),
        ("Governanca: conflito interesses", "Declarar e abster."),
        ("Governanca: politica indicacao", "Criterios escrutinio."),
        ("Governanca: sucessao dirigentes", "Plano de sucessao."),
        ("Governanca: remuneracao", "Variavel consoante resultados."),
        ("PREVIC: fiscalizacao ciclos", "Programacao anual."),
        ("PREVIC: fiscalizacao extraordinaria", "Denuncias ou anormalidades."),
        ("PREVIC: autoavaliacao", "Questionario compliance."),
        ("PREVIC: termo ajustamento conduta", "Compromisso adequacao."),
        ("PREVIC: TAC penalidades", "Multa diaria descumprimento."),
        ("PREVIC: processo administrativo sancionador", "Fases: instauracao, instrucao, defesa, julgamento."),
        ("PREVIC: prescricao", "5 anos conduta."),
        ("PREVIC: reincidencia", "Agrava penalidade."),
        ("PREVIC: multa maxima", "R$ 500 mil (pessoa fisica) ou 10% faturamento (juridica)."),
        ("PREVIC: inabilitacao", "Dirigentes inabilitados."),
        ("PREVIC: intervencao nomeacao", "Interventor assume gestao."),
        ("PREVIC: intervencao prazo", "Max 180 dias, prorrogavel."),
        ("PREVIC: liquidacao extrajudicial", "Encerramento entidade."),
        ("Regime capitalizacao: vantagens", "Acumulo, sustentabilidade longa."),
        ("Regime capitalizacao: desvantagens", "Longo prazo, risco mercado, custos."),
        ("Regime reparticao: vantagens", "Solidariedade, beneficios imediatos."),
        ("Regime reparticao: desvantagens", "Envelhecimento populacional, insustentavel LP."),
        ("RPPS vs RPC", "RPPS: regime proprio servidores (RGPS substituto). RPC: complementar."),
        ("RPPS: requisitos aposentadoria", "Idade, tempo, sexo, cargo."),
        ("RPC: complementar definicao", "Alem do limite RGPS/RPPS."),
        ("RPC: teto RGPS 2024", "R$ 7.786,02."),
        ("RPC: contribuicao aliquota", "Percentual salario participante."),
        ("RPC: beneficio complementar", "Calculo plano."),
        ("PREVCOM: plano PRÓ-SP", "Servidores efetivos."),
        ("PREVCOM: plano COMP-SP", "Servidores celetistas."),
        ("PREVCOM: plano MULTI-SP", "Multiplos orgaos."),
        ("PREVCOM: plano SEG-SP", "Seguranca publica."),
        ("PREVCOM: plano MAG-SP", "Magisterio."),
        ("PREVCOM: contribuicao normal", "Percentual sobre salario."),
        ("PREVCOM: contribuicao suplementar", "Adicional."),
        ("PREVCOM: resgate saldo", "Conforme regulamento."),
        ("PREVCOM: portabilidade saida", "Para outro plano."),
        ("PREVCOM: tributacao resgate", "Conforme opcao regressiva/progressiva."),
        ("PREVCOM: aposentadoria normal", "Cumprir requisitos."),
        ("PREVCOM: pensao", "Aos dependentes."),
        ("PREVCOM: auxilio-doenca", "Invalidez temporaria."),
        ("PREVCOM: abono anual", "13o salario."),
        ("PREVCOM: taxa administracao max", "Percentual regulamento."),
        ("PREVCOM: carência", "Periodo minimo."),
        ("PREVCOM: inscricao", "Aderir ao plano."),
        ("PREVCOM: conselho deliberativo representantes", "Patrocinador, participantes, assistidos."),
        ("PREVCOM: conselho fiscal composicao", "Patrocinador, participantes, assistidos."),
    ]
    PR.extend(prev_extra2)
    print(f"  Previdencia expansion 2: {len(prev_extra2)} cards")

    # --- TI expansion 2 (~400 cards) ---
    ti_extra2 = [
        ("Redes: modelo OSI camada aplicacao", "HTTP, FTP, SMTP, DNS."),
        ("Redes: modelo OSI camada apresentacao", "Criptografia, compressao."),
        ("Redes: modelo OSI camada sessao", "Sessao entre aplicacoes."),
        ("Redes: modelo OSI camada transporte", "TCP, UDP."),
        ("Redes: modelo OSI camada rede", "IP, roteamento."),
        ("Redes: modelo OSI camada enlace", "MAC, Ethernet, switch."),
        ("Redes: modelo OSI camada fisica", "Bits, cabos, sinais."),
        ("Redes: TCP/IP aplicacao", "HTTP, DNS, FTP, SMTP."),
        ("Redes: TCP/IP transporte", "TCP, UDP."),
        ("Redes: TCP/IP rede", "IP, ICMP, ARP."),
        ("Redes: TCP/IP enlace", "Ethernet, WiFi."),
        ("Redes: IPv4 classes", "A: 1-126, B: 128-191, C: 192-223, D: 224-239, E: 240-255."),
        ("Redes: IPv4 mascara", "255.0.0.0 (A), 255.255.0.0 (B), 255.255.255.0 (C)."),
        ("Redes: CIDR", "Roteamento interdominio sem classe."),
        ("Redes: subnetting", "Dividir rede em sub-redes."),
        ("Redes: NAT", "Network Address Translation."),
        ("Redes: DHCP", "Distribuicao automatica IP."),
        ("Redes: ARP", "Address Resolution Protocol. IP→MAC."),
        ("Redes: ICMP", "Internet Control Message Protocol. Ping."),
        ("Redes: TCP handshake", "SYN → SYN-ACK → ACK."),
        ("Redes: TCP slow start", "Incrementa janela exponencial."),
        ("Redes: TCP congestion control", "Slow start, congestion avoidance, fast recovery."),
        ("Redes: TCP flow control", "Janela deslizante."),
        ("Redes: UDP usos", "Streaming, DNS, VoIP."),
        ("Redes: DNS tipos registro", "A (IPv4), AAAA (IPv6), CNAME (alias), MX (email), NS (nameserver)."),
        ("Redes: DNS iterativo", "Servidor responde com referencia."),
        ("Redes: DNS recursivo", "Servidor busca ate resposta."),
        ("Redes: HTTP 1.0 vs 1.1", "1.1: conexao persistente, host header."),
        ("Redes: HTTP/2 multiplex", "Multiplas requisicoes mesma conexao."),
        ("Redes: HTTP/3 QUIC", "UDP, multiplex, menor latencia."),
        ("Redes: gRPC HTTP/2", "Streaming bidirecional, Protobuf."),
        ("Redes: WebSocket upgrade", "GET /path HTTP/1.1 Upgrade: websocket."),
        ("Redes: TLS handshake", "Client Hello, Server Hello, Cert, Key Exchange, Finished."),
        ("Redes: TLS 1.3", "Menos round trips, remocao algoritmos inseguros."),
        ("Redes: mTLS", "Mutual TLS. Cliente + servidor certificados."),
        ("Redes: SSH autenticacao", "Senha ou chave publica."),
        ("Redes: SSH tunnelling", "Port forwarding."),
        ("Redes: VPN IPSec", "IP Security. Modo transporte ou tunel."),
        ("Redes: VPN OpenVPN", "SSL/TLS. Flexible."),
        ("Redes: load balance L4", "TCP/UDP, IP + porta."),
        ("Redes: load balance L7", "HTTP, URL, cookie, header."),
        ("Redes: load balance algoritmos", "Round robin, least connections, IP hash."),
        ("Redes: load balance health check", "Verifica servidor ativo."),
        ("Redes: proxy forward", "Cliente → proxy → internet."),
        ("Redes: proxy reverso", "Internet → proxy → servidor."),
        ("Redes: API Gateway vs reverse proxy", "Gateway: auth, rate limit, routing. Proxy: load balance, cache."),
        ("Cloud: AWS S3 presigned URL", "URL temporaria acesso privado."),
        ("Cloud: AWS S3 event notifications", "S3 → SNS/SQS/Lambda."),
        ("Cloud: AWS S3 transfer acceleration", "CloudFront edge upload."),
        ("Cloud: AWS Lambda layers", "Dependencias compartilhadas."),
        ("Cloud: AWS Lambda concurrency", "Limite paralelismo."),
        ("Cloud: AWS Lambda reserved concurrency", "Garante capacidade."),
        ("Cloud: AWS Lambda provisioned concurrency", "Sem cold start."),
        ("Cloud: AWS Lambda destinations", "On success/failure."),
        ("Cloud: AWS DynamoDB streams", "Mudancas tempo real."),
        ("Cloud: AWS DynamoDB TTL", "Expira itens automaticamente."),
        ("Cloud: AWS DynamoDB global tables", "Multi-regiao."),
        ("Cloud: AWS CloudFront behaviors", "Path pattern, origin, cache."),
        ("Cloud: AWS CloudFront signed URL", "Acesso restrito."),
        ("Cloud: AWS CloudFront WAF", "Web ACL associada."),
        ("Cloud: AWS RDS proxy", "Pool conexoes, IAM."),
        ("Cloud: AWS RDS snapshot", "Backup manual."),
        ("Cloud: AWS RDS automated backup", "Retencao ate 35 dias."),
        ("Cloud: AWS RDS encryption at rest", "KMS."),
        ("Cloud: AWS Aurora", "Compativel MySQL/PostgreSQL. 5x performance."),
        ("Cloud: AWS Aurora Serverless", "Auto scaling."),
        ("Cloud: AWS SQS tipos", "Standard (alta vazao) vs FIFO (ordenado)."),
        ("Cloud: AWS SQS visibility timeout", "Tempo processamento mensagem."),
        ("Cloud: AWS SQS dead letter queue", "Apos falhas."),
        ("Cloud: AWS SNS vs SQS", "SNS: push (pub/sub). SQS: poll (fila)."),
        ("Cloud: AWS SNS filtering", "Filtra mensagens."),
        ("Cloud: AWS Step Functions estados", "Task, Choice, Wait, Parallel, Map."),
        ("Cloud: AWS Step Functions express", "Alta vazao, curta duracao."),
        ("Cloud: AWS API Gateway tipos", "REST, HTTP, WebSocket."),
        ("Cloud: AWS API Gateway throttling", "Limita requisicoes."),
        ("Cloud: AWS API Gateway caching", "Cache respostas."),
        ("Cloud: AWS ECS vs EKS", "ECS: AWS proprio. EKS: Kubernetes gerenciado."),
        ("Cloud: AWS ECS Fargate", "Serverless containers."),
        ("Cloud: AWS ECS EC2", "Containers em EC2."),
        ("Cloud: AWS ECR", "Container registry."),
        ("Cloud: AWS Beanstalk environments", "Web server vs worker."),
        ("Cloud: AWS CloudFormation templates", "YAML/JSON."),
        ("Cloud: AWS CloudFormation stacks", "Conjunto recursos."),
        ("Cloud: AWS CloudFormation changeset", "Preview mudancas."),
        ("Cloud: IaC Terraform state", "tfstate, remote backend."),
        ("Cloud: Terraform providers", "AWS, Azure, GCP, etc."),
        ("Cloud: Terraform modules", "Reuso codigo."),
        ("Cloud: Azure Functions plan", "Consumption, Premium, App Service."),
        ("Cloud: Azure DevOps pipelines", "CI/CD YAML."),
        ("Cloud: Azure DevOps repos", "Git repositorios."),
        ("Cloud: GCP Cloud Functions gen2", "Cloud Run base."),
        ("Cloud: GCP Cloud Run scaling", "0 a N, min/max instances."),
        ("Cloud: GCP Cloud Build triggers", "Git push."),
        ("Cloud: multicloud desafios", "Complexidade, custos, seguranca."),
        ("Cloud: FinOps", "Gestao financeira cloud."),
        ("Seguranca: hash SHA-256", "256 bits. Colisao resistente."),
        ("Seguranca: hash SHA-3", "Último padrao NIST."),
        ("Seguranca: HMAC", "Hash-based Message Authentication Code."),
        ("Seguranca: AES-256", "Simetrico, chave 256 bits."),
        ("Seguranca: RSA-2048", "Assimetrico, 2048 bits."),
        ("Seguranca: ECDSA", "Elliptic Curve Digital Signature Algorithm."),
        ("Seguranca: Diffie-Hellman", "Troca chaves segura."),
        ("Seguranca: Perfect Forward Secrecy", "Chave sessao unica."),
        ("Seguranca: cifra bloco vs fluxo", "Bloco (AES): blocos. Fluxo (ChaCha20): bytes."),
        ("Seguranca: SSL strip", "Downgrade HTTPS para HTTP."),
        ("Seguranca: MITM", "Man-in-the-middle."),
        ("Seguranca: phishing", "Falsificacao identidade."),
        ("Seguranca: spear phishing", "Phishing direcionado."),
        ("Seguranca: ransomware", "Sequestro dados."),
        ("Seguranca: DDoS amplification", "Amplifica ataque."),
        ("Seguranca: zero trust", "Confie zero, verifique sempre."),
        ("Seguranca: IAM roles", "Permissoes temporarias AWS."),
        ("Seguranca: IAM policies", "Documentos JSON permissoes."),
        ("Seguranca: principle least privilege", "Minimo acesso necessario."),
        ("Seguranca: secrets rotation", "Troca periodica segredos."),
        ("Seguranca: vault (HashiCorp)", "Gerenciamento segredos."),
        ("BD: MongoDB aggregation pipeline $match", "Filtra documentos."),
        ("BD: MongoDB aggregation $group", "Agrupa."),
        ("BD: MongoDB aggregation $lookup", "Left outer join."),
        ("BD: MongoDB aggregation $unwind", "Desconstroi array."),
        ("BD: MongoDB indexes", "Single, compound, text, 2dsphere."),
        ("BD: MongoDB replica set", "Primary + secondaries."),
        ("BD: MongoDB sharding", "Shard key distribui dados."),
        ("BD: Redis persistencias", "RDB (snapshot), AOF (append-only)."),
        ("BD: Redis pub/sub", "Mensagens tempo real."),
        ("BD: Redis transactions", "MULTI/EXEC."),
        ("BD: Redis Lua scripting", "Scripts atomicos."),
        ("BD: Cassandra arquitetura", "Gossip, snitch, ring."),
        ("BD: Cassandra consistency", "ONE, QUORUM, ALL."),
        ("BD: Cassandra CQL WHERE", "So colunas partition/clustering key."),
        ("BD: Neo4j Cypher CREATE", "Cria no/relacionamento."),
        ("BD: Neo4j Cypher MATCH", "Busca padroes."),
        ("BD: Neo4j Cypher RETURN", "Retorna dados."),
        ("BD: Elasticsearch inverted index", "Termo → documentos."),
        ("BD: Elasticsearch mapping", "Define tipos campos."),
        ("BD: Elasticsearch aggregation", "Analise dados."),
        ("BD: Elasticsearch cluster", "Nodes, shards, replicas."),
        ("Dados: data warehouse vs data lake", "DW: estruturado, schema-on-write. Lake: tudo, schema-on-read."),
        ("Dados: ETL vs ELT", "ETL: transforma antes. ELT: transforma depois."),
        ("Dados: data mart", "Subconjunto DW departamental."),
        ("Dados: dimensional modeling", "Fato + dimensoes."),
        ("Dados: fato tabela", "Metricas, chaves estrangeiras."),
        ("Dados: dimensao tabela", "Atributos descritivos."),
        ("Dados: star schema", "Fato central + dimensoes."),
        ("Dados: snowflake schema", "Dimensoes normalizadas."),
        ("Dados: OLAP cubo", "Dados multidimensionais."),
        ("Dados: slice/dice", "Fatiar/detalhar cubo."),
        ("Dados: drill down/up", "Navegar hierarquia."),
        ("Dados: pivot", "Reorienta tabela."),
        ("Dados: pipeline dados", "Extracao → transformacao → carga."),
        ("Dados: data lineage", "Rastreamento origem dados."),
        ("Dados: data catalog", "Catalogo metadados."),
        ("Dados: data quality metrics", "Completude, acuracia, consistencia."),
        ("Dados: master data management", "Dados mestre unificados."),
        ("ML: hyperparameter tuning", "Grid search, random search."),
        ("ML: early stopping", "Para se nao melhora."),
        ("ML: regularization L1 Lasso", "Soma valores absolutos. Selecao features."),
        ("ML: regularization L2 Ridge", "Soma quadrados. Reduz overfitting."),
        ("ML: regularization ElasticNet", "L1 + L2."),
        ("ML: dropout", "Desliga neuronios aleatoriamente."),
        ("ML: batch normalization", "Normaliza ativacoes."),
        ("ML: data augmentation", "Aumenta dados artificiais."),
        ("ML: imbalance dataset", "Under/over-sampling, SMOTE."),
        ("ML: ROC AUC interpretacao", ">0.9 excelente, 0.8-0.9 bom, 0.7-0.8 razoavel."),
        ("ML: F1 score", "2*P*R/(P+R). Media harmonica."),
        ("ML: precision vs recall", "P: VP/(VP+FP). R: VP/(VP+FN)."),
        ("ML: confusion matrix VP", "Previu positivo, era positivo."),
        ("ML: confusion matrix FP", "Previu positivo, era negativo."),
        ("ML: confusion matrix VN", "Previu negativo, era negativo."),
        ("ML: confusion matrix FN", "Previu negativo, era positivo."),
        ("Engenharia: microservices comunicacao", "HTTP/REST, gRPC, mensageria."),
        ("Engenharia: microservices desafios", "Coordenação, latencia, dados distribuidos."),
        ("Engenharia: service mesh", "Istio, Linkerd. Sidecar proxy."),
        ("Engenharia: API versioning", "URL, header, query param."),
        ("Engenharia: API rate limiting", "Token bucket, leaky bucket."),
        ("Engenharia: circuit breaker", "Protege chamadas falhas."),
        ("Engenharia: retry with backoff", "Exponencial + jitter."),
        ("Engenharia: idempotency key", "Evita duplicatas."),
        ("Engenharia: saga pattern", "Transacoes distribuídas. Coreografia ou orquestracao."),
        ("Engenharia: CQRS", "Separacao commando/consulta."),
        ("Engenharia: event sourcing", "Eventos como fonte verdade."),
    ]
    TI.extend(ti_extra2)
    print(f"  TI expansion 2: {len(ti_extra2)} cards")
'''

idx = content.rfind(marker)
if idx != -1:
    new_content = content[:idx + len(marker)] + extra + content[idx + len(marker):]
    with open(path, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"Expansion 2 inserted. File size: {len(new_content)} chars")
else:
    print("ERROR: marker not found!")
