"""Expands programmatic_flashcards.py with ~3000 more cards"""
import os

path = r'D:\Prevcom\prevcom_app\programmatic_flashcards.py'

# Read current file
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

# Find the insertion point: before the final print summary and return
insert_marker = "    print(f\"  Tecnologia programatico: {len(TI)} cards\")"

extra_content = '''

    # ================================================================
    # EXPANSAO MASSIVA (~3000 CARDS ADICIONAIS)
    # ================================================================

    # --- LP expansion (~500 cards) ---
    LP_subjuntivo = [
        ("Presente subjuntivo 1a conj", "e/e/es/e/emos/eis/em. Ex: que eu cante."),
        ("Presente subjuntivo 2a conj", "a/a/as/a/amos/ais/am. Ex: que eu venda."),
        ("Presente subjuntivo 3a conj", "a/a/as/a/amos/ais/am. Ex: que eu parta."),
        ("Imperfeito subjuntivo 1a conj", "asse/asses/asse/assemos/asseis/assem."),
        ("Imperfeito subjuntivo 2a conj", "esse/esses/esse/essemos/esseis/essem."),
        ("Imperfeito subjuntivo 3a conj", "isse/isses/isse/issemos/isseis/issem."),
        ("Futuro subjuntivo 1a conj", "ar/ares/ar/armos/ardes/arem."),
        ("Futuro subjuntivo 2a conj", "er/eres/er/ermos/erdes/erem."),
        ("Futuro subjuntivo 3a conj", "ir/ires/ir/irmos/irdes/irem."),
        ("Imperativo afirmativo 1a conj", "canta (tu), cante (voce), cantemos, cantai (vos), cantem (voces)."),
        ("Imperativo negativo 1a conj", "nao cantes, nao cante, nao cantemos, nao canteis, nao cantem."),
        ("Infinitivo pessoal 1a conj", "cantar/cantares/cantar/cantarmos/cantardes/cantarem."),
        ("Gerundio composto", "tendo/havendo + particulo. Ex: tendo cantado."),
        ("Participio regular/irregular", "Regular: -ado/-ido. Irreg: aceito, eleito, entregue, gasto, pago, preso."),
        ("Verbos abundantes", "Dois participios: aceitado/aceito, entregado/entregue, gastado/gasto."),
        ("Voz reflexiva", "Sujeito age e recebe. Ex: Pedro cortou-se."),
        ("Voz reflexiva reciproca", "Acao mutua. Ex: Os noivos beijaram-se."),
        ("Predicado verbal", "Nucleo verbo significativo. Ex: Pedro comprou um carro."),
        ("Predicado nominal", "Nucleo + predicativo. Ex: Pedro e feliz."),
        ("Predicado verbo-nominal", "Dois nucleos. Ex: Pedro comprou um carro feliz."),
        ("Vocativo", "Termo independente. Chamamento. Ex: Pedro, venha ca!"),
        ("Aposto", "Explica/resume termo anterior. Ex: Maria, a gerente, chegou."),
        ("Adjunto adnominal", "Acompanha substantivo. Art, adj, loc, num."),
        ("Adjunto adverbial", "Circunstancia. Ex: Chegou cedo."),
        ("Complemento nominal", "Paciente de nome/adj/adv. Ex: medo de altura."),
        ("Agente da passiva", "Quem pratica na voz passiva. Ex: feito por Pedro."),
        ("Oracao coordenada sindetica aditiva", "e, nem, mas tambem."),
        ("Oracao coordenada sindetica adversativa", "mas, porem, todavia, contudo, no entanto."),
        ("Oracao coordenada sindetica alternativa", "ou, ora...ora, quer...quer."),
        ("Oracao coordenada sindetica conclusiva", "logo, portanto, por isso, assim."),
        ("Oracao coordenada sindetica explicativa", "porque, pois, que."),
        ("Oracao subordinada substantiva subjetiva", "Funcao de sujeito. Ex: E importante que voce estude."),
        ("Oracao subordinada substantiva objetiva direta", "Funcao OD. Ex: Quero que voce estude."),
        ("Oracao subordinada substantiva objetiva indireta", "Funcao OI. Ex: Lembro-me de que estudei."),
        ("Oracao subordinada substantiva completiva nominal", "Funcao CN. Ex: Tenho medo de que chova."),
        ("Oracao subordinada substantiva predicativa", "Funcao predicativo. Ex: Meu desejo e que voce passe."),
        ("Oracao subordinada substantiva apositiva", "Funcao aposto. Ex: So quero isso: que voce estude."),
        ("Oracao subordinada adjetiva restritiva", "Sem virgula. Restringe. Ex: Alunos que estudam passam."),
        ("Oracao subordinada adjetiva explicativa", "Com virgula. Explica. Ex: Alunos, que estudam, passam."),
        ("Oracao subordinada adverbial causal", "porque, ja que, visto que."),
        ("Oracao subordinada adverbial consecutiva", "tanto que, de modo que, de sorte que."),
        ("Oracao subordinada adverbial condicional", "se, caso, contanto que, a menos que."),
        ("Oracao subordinada adverbial concessiva", "embora, ainda que, mesmo que, apesar de."),
        ("Oracao subordinada adverbial temporal", "quando, enquanto, logo que, assim que."),
        ("Oracao subordinada adverbial final", "para que, a fim de que."),
        ("Oracao subordinada adverbial proporcional", "a proporcao que, a medida que."),
        ("Oracao subordinada adverbial comparativa", "como, tal qual, mais que, menos que."),
        ("Oracao subordinada adverbial conformativa", "conforme, como, segundo."),
        ("Regencia verbal: assistir (sentido ver)", "Exige a. Ex: Assisti ao filme."),
        ("Regencia verbal: assistir (ajudar)", "Sem preposicao. Ex: Assistir o necessitado."),
        ("Regencia verbal: aspirar (desejar)", "Exige a. Ex: Aspiro ao cargo."),
        ("Regencia verbal: aspirar (inalar)", "Sem preposicao. Ex: Aspirar o ar."),
        ("Regencia verbal: visar (mirar)", "Sem preposicao. Ex: Visar o alvo."),
        ("Regencia verbal: visar (objetivar)", "Exige a. Ex: Viso ao sucesso."),
        ("Regencia verbal: pagar", "Paga-se algo (OD) a alguem (OI). Ex: Pagar o boleto ao credor."),
        ("Regencia verbal: perdoar", "Perdoa-se alguem (OD) a alguem (OI). Ex: Perdoar o erro ao amigo."),
        ("Regencia nominal: acostumado a/com", "Ex: acostumado ao frio."),
        ("Regencia nominal: apto a/para", "Ex: apto ao trabalho."),
        ("Regencia nominal: capaz de", "Ex: capaz de vencer."),
        ("Regencia nominal: contrario a", "Ex: contrario a lei."),
        ("Concordancia verbal: sujeito composto antes", "Verbo plural. Ex: Pedro e Paulo chegaram."),
        ("Concordancia verbal: sujeito composto depois", "Verbo concorda com mais proximo ou plural. Ex: Chegou Pedro e Paulo."),
        ("Concordancia verbal: percentual", "Verbo concorda com numero ou especificacao. Ex: 10% dos alunos faltaram."),
        ("Concordancia verbal: 'mais de'", "Singular. Ex: Mais de um aluno faltou."),
        ("Concordancia verbal: 'um dos que'", "Plural ou singular. Ex: Um dos que chegaram/chegou."),
        ("Concordancia verbal: pronome 'que'", "Verbo concorda com antecedente. Ex: Fui eu que fiz."),
        ("Concordancia verbal: 'se' indice indeterminacao", "Verbo singular VTI/VI. Ex: Precisa-se de funcionarios."),
        ("Concordancia verbal: 'se' apassivador", "Verbo concorda com sujeito. Ex: Vendem-se casas."),
        ("Concordancia nominal: adjetivo varios substantivos", "Concorda com o mais proximo ou vai plural. Ex: Camisa e sapato novo/novos."),
        ("Concordancia nominal: 'mesmo/proprio'", "Variavel. Ex: Elas mesmas fizeram."),
        ("Concordancia nominal: 'anexo/obrigado'", "Concorda. Ex: Seguem anexos os documentos. Obrigada disse ela."),
        ("Concordancia nominal: 'menos/quite'", "Invariável. Ex: Menos aulas."),
        ("Estilistica: metonimia", "Substituicao por relacao logica. Ex: Piazao pela selecao."),
        ("Estilistica: catacrese", "Figura desgastada pelo uso. Ex: pe da mesa, boca do forno."),
        ("Estilistica: antonomasia", "Substituicao por epiteto. Ex: O Poeta dos Escravos (Castro Alves)."),
        ("Estilistica: sinestesia", "Mistura sentidos. Ex: cor fria, som doce."),
        ("Estilistica: pleonasmo", "Repeticao enfatica. Ex: subir para cima."),
        ("Estilistica: eufemismo", "Suavizacao. Ex: Ele foi desta para melhor."),
        ("Estilistica: disfemismo", "Engrossamento. Ex: Ele bateu as botas."),
        ("Estilistica: ironia", "Dizer o contrario. Ex: Que bela bagunca!"),
        ("Estilistica: antitese", "Oposicao. Ex: amor e odio."),
        ("Estilistica: paradoxo", "Contradicao aparente. Ex: O silencio e ensurdecedor."),
        ("Estilistica: hipotipose", "Descricao vivida."),
        ("Estilistica: prosopopeia/personificacao", "Atribuir acoes humanas a seres inanimados."),
        ("Estilistica: aliteracao", "Repeticao consoantes. Ex: O rato roeu a roupa."),
        ("Estilistica: assonancia", "Repeticao vogais."),
        ("Genero textual: narrativo", "Conta historia. Elementos: enredo, personagens, tempo, espaco."),
        ("Genero textual: descritivo", "Caracteriza seres/objetos. Ex: verbos de estado, adjetivos."),
        ("Genero textual: dissertativo", "Defende tese. Estrutura: tese, argumentos, conclusao."),
        ("Genero textual: injuntivo", "Instrucoes. Ex: receitas, manuais."),
        ("Genero textual: expositivo", "Explica conceito. Ex: artigo cientifico, verbete."),
        ("Funcao referencial/denotativa", "Foco na informacao. 3a pessoa. Ex: noticia."),
        ("Funcao conativa/apelativa", "Foco no receptor. Imperativo. Ex: propaganda."),
        ("Funcao poetica", "Foco na mensagem. Figuras, sonoridade. Ex: poema."),
        ("Funcao fatica", "Foco no canal. Ex: alo, entendeu?"),
        ("Funcao metalinguistica", "Foco no codigo. Ex: dicionario, gramatica."),
        ("Discurso direto", "Reproducao fala. Travessao. Ex: Ele disse: 'Vou ja'."),
        ("Discurso indireto", "Narrador reproduz. Ex: Ele disse que ia ja."),
        ("Discurso indireto livre", "Mistura. Ex: Ele ia ja, pensou consigo."),
        ("Variacao diastratica", "Social/grupo. Ex: girias, jargoes."),
        ("Variacao diacronica", "Tempo. Ex: voce vs vosmece."),
        ("Variacao diamesica", "Meio. Ex: fala vs escrita."),
        ("Variacao diafasica", "Registro. Ex: formal vs informal."),
        ("Pronome relativo: que", "Universal, substitui coisa/pessoa."),
        ("Pronome relativo: quem", "Pessoa. Ex: O amigo a quem me refiro."),
        ("Pronome relativo: cujo", "Posse. Ex: O livro cuja capa e azul."),
        ("Pronome relativo: onde", "Lugar. Ex: A casa onde moro."),
        ("Pronome relativo: aonde", "Movimento. Ex: A cidade aonde vou."),
        ("Pronome relativo: qual", "Acompanhado artigo. Ex: O amigo o qual conheci."),
        ("Colocacao: proclise", "Pronome antes verbo. Palavra atrativa: nao, que, quem, adv, pron. Ex: Nao me diga."),
        ("Colocacao: mesoclise", "Pronome meio verbo. Futuro presente/pret. Ex: Dir-lhe-ei a verdade."),
        ("Colocacao: enclise", "Pronome apos verbo. Inicio frase, imperativo. Ex: Diga-me a verdade."),
    ]
    LP.extend(LP_subjuntivo)
    LP_extra = [
        ("Verbos defectivos", "Nao conjugados todas formas. Ex: falir, colorir, abolir."),
        ("Verbos abundantes no particulo", "Irregulares (aceito, eleito, entregue, gasto) + regulares."),
        ("Perifrases verbais", "Locucao verbal. Ex: estava cantando, vai cantar, tem cantado."),
        ("Formacao: prefixacao", "Prefixo + radical. Ex: desfazer, refazer."),
        ("Formacao: sufixacao", "Radical + sufixo. Ex: felizmente, florista."),
        ("Formacao: parassintese", "Prefixo+sufixo simultaneo. Ex: enrijecer, anoitecer."),
        ("Formacao: composicao justaposicao", "Palavras justas. Ex: guarda-chuva, passatempo."),
        ("Formacao: composicao aglutinacao", "Perdem fonemas. Ex: aguardente (agua+ardente), planalto (plano+alto)."),
        ("Formacao: hibridismo", "Elementos linguas diferentes. Ex: automovel (grego+latim)."),
        ("Formacao: onomatopeia", "Imitacao sons. Ex: tique-taque, miau."),
        ("Formacao: abreviacao", "Reducao. Ex: foto (fotografia), moto (motocicleta)."),
        ("Formacao: sigla", "Iniciais. Ex: IBGE, USP, INSS."),
        ("Formacao: derivacao regressiva", "Reduz verbo. Ex: ataque (atacar), choro (chorar)."),
        ("Formacao: derivacao impropria", "Muda classe sem alterar forma. Ex: o olhar (verbo>substantivo)."),
        ("Silepse genero", "Concorda com sentido. Ex: A gente somos feliz."),
        ("Silepse numero", "Concorda plural. Ex: A turma chegaram tarde."),
        ("Silepse pessoa", "Concorda emissor. Ex: Os brasileiros somos assim."),
        ("Zeugma", "Omissao termo ja citado. Ex: Pedro gosta de matematica; eu, de portugues."),
    ]
    LP.extend(LP_extra)
    print(f"  LP expanded: {len(LP_subjuntivo)+len(LP_extra)} cards")

    # --- Etica expansion (~500 cards) ---
    etica_expand = [
        ("LGPD: art. 2 fundamentos", "Privacidade, autodeterminacao, direitos humanos, livre iniciativa."),
        ("LGPD: art. 5 dado pessoal", "Informacao relativa a pessoa natural identificada ou identifcavel."),
        ("LGPD: art. 5 dado sensivel", "Origem racial, conviccao religiosa, saude, biometria."),
        ("LGPD: art. 5 anonimizacao", "Dado que nao permite identificacao."),
        ("LGPD: art. 6 principios", "Finalidade, adequacao, necessidade, livre acesso, qualidade, seguranca, prevencao, nao discriminacao."),
        ("LGPD: art. 7 bases legais", "10 bases para tratamento dados pessoais."),
        ("LGPD: art. 8 consentimento", "Manifestacao livre, especifica, informada."),
        ("LGPD: art. 11 sensiveis", "Consentimento especifico + destacado."),
        ("LGPD: art. 15 termino tratamento", "Fim finalidade, revogacao, determinacao legal."),
        ("LGPD: art. 17 direitos titular", "Confirmacao, acesso, correcao, anonimizacao, portabilidade."),
        ("LGPD: art. 18 direito acesso", "Confirmacao existencia tratamento."),
        ("LGPD: art. 19 resposta", "15 dias, formato simples ou eletronico."),
        ("LGPD: art. 20 revisao automatizada", "Revisao humana decisoes automatizadas."),
        ("LGPD: art. 26 compartilhamento", "Comunicacao com orgaos pesquisa."),
        ("LGPD: art. 27 uso publico", "Tratamento dados publicos para pesquisa."),
        ("LGPD: art. 33 transferencia", "Paises nivel protecao adequado."),
        ("LGPD: art. 37 seguranca", "Medidas tecnicas e administrativas."),
        ("LGPD: art. 41 encarregado DPO", "Comunicacao, orientacao, denuncias."),
        ("LGPD: art. 42 dano", "Responsabilidade solidaria operador e controlador."),
        ("LGPD: art. 45 ANPD", "Autoridade fiscalizadora."),
        ("LGPD: art. 52 multa", "2% faturamento, limite 50 milhoes."),
        ("LGPD: art. 53 multa simples", "Ate 2% faturamento por infracao."),
        ("LGPD: art. 54 sancoes", "Multa, publicizacao, bloqueio, eliminacao."),
        ("ODS 1 erradicacao pobreza", "Acabar com a pobreza em todas as formas."),
        ("ODS 2 fome zero", "Erradicar a fome, agricultura sustentavel."),
        ("ODS 3 saude bem-estar", "Vida saudavel para todos."),
        ("ODS 4 educacao qualidade", "Educacao inclusiva, equitativa e de qualidade."),
        ("ODS 5 igualdade genero", "Empoderar mulheres e meninas."),
        ("ODS 6 agua potavel", "Agua e saneamento para todos."),
        ("ODS 7 energia limpa", "Energia acessivel e limpa."),
        ("ODS 8 trabalho decente", "Crescimento economico e trabalho decente."),
        ("ODS 9 industria inovacao", "Infraestrutura, industrializacao, inovacao."),
        ("ODS 10 reducao desigualdades", "Reduzir desigualdades dentro e entre paises."),
        ("ODS 11 cidades sustentaveis", "Cidades e comunidades sustentaveis."),
        ("ODS 12 consumo consciente", "Consumo e producao responsaveis."),
        ("ODS 13 clima", "Acao contra mudanca climatica."),
        ("ODS 14 vida na agua", "Conservacao oceanos e mares."),
        ("ODS 15 vida terrestre", "Proteger florestas e biodiversidade."),
        ("ODS 16 paz justica", "Paz, justica e instituicoes eficazes."),
        ("ODS 17 parcerias", "Parcerias para implementacao."),
        ("ESG: E ambiental", "Mudancas climaticas, recursos naturais, poluicao."),
        ("ESG: S social", "Direitos trabalhistas, diversidade, saude, seguranca."),
        ("ESG: G governanca", "Transparencia, compliance, etica, conselho."),
        ("ESG: GHG Protocol", "Inventario emissoes gases estufa."),
        ("ESG: Scope 1", "Emissoes diretas fontes controladas."),
        ("ESG: Scope 2", "Emissoes indiretas energia adquirida."),
        ("ESG: Scope 3", "Outras emissoes indiretas cadeia valor."),
        ("ESG: greenwashing", "Pratica enganosa ambiental."),
        ("ESG: ISE B3", "Indice Sustentabilidade Empresarial B3."),
        ("ESG: PRI", "Principios Investimento Responsavel ONU."),
        ("ESG: reporting GRI", "Global Reporting Initiative. Padrao relatorios."),
        ("Anticorrupcao: art. 1", "Responsabilidade objetiva pessoas juridicas."),
        ("Anticorrupcao: art. 5 ato lesivo", "Corromper, fraudar, dificultar, obstruir."),
        ("Anticorrupcao: art. 6 multa", "0,1% a 20% faturamento bruto."),
        ("Anticorrupcao: art. 7 sancoes", "Publicacao extraordinaria, desconsideracao."),
        ("Anticorrupcao: art. 9 acordo leniencia", "Reducao pena."),
        ("Anticorrupcao: art. 10 requisitos leniencia", "Colaborar, admitir, devolver, reparar."),
        ("Anticorrupcao: art. 11 processo", "Processo administrativo."),
        ("Anticorrupcao: art. 12 CNEP", "Cadastro Nacional Empresas Punidas."),
        ("Anticorrupcao: art. 13 CEIS", "Cadastro Entidades Inidoneas."),
        ("Improbidade: art. 1 LIA", "Ato improbidade."),
        ("Improbidade: art. 2 sujeito", "Agente publico, terceiro beneficiado."),
        ("Improbidade: art. 3 terceiro", "Particular tambem responde."),
        ("Improbidade: art. 4 dolo", "Elemento subjetivo intencional."),
        ("Improbidade: art. 5 atos enriquecimento", "Art. 9: auferir vantagem."),
        ("Improbidade: art. 6 atos prejuizo", "Art. 10: causar prejuizo erario."),
        ("Improbidade: art. 7 atos principios", "Art. 11: violar principios administracao."),
        ("Improbidade: art. 12 penas", "Ressarcimento, multa, perda funcao, suspensao direitos."),
        ("Improbidade: art. 12 prazos", "8, 10, 12 anos conforme modalidade."),
        ("Improbidade: art. 16 indisponibilidade", "Bens para garantir ressarcimento."),
        ("Improbidade: art. 17 acao", "MP obrigatorio."),
        ("Compliance: pilares", "Prevenir, detectar, responder, monitorar."),
        ("Compliance: COSO", "Ambiente, avaliacao, controle, informacao, monitoramento."),
        ("Compliance: codigo conduta", "Normas e diretrizes eticas."),
        ("Compliance: canal denuncia", "Mecanismo anonimo reportar."),
        ("Compliance: due diligence", "Verificacao previa riscos."),
        ("Compliance: KYC", "Know Your Customer. Identificacao cliente."),
        ("Compliance: AML", "Anti Money Laundering. Prevencao lavagem."),
        ("Compliance: PLD", "Prevencao Lavagem Dinheiro."),
        ("Lavagem: 1 fase colocacao", "Introducao sistema financeiro."),
        ("Lavagem: 2 fase ocultacao", "Multiplas transacoes."),
        ("Lavagem: 3 fase integracao", "Retorno aparencia legal."),
        ("Governanca: conselho administracao", "Estrategia e supervisao."),
        ("Governanca: diretoria", "Execucao e gestao."),
        ("Governanca: conselho fiscal", "Fiscalizacao contas."),
        ("Governanca: auditoria interna", "Controles e riscos."),
        ("Governanca: comite auditoria", "Relacao com auditoria independente."),
        ("Governanca: comite remuneracao", "Politica compensacao."),
        ("Governanca: comite nomeacao", "Sucessao e indicacao."),
        ("Governanca: IAG 1", "Propriedade e controle."),
        ("Governanca: IAG 2", "Conselho e gestao."),
        ("Governanca: IAG 3", "Auditoria e riscos."),
        ("Governanca: IAG 4", "Transparencia e conduta."),
        ("LAI: art. 5 acesso", "Acesso informacao direito fundamental."),
        ("LAI: art. 7 informacoes", "Competencias, gastos, licitacoes, servidores."),
        ("LAI: art. 8 transparencia ativa", "Divulgar obrigatoriamente sites."),
        ("LAI: art. 10 pedido", "Qualquer pessoa, sem motivacao."),
        ("LAI: art. 11 prazo", "20 dias + 10 prorrogacao."),
        ("LAI: art. 12 formato", "Preferencialmente eletronico."),
        ("LAI: art. 16 recurso", "3 instancias: CGU, CMRI."),
        ("LAI: art. 21 sigilo", "Informacoes pessoais 100 anos."),
        ("LAI: art. 22 classificacao", "Ultrassecreto 25a, secreto 15a, reservado 5a."),
        ("Lideranca: autocratica", "Decisoes centralizadas."),
        ("Lideranca: democratica", "Participativa."),
        ("Lideranca: laissez-faire", "Liberdade total."),
        ("Lideranca: situacional", "Adapta-se contexto."),
        ("Lideranca: transformacional", "Inspira e motiva."),
        ("Lideranca: servidora", "Foco servico aos outros."),
        ("Lideranca: coaching", "Desenvolve pessoas."),
        ("Lideranca: etica", "Exemplo, integridade, valores."),
    ]
    ET.extend(etica_expand)
    print(f"  Etica expanded: {len(etica_expand)} cards")

    # --- RLP expansion (~500 cards) ---
    rlp_expand = [
        ("Equivalencia: contrapositiva", "p→q ≡ ¬q→¬p."),
        ("Equivalencia: p→q ≡ ¬p∨q", "Condicional como disjuncao."),
        ("Equivalencia: ¬(p∧q) ≡ ¬p∨¬q", "De Morgan AND."),
        ("Equivalencia: ¬(p∨q) ≡ ¬p∧¬q", "De Morgan OR."),
        ("Equivalencia: p↔q ≡ (p→q)∧(q→p)", "Bicondicional."),
        ("Equivalencia: p∨(q∧r) ≡ (p∨q)∧(p∨r)", "Distributiva."),
        ("Equivalencia: p∧(q∨r) ≡ (p∧q)∨(p∧r)", "Distributiva."),
        ("Negacao: ¬(∀x P(x)) ≡ ∃x ¬P(x)", "Negacao universal."),
        ("Negacao: ¬(∃x P(x)) ≡ ∀x ¬P(x)", "Negacao existencial."),
        ("Negacao: ¬(p∧q) ≡ ¬p∨¬q", "Nega E vira OU negado."),
        ("Negacao: ¬(p∨q) ≡ ¬p∧¬q", "Nega OU vira E negado."),
        ("Negacao: ¬(p→q) ≡ p∧¬q", "Nega condicional: mantem antecedente, nega consequente."),
        ("Negacao: ¬(p↔q) ≡ p⊕q", "Nega bicondicional: ou exclusivo."),
        ("Negacao: ¬(∀x P(x)) ≡ ∃x ¬P(x)", "Nega todo = existe um nao."),
        ("Silogismo hipotetico", "p→q, q→r ⊢ p→r."),
        ("Modus ponens", "p→q, p ⊢ q."),
        ("Modus tollens", "p→q, ¬q ⊢ ¬p."),
        ("Silogismo disjuntivo", "p∨q, ¬p ⊢ q."),
        ("Absorcao", "p→q ⊢ p→(p∧q)."),
        ("Dilema construtivo", "(p→q)∧(r→s), p∨r ⊢ q∨s."),
        ("Dilema destrutivo", "(p→q)∧(r→s), ¬q∨¬s ⊢ ¬p∨¬r."),
        ("Falacia ad hominem", "Atacar pessoa nao argumento."),
        ("Falacia ad verecundiam", "Apelo autoridade irrelevante."),
        ("Falacia ad populum", "Apelo popularidade."),
        ("Falacia ad ignorantiam", "Ausencia prova como prova."),
        ("Falacia apelo emocao", "Manipulacao emocional."),
        ("Falacia falso dilema", "So duas opcoes."),
        ("Falacia ladeira escorregadia", "Evento leva a outro extremo."),
        ("Falacia peticao principio", "Premissa ja contem conclusao."),
        ("Falacia anedota", "Evidencia anedotica como geral."),
        ("Falacia espantalho", "Distorce argumento."),
        ("Falacia correlacao causal", "Correlacao nao implica causalidade."),
        ("Falacia generalizacao apressada", "Poucos casos conclusao geral."),
        ("Falacia composicao", "Parte tem propriedade = todo tem."),
        ("Probabilidade: P(A∪B) = P(A)+P(B)-P(A∩B)", "Uniao."),
        ("Probabilidade: P(A|B) = P(A∩B)/P(B)", "Condicional."),
        ("Probabilidade: P(A∩B)=P(A)*P(B)", "Eventos independentes."),
        ("Probabilidade: complementar P(A^c)", "= 1-P(A)."),
        ("Probabilidade: Teorema Bayes", "P(A|B) = P(B|A)*P(A)/P(B)."),
        ("Estatistica: media geometrica", "∛(a*b*c). Crescimento percentual."),
        ("Estatistica: media harmonica", "n/(Σ1/x_i). Velocidade media."),
        ("Sequencia: PA termo geral", "an = a1 + (n-1)*r."),
        ("Sequencia: PA soma", "Sn = (a1+an)*n/2."),
        ("Sequencia: PG termo geral", "an = a1 * q^(n-1)."),
        ("Sequencia: PG soma finita", "Sn = a1*(q^n-1)/(q-1)."),
        ("Sequencia: PG soma infinita", "S∞ = a1/(1-q), |q|<1."),
        ("Matematica: logaritmo definicao", "log_a(b) = c <=> a^c = b."),
        ("Matematica: propriedades log", "log(ab)=log(a)+log(b), log(a/b)=log(a)-log(b), log(a^n)=n*log(a)."),
        ("Matematica: equacao 1o grau", "ax+b=0 => x=-b/a."),
        ("Matematica: equacao 2o grau", "ax^2+bx+c=0 => Δ=b^2-4ac, x=(-b±√Δ)/(2a)."),
        ("Matematica: sistema 2x2", "Substituicao ou adicao."),
        ("Matematica: regra tres simples", "Proporcao."),
        ("Matematica: regra tres composta", "Multiplas grandezas."),
        ("Matematica: porcentagem", "Parte/100 * total."),
        ("Matematica: variacao percentual", "(Vf-Vi)/Vi * 100."),
        ("Matematica: juros simples formula", "J = C*i*n, M = C+J."),
        ("Matematica: juros compostos formula", "M = C*(1+i)^n."),
        ("Matematica: analise combinatoria PFC", "Multiplica possibilidades."),
        ("Anal comb: permutacao simples", "Pn = n!."),
        ("Anal comb: permutacao repeticao", "Pn(a,b,c) = n!/(a!b!c!)."),
        ("Anal comb: arranjo", "An,p = n!/(n-p)!."),
        ("Anal comb: combinacao", "Cn,p = n!/(p!(n-p)!)."),
        ("Anal comb: permutacao circular", "Pn(circ) = (n-1)!."),
        ("Conjuntos: A⊂B", "A subconjunto de B."),
        ("Conjuntos: A∩B", "Intersecao (comum)."),
        ("Conjuntos: A∪B", "Uniao (todos)."),
        ("Conjuntos: A-B", "Diferenca (so A)."),
        ("Conjuntos: complementar", "Elementos U nao em A."),
        ("Conjuntos: cardinalidade", "|A∪B| = |A|+|B|-|A∩B|."),
        ("Logica: proposicao simples", "Valor logico V ou F."),
        ("Logica: proposicao composta", "Conectivos: e, ou, nao, se...entao, se...se."),
        ("Logica: Tabela verdade p∧q", "V so se ambos V."),
        ("Logica: Tabela verdade p∨q", "F so se ambos F."),
        ("Logica: Tabela verdade p→q", "F so se V→F."),
        ("Logica: Tabela verdade p↔q", "V se valores iguais."),
        ("Logica: tautologia", "Sempre V."),
        ("Logica: contradicao", "Sempre F."),
        ("Logica: contingencia", "V e F possiveis."),
        ("Logica: argumento valido", "Premissas verdadeiras => conclusao verdadeira."),
        ("Logica: quantificador universal ∀", "Para todo."),
        ("Logica: quantificador existencial ∃", "Existe pelo menos um."),
    ]
    RL.extend(rlp_expand)
    print(f"  RLP expanded: {len(rlp_expand)} cards")

    # --- Previdencia expansion (~500 cards) ---
    prev_expand = [
        ("PREVIC: DN 1", "Plano de custeio."),
        ("PREVIC: DN 2", "Politica de investimentos."),
        ("PREVIC: DN 3", "Reservas e provisoes."),
        ("PREVIC: DN 4", "Governanca corporativa."),
        ("PREVIC: DN 5", "Controles internos."),
        ("PREVIC: DN 6", "Auditoria."),
        ("PREVIC: DN 7", "Gestao de riscos."),
        ("PREVIC: DN 8", "Transparencia."),
        ("PREVIC: DN 9", "Elegibilidade e beneficios."),
        ("PREVIC: vedações dirigentes", "Empregado patrocinador, fornecedor, cargo politico."),
        ("PREVIC: termo responsabilidade", "Ajuste conduta gestores."),
        ("PLANO BD: risco", "Risco atuarial da entidade."),
        ("PLANO BD: contribuicao", "Variavel para equilibrio."),
        ("PLANO BD: reserva", "Reserva matematica calculada atuarialmente."),
        ("PLANO BD: solvencia", "Ativos >= passivo atuarial."),
        ("PLANO BD: deficit", "Patrocinador e participantes custeiam."),
        ("PLANO CD: conta individual", "Saldo acumulado individual."),
        ("PLANO CD: risco", "Do participante (rentabilidade)."),
        ("PLANO CD: contribuicao", "Fixa, definida regulamento."),
        ("PLANO CD: beneficio", "Saldo acumulado."),
        ("PLANO CV: acumulacao", "CD: saldo conta individual."),
        ("PLANO CV: concessao", "BD: formula beneficio definido."),
        ("PLANO CV: risco", "Compartilhado."),
        ("PLANO CV: reserva", "Pool compartilhado risco."),
        ("Reserva contingencia", "Superavit para eventualidades."),
        ("Reserva oscilacao", "Variacoes mercado e atuariais."),
        ("Reserva especial", "Revisao plano beneficio. Apos contingencia."),
        ("Equacionamento deficit: alternativas", "Aumento contrib, reducao beneficio, planos especiais."),
        ("Equacionamento: plano equacionamento", "Cronograma eliminacao deficit."),
        ("Revisao plano: superavit", "Melhoria beneficios, reducao contribuicoes, devolucao."),
        ("TITULOS IPCA+ beneficios", "Protecao inflacionaria beneficios."),
        ("Alocacao: duration", "Casamento prazo passivo atuarial."),
        ("Alocacao: benchmark", "Indice referencia carteira."),
        ("Alocacao: risk budgeting", "Orcamento risco por ativo."),
        ("CMN Res 4.963 RF minima", "55%."),
        ("CMN Res 4.963 RV maxima", "40% (para rating) ou 25% (demais)."),
        ("CMN Res 4.963 imoveis", "Maximo 8%."),
        ("CMN Res 4.963 exterior", "Maximo 10%."),
        ("CMN Res 4.963 emprestimos", "Maximo 5%."),
        ("CMN Res 4.963 FIP", "Maximo 15% (non-public assets)."),
        ("Delega: gestao terceirizada", "Contrata gestor profissional."),
        ("Delega: custodia", "Banco custodante."),
        ("Delega: corretagem", "Intermediacao compra/venda."),
        ("Indices: CDI", "Depositos interfinanceiros."),
        ("Indices: IMA-B", "Indice Mercado Anbima - Titulos IPCA."),
        ("Indices: IMA-C", "Indice Mercado Anbima - Prefixados."),
        ("Indices: IRF-M", "Indice RF Mercado - Prefixados."),
        ("Indices: IDA", "Indice Debentures Anbima."),
        ("Indices: Ibovespa", "Acoes B3."),
        ("Indices: IFIX", "Fundos imobiliarios."),
        ("Ativo financeiro: definicao", "Direito sobre fluxo caixa futuro."),
        ("Passivo financeiro: definicao", "Obrigacao transferir recurso."),
        ("Instrumento derivativo", "Valor deriva de ativo subjacente."),
        ("Swap: definicao", "Troca fluxos indexadores."),
        ("Swap: exemplo", "Troca CDI por IPCA."),
        ("Futuro: ajuste diario", "Liquidacao diaria ganhos/perdas."),
        ("Opcao: call", "Direito compra."),
        ("Opcao: put", "Direito venda."),
        ("Opcao: strike", "Preco exercicio."),
        ("Opcao: premio", "Custo da opcao."),
        ("Termo: nao padronizado", "Acordo privado compra/venda futuro."),
        ("Renda fixa: prefixado", "Taxa definida emissao."),
        ("Renda fixa: pos-fixado", "Indexador + spread."),
        ("Renda fixa: NTN-B", "Tesouro IPCA+."),
        ("Renda fixa: NTN-F", "Tesouro Prefixado."),
        ("Renda fixa: LFT", "Tesouro Selic."),
        ("Renda fixa: debenture", "Titulo divida privado."),
        ("Renda fixa: CRI", "Certificado Recebiveis Imobiliarios."),
        ("Renda fixa: CRA", "Certificado Recebiveis Agro."),
        ("Renda fixa: LCI", "Letra Credito Imobiliario."),
        ("Renda fixa: LCA", "Letra Credito Agro."),
        ("Renda fixa: CDB", "Certificado Deposito Bancario."),
        ("Renda fixa: risco credito", "Risco contraparte nao pagar."),
        ("Renda fixa: rating", "Classificacao risco credito."),
        ("Renda fixa: duration", "Prazo medio ponderado fluxos."),
        ("Renda fixa: convexidade", "Curvatura relacao preco-taxa."),
        ("Renda variavel: acao ON", "Com voto."),
        ("Renda variavel: acao PN", "Preferencial dividendos."),
        ("Renda variavel: dividendo", "Distribuicao lucro."),
        ("Renda variavel: JCP", "Juros Capital Proprio."),
        ("Renda variavel: valor intrinseco", "Valor real empresa."),
        ("Renda variavel: valor mercado", "Preco acao * n acoes."),
        ("Renda variavel: P/L", "Preco/Lucro."),
        ("Renda variavel: P/VP", "Preco/Valor Patrimonial."),
        ("Renda variavel: EV/EBITDA", "Valor Firma/EBITDA."),
        ("Renda variavel: dividend yield", "Dividendo/Preco."),
        ("Renda variavel: ROE", "Lucro Liquido/Patrimonio Liquido."),
        ("Renda variavel: ROC", "Retorno sobre Capital."),
        ("Fundos: FIA", "Fundos Investimento Acoes."),
        ("Fundos: FIM", "Fundos Multimercado."),
        ("Fundos: FIC", "Fundos Investimento Cotas."),
        ("Fundos: ETF", "Exchange Traded Fund. Negociado Bolsa."),
        ("Fundos: taxa administracao", "Anual sobre patrimonio."),
        ("Fundos: taxa performance", "Sobre CDI + % excedente."),
        ("Fundos: patrimonio liquido", "Ativos - passivos."),
        ("Fundos: cota", "Valor unitario fundo."),
        ("Fundos: resgate", "Prazo conversao cotas."),
        ("Atuario: tábua mortalidade geral", "Populacao geral."),
        ("Atuario: tábua mortalidade selecionada", "Grupo especifico."),
        ("Atuario: tábua entrada invalidez", "Probabilidade tornar invalido."),
        ("Atuario: taxa juros real atuarial", "Desconto fluxos."),
        ("Atuario: salario projecao", "Crescimento real carreira."),
        ("Atuario: beneficio projecao", "Valor futuro beneficio."),
        ("Atuario: custo normal", "Contribuicao anual nivelada."),
        ("Atuario: custo suplementar", "Amortizacao deficit."),
        ("Atuario: provisao matematica beneficios concedidos", "Aposentados/pensionistas."),
        ("Atuario: provisao matematica beneficios a conceder", "Participantes ativos."),
        ("Atuario: provisao riscos", "Riscos nao ocorridos (invalidez, morte)."),
        ("Atuario: hipotese rotatividade", "% saida antes aposentadoria."),
        ("Atuario: hipotese composicao familiar", "% com dependentes."),
        ("Atuario: hipotese crescimento salarial", "Projecao aumento salarial."),
        ("Atuario: hipotese inflacao", "Projecao inflacao LP."),
    ]
    PR.extend(prev_expand)
    print(f"  Previdencia expanded: {len(prev_expand)} cards")

    # --- TI expansion (~500 cards) ---
    ti_expand = [
        ("REST: GET /recursos", "Listar recursos."),
        ("REST: POST /recursos", "Criar recurso."),
        ("REST: PUT /recursos/{id}", "Atualizar recurso completo."),
        ("REST: PATCH /recursos/{id}", "Atualizar parcial."),
        ("REST: DELETE /recursos/{id}", "Remover recurso."),
        ("REST: status 200", "OK."),
        ("REST: status 201", "Created."),
        ("REST: status 204", "No Content."),
        ("REST: status 400", "Bad Request."),
        ("REST: status 401", "Unauthorized."),
        ("REST: status 403", "Forbidden."),
        ("REST: status 404", "Not Found."),
        ("REST: status 500", "Internal Server Error."),
        ("REST: HATEOAS", "Links hipermidia respostas."),
        ("GraphQL: query", "Busca dados. Hierarquico."),
        ("GraphQL: mutation", "Modifica dados."),
        ("GraphQL: subscription", "Tempo real."),
        ("GraphQL: resolver", "Funcao resolve campo."),
        ("GraphQL: schema", "Tipos e campos disponiveis."),
        ("GraphQL: vantagens", "Cliente define query. Menos over/under-fetching."),
        ("gRPC: definicao", "RPC performatico. HTTP/2, Protobuf."),
        ("gRPC: vantagens", "Baixa latencia, streaming bidirecional."),
        ("gRPC: protocol buffers", ".proto, binario, tipado."),
        ("WebSocket: handshake", "HTTP upgrade."),
        ("WebSocket: frames", "Dados binario/texto."),
        ("WebSocket: usos", "Chat, notificacoes, jogos."),
        ("Mensageria: RabbitMQ", "AMQP. Broker, exchanges, queues."),
        ("Mensageria: Kafka", "Log distribuido. Topics, partitions. Alta vazao."),
        ("Mensageria: SQS", "AWS queue. Pull-based."),
        ("Mensageria: SNS", "AWS pub/sub. Push-based."),
        ("Mensageria: publish-subscribe", "Publica topico, varios assinantes."),
        ("Mensageria: point-to-point", "Fila, um consumidor por msg."),
        ("Mensageria: dead letter queue", "Msgs falhas processamento."),
        ("Cache: Redis comando SET", "Guarda chave-valor."),
        ("Cache: Redis comando GET", "Recupera valor chave."),
        ("Cache: Redis EXPIRE", "TTL chave."),
        ("Cache: CDN", "Cache distribuido geograficamente."),
        ("Cache: estrategia cache aside", "Aplicacao gerencia cache."),
        ("Cache: estrategia write-through", "Cache + DB sinal."),
        ("Cache: estrategia write-behind", "Cache primeiro, DB async."),
        ("Cache: TTL", "Time To Live. Expira automaticamente."),
        ("Cache: invalidation", "Remover cache desatualizado."),
        ("Seguranca: OAuth2 grant authorization code", "Code + token. Servidor backend."),
        ("Seguranca: OAuth2 grant implicit", "Token direto. Public client."),
        ("Seguranca: OAuth2 grant client credentials", "Servico a servico."),
        ("Seguranca: OAuth2 grant password", "User+pass direto."),
        ("Seguranca: OAuth2 grant refresh token", "Novo token sem reautenticar."),
        ("Seguranca: JWT estrutura", "Header.payload.signature."),
        ("Seguranca: JWT header", "Alg (HS256, RS256), typ: JWT."),
        ("Seguranca: JWT payload", "Claims (sub, iat, exp, iss)."),
        ("Seguranca: JWT signature", "Assina header+payload."),
        ("Seguranca: CORS", "Cross-Origin Resource Sharing. Headers."),
        ("Seguranca: CSP", "Content Security Policy. Previne XSS."),
        ("Seguranca: CSRF token", "Token anti-CSRF."),
        ("Seguranca: X-Frame-Options", "Previne clickjacking."),
        ("Seguranca: HSTS", "Strict Transport Security. Forca HTTPS."),
        ("Seguranca: OWASP Top 1 Broken Access Control", "Falhas controle acesso."),
        ("Seguranca: OWASP Top 2 Crypto Failures", "Falhas criptograficas."),
        ("Seguranca: OWASP Top 3 Injection", "SQL, NoSQL, OS injection."),
        ("Seguranca: OWASP Top 4 Insecure Design", "Falhas design."),
        ("Seguranca: OWASP Top 5 Security Misconfiguration", "Config insegura."),
        ("Seguranca: OWASP Top 6 Vulnerable Components", "Componentes vulneraveis."),
        ("Seguranca: OWASP Top 7 Auth Failures", "Falhas autenticacao."),
        ("Seguranca: OWASP Top 8 Data Integrity Failures", "Falhas integridade dados."),
        ("Seguranca: OWASP Top 9 Logging Failures", "Falhas monitoramento."),
        ("Seguranca: OWASP Top 10 SSRF", "Server-Side Request Forgery."),
        ("Cloud: AWS S3 classes", "Standard, IA, Glacier, Deep Archive."),
        ("Cloud: AWS S3 versioning", "Multiplas versoes."),
        ("Cloud: AWS S3 lifecycle", "Transicao automatica classes."),
        ("Cloud: AWS S3 encryption", "SSE-S3, SSE-KMS, SSE-C."),
        ("Cloud: AWS S3 bucket policy", "Politica acesso bucket."),
        ("Cloud: AWS Lambda triggers", "S3, DynamoDB, SQS, API Gateway."),
        ("Cloud: AWS Lambda cold start", "Latencia inicial."),
        ("Cloud: AWS Lambda timeout", "Max 15 min."),
        ("Cloud: AWS VPC components", "Subnet, route table, IGW, NAT, SG, NACL."),
        ("Cloud: AWS SG vs NACL", "SG stateful (instancia). NACL stateless (subnet)."),
        ("Cloud: AWS DynamoDB", "NoSQL chave-valor/documento."),
        ("Cloud: AWS DynamoDB RCU/WCU", "Read/Write capacity units."),
        ("Cloud: AWS DynamoDB DAX", "Cache in-memory."),
        ("Cloud: AWS RDS engines", "MySQL, PostgreSQL, Oracle, SQL Server, Aurora."),
        ("Cloud: AWS RDS Multi-AZ", "Alta disponibilidade."),
        ("Cloud: AWS RDS Read Replica", "Escala leitura."),
        ("Cloud: AWS CloudFormation", "IaC AWS."),
        ("Cloud: AWS Elastic Beanstalk", "PaaS automatico."),
        ("Cloud: AWS Step Functions", "Orquestracao serverless."),
        ("Cloud: AWS API Gateway", "API REST/WebSocket gerenciada."),
        ("Cloud: AWS KMS", "Gerenciamento chaves."),
        ("Cloud: AWS Secrets Manager", "Gerenciamento segredos."),
        ("Cloud: AWS CloudTrail", "Auditoria API calls."),
        ("Cloud: AWS Config", "Avaliacao conformidade recursos."),
        ("Cloud: AWS WAF", "Firewall aplicacao web."),
        ("Cloud: AWS Shield", "Protecao DDoS."),
        ("Cloud: AWS Organizations", "Governanca multi-conta."),
        ("Cloud: AWS Cost Explorer", "Analise custos."),
        ("Cloud: Azure Resource Group", "Container recursos."),
        ("Cloud: Azure Logic Apps", "Workflow integracao."),
        ("Cloud: Azure DevOps", "CI/CD, boards, repos."),
        ("Cloud: GCP Cloud Run", "Containers serverless."),
        ("Cloud: GCP Cloud Build", "CI/CD."),
        ("DevOps: Git flow", "Branches: master, develop, feature, release, hotfix."),
        ("DevOps: trunk-based", "Branch unica, commits frequentes."),
        ("DevOps: deployment strategies", "Rolling, blue/green, canary, recreate."),
        ("DevOps: blue/green", "Duplo ambiente. Switch DNS."),
        ("DevOps: canary", "% trafego novo, gradual."),
        ("DevOps: rolling update", "Gradual, pod a pod."),
        ("DevOps: monitoring 4 signals", "Latency, traffic, errors, saturation (Google SRE)."),
        ("DevOps: SLI", "Service Level Indicator. Metrica."),
        ("DevOps: SLO", "Service Level Objective. Alvo."),
        ("DevOps: SLA", "Service Level Agreement. Contrato."),
        ("DevOps: observability", "Logs, metrics, traces."),
        ("DevOps: ELK stack components", "Elasticsearch (busca), Logstash (processa), Kibana (vis)."),
        ("DevOps: Prometheus features", "Pull metrics, alerting, time-series DB."),
        ("DevOps: Grafana datasources", "Prometheus, InfluxDB, CloudWatch, Elasticsearch."),
        ("DevOps: Jaeger opentelemetry", "Tracing distribuido."),
        ("Python: Flask vs Django", "Flask: micro, flexivel. Django: full-stack, batteries-included."),
        ("Python: FastAPI", "Async, OpenAPI, Pydantic. Moderno."),
        ("Python: asyncio", "Programacao assincrona."),
        ("Python: Celery", "Task queue distribuida."),
        ("Python: SQLAlchemy", "ORM Python."),
        ("Python: Alembic", "Migrations."),
        ("Python: Pydantic v2", "Validacao dados, models."),
        ("Python: typing hints", "Type hints, mypy."),
        ("Java: Maven vs Gradle", "Maven: XML, padrao. Gradle: Groovy/Kotlin, flexivel."),
        ("Java: JPA/Hibernate", "ORM Java."),
        ("Java: JUnit 5", "Testes unitarios."),
        ("Java: Mockito", "Mock test framework."),
        ("Java: Swagger/OpenAPI", "Documentacao API."),
        ("Java: Lombok", "Reduz boilerplate."),
        ("Java: Micronaut", "Framework leve, compilacao AOT."),
        ("Java: Quarkus", "Supersonic Subatomic Java."),
        ("JS: TypeScript", "Tipado, compila JS."),
        ("JS: Next.js", "React SSR/SSG."),
        ("JS: NestJS", "Node.js framework estruturado."),
        ("JS: Express", "HTTP server minimalista."),
        ("JS: Prisma", "ORM TS/JS."),
        ("JS: Zod", "Validacao schema."),
        ("Docker: docker-compose up", "Sobe servicos."),
        ("Docker: docker build", "Constroi imagem."),
        ("Docker: docker push", "Envia registry."),
        ("Docker: docker pull", "Baixa imagem."),
        ("Docker: docker exec", "Executa comando container."),
        ("Docker: docker logs", "Logs container."),
        ("K8s: kubectl get pods", "Lista pods."),
        ("K8s: kubectl apply", "Aplica manifesto."),
        ("K8s: kubectl describe", "Detalha recurso."),
        ("K8s: health probes", "Liveness, readiness, startup."),
        ("K8s: HPA", "Horizontal Pod Autoscaler."),
        ("K8s: VPA", "Vertical Pod Autoscaler."),
        ("K8s: PDB", "Pod Disruption Budget."),
        ("K8s: RBAC", "Role, ClusterRole, RoleBinding."),
        ("K8s: PV/PVC", "Persistent Volume/Claim."),
        ("K8s: StorageClass", "Classe armazenamento dinamico."),
        ("K8s: StatefulSet", "Aplicacoes stateful."),
        ("K8s: DaemonSet", "Pod em cada node."),
        ("K8s: Job/CronJob", "Tarefas batch."),
        ("BD: ACID detalhado", "A: tudo ou nada. C: integridade. I: concorrencia. D: persistencia."),
        ("BD: isolation levels", "Read uncommitted, read committed, repeatable read, serializable."),
        ("BD: read committed", "So le dados commitados. Evita dirty read."),
        ("BD: repeatable read", "Leitura consistente. Evita dirty + non-repeatable."),
        ("BD: serializable", "Total isolamento. Evita todas anomalias."),
        ("BD: dirty read", "Le dado nao commitado."),
        ("BD: non-repeatable read", "Mesma query retorna diferente."),
        ("BD: phantom read", "Novas linhas aparecem."),
        ("BD: index clustered", "Dados ordenados fisicamente."),
        ("BD: index non-clustered", "Dados separados, ponteiros."),
        ("BD: explain analyze", "Executa e mostra plano real."),
        ("BD: query planner", "Escolhe melhor acesso dados."),
        ("BD: full table scan", "Le toda tabela. Ruim grandes."),
        ("BD: index seek", "Busca eficiente index."),
        ("BD: index scan", "Varre todo index."),
        ("BD: composite index columns order", "Cardinalidade, seletividade."),
        ("BD: covering index", "Index inclui todas colunas query."),
        ("BD: fill factor", "% preenchimento pagina index."),
        ("BD: deadlock", "Transacoes esperam recurso mutuamente."),
        ("BD: deadlock prevention", "Acesso recursos mesma ordem."),
        ("BD: connection pool", "Reutiliza conexoes DB."),
        ("Big Data: 3 Vs", "Volume, velocidade, variedade."),
        ("Big Data: 5 Vs", "+ veracidade, valor."),
        ("Big Data: Hadoop HDFS", "Sistema arquivos distribuido."),
        ("Big Data: Hadoop MapReduce", "Processamento batch distribuido."),
        ("Big Data: Spark", "Processamento in-memory. Rapido."),
        ("Big Data: Spark RDD", "Resilient Distributed Dataset."),
        ("Big Data: Spark DataFrame", "API estruturada."),
        ("Big Data: Spark SQL", "SQL sobre DataFrames."),
        ("Big Data: Spark Streaming", "Processamento tempo real."),
        ("Big Data: Hive", "SQL sobre Hadoop."),
        ("Big Data: HBase", "NoSQL column-family Hadoop."),
        ("Big Data: Airflow", "Orquestracao pipelines."),
        ("Big Data: Kafka streams", "Processamento streaming."),
        ("Big Data: Flink", "Stream processing. Event time."),
        ("IA: Machine Learning tipos", "Supervisionado, nao supervisionado, reforco."),
        ("ML: supervised", "Dados rotulados, prever target."),
        ("ML: unsupervised", "Sem rotulo, encontrar padroes."),
        ("ML: reinforcement", "Agente aprende por recompensa."),
        ("ML: regressao linear", "y = wx + b."),
        ("ML: regressao logistica", "Probabilidade 0-1."),
        ("ML: SVM", "Hiperplano separacao."),
        ("ML: KNN", "Classifica por vizinhos."),
        ("ML: K-means", "Clusteriza K grupos."),
        ("ML: decision tree criteria", "Gini, entropia, information gain."),
        ("ML: ensemble bagging", "Modelos paralelos. Random Forest."),
        ("ML: ensemble boosting", "Modelos sequenciais. XGBoost, LightGBM."),
        ("ML: overfitting prevencao", "Regularizacao L1/L2, dropout, cross-validation."),
        ("ML: bias vs variance", "Underfit (bias alto). Overfit (variancia alta)."),
        ("ML: confusion matrix", "VP, FP, VN, FN."),
        ("ML: ROC AUC", "Curva VP vs FP. Area sob curva."),
        ("ML: feature importance", "Peso cada feature modelo."),
        ("DL: CNN conceito", "Convolucao imagens. Filtros, pooling."),
        ("DL: RNN LSTM", "Sequencias. Memoria longa."),
        ("DL: transformer attention", "Q, K, V. Auto-atencao."),
        ("DL: BERT uso", "Embeddings contextuais. NLP."),
        ("DL: GPT uso", "Geracao texto. Autoregressivo."),
        ("DL: transfer learning", "Modelo pre-treinado + fine-tune."),
        ("DL: fine-tuning full", "Ajusta todos pesos."),
        ("DL: fine-tuning LoRA", "Adaptadores leves. Poucos parametros."),
        ("DL: RLHF", "Reinforcement Learning from Human Feedback."),
        ("DL: embedding", "Vetor denso representacao."),
        ("DL: tokenization", "Divide texto em tokens."),
        ("DL: vector database", "Armazena embeddings. Pinecone, Weaviate."),
        ("DL: RAG exemplo", "Query → busca documentos → LLM responde com contexto."),
        ("TI: ITIL 4 dimensions", "Pessoas, processos, tecnologia, parceiros."),
        ("TI: ITIL 4 SVS", "Service Value System."),
        ("TI: ITIL 4 value chain", "Plan, Improve, Engage, Design, Obtain, Deliver."),
        ("TI: COBIT 5 principios", "Stakeholder value, governance, integrated, holistic, separte governance/management."),
        ("TI: COBIT goals cascade", "Stakeholder drivers → enterprise goals → IT goals → enabler goals."),
        ("TI: COBIT enablers", "Principles, processes, structures, culture, information, skills, services."),
        ("TI: CMMI maturidade", "Initial, Managed, Defined, Quantitatively Managed, Optimizing."),
        ("TI: PMP processos", "49 processos, 10 areas, 5 grupos."),
        ("TI: Scrum velho vs novo", "Scrum Guide 2020: um Product Goal, nao 3 perguntas diarias."),
        ("TI: SAFe", "Scaled Agile Framework. Program, large solution, portfolio."),
    ]
    TI.extend(ti_expand)
    print(f"  TI expanded: {len(ti_expand)} cards")
'''

# Insert before the print summary
idx = content.rfind(insert_marker)
if idx != -1:
    new_content = content[:idx + len(insert_marker)] + extra_content + content[idx + len(insert_marker):]
    with open(path, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"Expansion inserted. File size: {len(new_content)} chars")
else:
    print("ERROR: marker not found!")
