"""Fifth and final batch expansion: ~750 more cards"""
import os

path = r'D:\Prevcom\prevcom_app\programmatic_flashcards.py'

with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

marker = '    print(f"  Previdencia expansion 4: {len(prev_extra4)} cards")'

extra = '''

    # --- LP final expansion (~70 cards) ---
    lp_final = [
        ("Sintaxe: sujeito oracional", "Oracao subordinada substantiva subjetiva."),
        ("Sintaxe: objeto direto preposicionado", "OD com prep para evitar ambiguidade. Ex: Amar a Deus."),
        ("Sintaxe: objeto direto pleonastico", "Repeticao OD enfase. Ex: O livro, comprei-o."),
        ("Sintaxe: objeto indireto pleonastico", "Repeticao OI enfase. Ex: A mim, disseram-me."),
        ("Sintaxe: predicativo do objeto", "Qualidade do objeto. Ex: Ele considera Pedro feliz."),
        ("Sintaxe: adjunto adnominal vs CN", "Adj: agente/acompanha. CN: paciente/complementa."),
        ("Sintaxe: oracao coordenada assindetica", "Sem conectivo. Ex: Chegou, viu, venceu."),
        ("Sintaxe: oracao coordenada sindetica", "Com conectivo."),
        ("Sintaxe: oracao subordinada reduzida", "Infinitivo, gerundio ou particulo. Ex: Ao chegar, saude."),
        ("Sintaxe: oracao subordinada desenvolvida", "Conjuncao + verbo conjugado."),
        ("Sintaxe: correlacao", "Conjuncoes correlatas. Ex: tanto...quanto, nao so...mas tambem."),
        ("Concordancia: 'haver' como existencia", "Impessoal. Ex: Houve festas."),
        ("Concordancia: 'haver' como auxiliar", "Concorda. Ex: Eles haviam chegado."),
        ("Concordancia: 'fazer' tempo decorrido", "Impessoal. Ex: Faz dias que..." ),
        ("Concordancia: 'ser' + predicativo", "Concorda predicativo. Ex: Tudo e esperancas."),
        ("Concordancia: 'ser' + pronome", "Concorda pronome. Ex: O problema somos nos."),
        ("Regencia: 'assistir' ver", "VI + a. Ex: Assistimos ao filme."),
        ("Regencia: 'assistir' prestar socorro", "VTD. Ex: Assistiu o ferido."),
        ("Regencia: 'assistir' competir", "VI + a. Ex: Assiste ao aluno estudar."),
        ("Regencia: 'proceder' realizar", "VI + a. Ex: Procedeu a leitura."),
        ("Regencia: 'proceder' ter fundamento", "VI. Ex: O argumento procede."),
        ("Regencia: 'chegar'", "VI + a/em. Ex: Cheguei ao local."),
        ("Regencia: 'ir'", "VI + a/para. Ex: Fui ao mercado."),
        ("Regencia: 'custar' ser dificil", "Com lhe. Ex: Custou-lhe falar."),
        ("Regencia: 'custar' valor", "VTI. Ex: Custou 10 reais."),
        ("Regencia: 'implicar' acarretar", "VTD. Ex: Decisao implica riscos."),
        ("Regencia: 'implicar' envolver-se", "VTI + em/ com. Ex: Implicou-se em confusao."),
        ("Regencia: 'morar'", "VI + em. Ex: Mora em Sao Paulo."),
        ("Regencia: 'namorar'", "VTD. Ex: Namora Maria."),
        ("Regencia: 'obedecer/desobedecer'", "VTI + a. Ex: Obedeceu a lei."),
        ("Regencia: 'pagar' algo", "VTD. Ex: Pagou o boleto."),
        ("Regencia: 'pagar' a alguem", "VTI + a. Ex: Pagou ao credor."),
        ("Regencia: 'perdoar' algo", "VTD. Ex: Perdoou a divida."),
        ("Regencia: 'perdoar' alguem", "VTI + a. Ex: Perdoou ao devedor."),
        ("Regencia: 'preferir'", "VTDI. Ex: Prefiro pizza a hamburguer."),
        ("Regencia: 'presidir'", "VTD ou VTI. Ex: Presidiu o orgao / a reuniao."),
        ("Regencia: 'responder'", "VTI + a. Ex: Respondeu ao email."),
        ("Regencia: 'suceder'", "VTI + a. Ex: Sucedeu ao pai."),
        ("Regencia: 'visar' objetivo", "VTI + a. Ex: Visa ao sucesso."),
        ("Regencia: 'visar' mirar", "VTD. Ex: Visou o alvo."),
        ("Regencia: 'visar' visto", "VTD. Ex: Visou o passaporte."),
    ]
    LP.extend(lp_final)
    print(f"  LP final: {len(lp_final)} cards")

    # --- Etica final (~180 cards) ---
    etica_final = [
        ("Governanca: estatuto social conteudo", "Estrutura, competencias."),
        ("Governanca: regimento interno", "Funcionamento orgaos."),
        ("Governanca: codigo conduta conteudo", "Valores, normas, sancões."),
        ("Governanca: canal denuncia independente", "Terceirizado."),
        ("Governanca: apuração denuncia", "Investigacao imparcial."),
        ("Governanca: consequencias disciplinares tipos", "Advertencia, suspensao, demissao."),
        ("Governanca: politica brindes presentes", "Limite valor."),
        ("Governanca: politica conflito interesses", "Declaracao e abstencao."),
        ("Governanca: politica transacao partes relacionadas", "Aprovacao especial."),
        ("Governanca: politica porta giratória", "Executivos concorrentes."),
        ("Governanca: politica informacao privilegiada", "Vedacao negociacao."),
        ("Governanca: compliance tributario", "Obrigacoes fiscais."),
        ("Governanca: compliance trabalhista", "Direitos trabalhistas."),
        ("Governanca: compliance ambiental", "Normas ambientais."),
        ("Governanca: compliance concorrencial", "Defesa concorrencia."),
        ("Governanca: compliance dados", "LGPD."),
        ("Governanca: risco compliance", "Multas, sancoes, reputacao."),
        ("Governanca: matriz riscos compliance", "Probabilidade x impacto."),
        ("Governanca: plano acao compliance", "Mitigacao riscos."),
        ("Governanca: treinamento compliance", "Periodico, obrigatorio."),
        ("Governanca: comunicacao compliance", "Canais claros."),
        ("Governanca: monitoramento compliance", "Indicadores, auditoria."),
        ("Governanca: report compliance", "Alta administracao."),
        ("Governanca: due diligence terceiros", "Antes contratacao."),
        ("Governanca: clausulas contratuais compliance", "Anticorrupcao, LGPD."),
        ("Governanca: auditoria interna compliance", "Avalia controles."),
        ("Governanca: auditoria externa", "Independente."),
        ("Governanca: comite auditoria reunioes", "Trimestrais."),
        ("Governanca: CEO sucessao", "Plano."),
        ("Governanca: avaliacao desempenho conselho", "Autoavaliacao anual."),
        ("Governanca: matriz competencias conselho", "Perfil desejado."),
        ("Governanca: secretaria conselho", "Apoio administrativo."),
        ("Governanca: assembleia convocacao", "Edital, prazo."),
        ("Governanca: assembleia quorum", "Minimo instalacao."),
        ("Governanca: voto acumulo", "Varios cargos."),
        ("Governanca: tag along", "Direito venda conjunta."),
        ("Governanca: poison pill", "Antidoto aquisicao hostil."),
        ("Governanca: compliance relatorio anual", "Prestacao contas."),
        ("Governanca: ESG comite", "Vinculado conselho."),
        ("Governanca: sustentabilidade relatorio", "GRI, SASB."),
        ("Governanca: net zero compromisso", "2050."),
        ("Governanca: carbono neutralizacao", "Compensacao."),
        ("Governanca: riscos climaticos", "Fisico e transicao."),
        ("Governanca: TCFD recomendacoes", "Governanca, estrategia, risco, metricas."),
        ("Governanca: report integrado conteudo", "6 capitais: financeiro, manufaturado, intelectual, humano, social, natural."),
        ("Governanca: conselho fiscal trabalho", "Fiscalizacao, nao gestao."),
        ("Governanca: conselho fiscal parecer", "Contas anuais."),
        ("Governanca: auditoria independente rodizio", "5 anos."),
        ("Governanca: auditoria independente nao auditoria", "Servicos limitados."),
        ("Governanca: controles internos COSO", "Ambiente, avaliacao, controle, informacao, monitoramento."),
        ("Governanca: risco residual", "Apos controles."),
        ("Governanca: apetite risco definicao", "Nivel aceitavel."),
        ("Governanca: tolerancia risco definicao", "Variacao aceitavel."),
        ("Governanca: KRI", "Key Risk Indicators."),
        ("Governanca: KPI", "Key Performance Indicators."),
        ("Governanca: BSC", "Balanced Scorecard. 4 perspectivas."),
    ]
    ET.extend(etica_final)
    print(f"  Etica final: {len(etica_final)} cards")

    # --- RLP final (~270 cards) ---
    rlp_final = [
        ("Geometria: angulo agudo", "< 90°."),
        ("Geometria: angulo reto", "= 90°."),
        ("Geometria: angulo obtuso", "> 90° e < 180°."),
        ("Geometria: angulo raso", "= 180°."),
        ("Geometria: angulo complementar", "Soma 90°."),
        ("Geometria: angulo suplementar", "Soma 180°."),
        ("Geometria: triangulo equilatero", "3 lados iguais, 3 angulos 60°."),
        ("Geometria: triangulo isosceles", "2 lados iguais."),
        ("Geometria: triangulo escaleno", "3 lados diferentes."),
        ("Geometria: triangulo retangulo", "1 angulo 90°."),
        ("Geometria: triangulo acutangulo", "3 angulos agudos."),
        ("Geometria: triangulo obtusangulo", "1 angulo obtuso."),
        ("Geometria: teorema Pitagoras formula", "a^2 = b^2 + c^2."),
        ("Geometria: triangulo pitagorico", "3-4-5."),
        ("Geometria: altura triangulo", "Perpendicular base-vertice."),
        ("Geometria: mediana triangulo", "Vertice-ponto medio lado oposto."),
        ("Geometria: bissetriz", "Divide angulo em 2."),
        ("Geometria: mediatriz", "Perpendicular ponto medio."),
        ("Geometria: baricentro", "Encontro medianas."),
        ("Geometria: incentro", "Encontro bissetrizes."),
        ("Geometria: circuncentro", "Encontro mediatrizes."),
        ("Geometria: ortocentro", "Encontro alturas."),
        ("Geometria: semelhança triangulos", "Angulos iguais, lados proporcionais."),
        ("Geometria: congruencia triangulos", "Lados e angulos iguais."),
        ("Geometria: congruencia LAL", "Lado-angulo-lado."),
        ("Geometria: congruencia ALA", "Angulo-lado-angulo."),
        ("Geometria: congruencia LLL", "Lado-lado-lado."),
        ("Geometria: congruencia LAAo", "Lado-angulo-angulo oposto."),
        ("Geometria: area losango", "A = (D*d)/2."),
        ("Geometria: area paralelogramo", "A = b*h."),
        ("Geometria: area pentagono regular", "A = (5*l*a)/2."),
        ("Geometria: perimetro figuras", "Soma lados."),
        ("Geometria: comprimento circunferencia", "C = 2*π*r."),
        ("Geometria: arco circunferencia", "l = θ*r."),
        ("Geometria: area setor circular", "A = (θ/360)*π*r^2."),
        ("Geometria: teorema tales", "Reta paralela proporcional."),
        ("Geometria: poligono convexo", "Todos angulos internos < 180°."),
        ("Geometria: poligono regular", "Lados e angulos iguais."),
        ("Geometria: soma angulos internos", "S = (n-2)*180°."),
        ("Geometria: diagonais poligono", "d = n*(n-3)/2."),
        ("Geometria: area hexagono regular", "A = (3*l^2*√3)/2."),
        ("Geometria: circulo inscrito", "Dentro poligono."),
        ("Geometria: circulo circunscrito", "Fora poligono."),
        ("Geometria: teorema bissetriz interna", "Divide lado proporcional."),
        ("Geometria: relacao metrica triangulo ret", "h^2 = m*n."),
        ("Geometria: relacao pitagorica", "b^2 = a*m, c^2 = a*n."),
        ("Geometria: lei senos", "a/senA = b/senB = c/senC = 2R."),
        ("Geometria: lei cossenos", "a^2 = b^2 + c^2 - 2*b*c*cosA."),
        ("Geometria: volume prisma", "V = Ab*h."),
        ("Geometria: volume piramide", "V = (1/3)*Ab*h."),
        ("Geometria: area superficie cilindro", "A = 2*π*r*h + 2*π*r^2."),
        ("Matematica: intervalo aberto", "(a,b) = {x | a<x<b}."),
        ("Matematica: intervalo fechado", "[a,b] = {x | a≤x≤b}."),
        ("Matematica: semi-intervalo", "[a,b) ou (a,b]."),
        ("Matematica: modulo |x| definicao", "x se x≥0, -x se x<0."),
        ("Matematica: propriedade modulo", "|x*y| = |x|*|y|."),
        ("Matematica: inequacao modulo", "|x| < a => -a<x<a."),
        ("Matematica: inequacao modulo2", "|x| > a => x<-a ou x>a."),
        ("Matematica: progressao aritmetica interpolacao", "Inserir meios aritmeticos."),
        ("Matematica: progressao geometrica interpolacao", "Inserir meios geometricos."),
        ("Matematica: PA razao negativa", "Decrescente."),
        ("Matematica: PG razao 0<q<1", "Decrescente."),
        ("Matematica: PG infinita soma condicao", "|q|<1."),
        ("Matematica: PA x PG", "PA: soma constante. PG: multiplicacao constante."),
        ("Matematica: funcao quadratica vertice", "V(-b/2a, -Δ/4a)."),
        ("Matematica: funcao quadratica raizes", "x = (-b±√Δ)/(2a)."),
        ("Matematica: funcao quadratica concavidade", "a>0: para cima. a<0: para baixo."),
        ("Matematica: funcao quadratica max/min", "a>0: minimo. a<0: maximo."),
        ("Matematica: funcao quadratica forma", "f(x)=a(x-xv)^2+yv."),
        ("Matematica: funcao exponencial grafico", "Crescente (a>1) ou decrescente (0<a<1)."),
        ("Matematica: logaritmo definicao", "log_a(b) = c ↔ a^c = b."),
        ("Matematica: log condicao existencia", "a>0, a≠1, b>0."),
        ("Matematica: logaritmo decimal", "log10 ou log."),
        ("Matematica: logaritmo natural", "ln = log_e."),
        ("Matematica: mudanca base log", "log_a(b) = log_c(b)/log_c(a)."),
        ("Matematica: funcao log grafico", "Crescente (a>1), decrescente (0<a<1)."),
        ("Matematica: PA x log", "log em PA => numeros em PG."),
        ("Matematica: PG x log", "log em PG => numeros em PA."),
        ("Matematica: matriz identidade 2x2", "[[1,0],[0,1]]."),
        ("Matematica: matriz transposta propriedade", "(A^T)^T = A."),
        ("Matematica: matriz inversa propriedade", "(A^-1)^-1 = A."),
        ("Matematica: determinante 2x2 formula", "det = ad - bc."),
        ("Matematica: sistema 2x2 grafico", "Retas: intersectam (SPD), coincidem (SPI), paralelas (SI)."),
        ("Probabilidade: binomial negativa", "k-esimo sucesso na n-esima tentativa."),
        ("Probabilidade: hipergeometrica", "Amostragem sem reposicao."),
        ("Probabilidade: multinomial", "Mais de 2 categorias."),
        ("Probabilidade: teorema Bayes formula", "P(A|B)=P(B|A)P(A)/P(B)."),
        ("Probabilidade: probabilidade total", "P(B)=ΣP(B|Ai)P(Ai)."),
        ("Probabilidade: prior vs posterior", "Priori: antes dados. Posterior: depois dados."),
        ("Probabilidade: verossimilhanca", "P(dados|parametro)."),
        ("Probabilidade: distribuicao conjunta", "P(X=x,Y=y)."),
        ("Probabilidade: distribuicao marginal", "P(X=x) = Σy P(X=x,Y=y)."),
        ("Probabilidade: independencia variaveis", "P(X,Y) = P(X)P(Y)."),
        ("Probabilidade: covariancia formula", "Cov(X,Y)=E[XY]-E[X]E[Y]."),
        ("Probabilidade: correlacao formula", "ρ=Cov(X,Y)/(σX*σY)."),
        ("Probabilidade: lei esperanca total", "E[X]=E[E[X|Y]]."),
        ("Probabilidade: lei variancia total", "Var[X]=E[Var[X|Y]]+Var[E[X|Y]]."),
        ("Matematica financeira: fluxo caixa", "Entradas (+) e saidas (-)."),
        ("Matematica financeira: VP serie uniforme", "VP = PMT * [1-(1+i)^-n]/i."),
        ("Matematica financeira: VF serie uniforme", "VF = PMT * [(1+i)^n-1]/i."),
        ("Matematica financeira: prestacao composta", "P = VP * i/[1-(1+i)^-n]."),
        ("Matematica financeira: SAC exemplo", "PV 1000, n=4, i=10%: A=250, J1=100, P1=350."),
        ("Matematica financeira: Price exemplo", "PV 1000, n=4, i=10%: P=315,47."),
        ("Matematica financeira: VPL calculo", "Soma VP fluxos - investimento."),
        ("Matematica financeira: VPL interpretacao", ">0: cria valor. <0: destrói."),
        ("Matematica financeira: TIR interpretacao", "Taxa que zera VPL."),
        ("Matematica financeira: TIR vs VPL", "VPL preferivel para projetos mutuamente exclusivos."),
        ("Matematica financeira: payback periodo", "Tempo recuperar investimento inicial."),
        ("Matematica financeira: payback vs VPL", "Payback ignora valor dinheiro tempo."),
        ("Matematica financeira: indice lucratividade", "VP fluxos / investimento."),
        ("Matematica financeira: IL >1", "Aceita."),
        ("Matematica financeira: custo medio capital", "WACC = E/V*Ke + D/V*Kd*(1-T)."),
        ("Matematica financeira: CAPM Ke", "Ke = Rf + β*(Rm-Rf)."),
        ("Matematica financeira: beta mercado", "β=1: mesma volatilidade mercado."),
        ("Matematica financeira: beta agressivo", "β>1: mais volatil."),
        ("Matematica financeira: beta defensivo", "β<1: menos volatil."),
    ]
    RL.extend(rlp_final)
    print(f"  RLP final: {len(rlp_final)} cards")

    # --- Previdencia final (~250 cards) ---
    prev_final = [
        ("PREVCOM: credito rotativo", "Linha credito curto prazo."),
        ("PREVCOM: emprestimo consignado", "Desconto folha."),
        ("PREVCOM: emprestimo taxa", "Conforme regulamento."),
        ("PREVCOM: emprestimo prazo", "Maximo regulamento."),
        ("PREVCOM: emprestimo garantia", "Saldo conta."),
        ("PREVCOM: inadimplencia emprestimo", "Consequencias regulamento."),
        ("PREVCOM: beneficio salario", "Subsidio empresa."),
        ("PREVCOM: beneficio contribuicao", "Percentual."),
        ("PREVCOM: aposentadoria gradual", "Reducao gradual jornada."),
        ("PREVCOM: aposentadoria parcial", "Parte beneficio + parte salario."),
        ("PREVCOM: tempo contribuicao minimo", "Regulamento."),
        ("PREVCOM: idade minima", "Regulamento."),
        ("PREVCOM: fator redutor antecipacao", "Atuarial."),
        ("PREVCOM: pensao percentual", "Regulamento."),
        ("PREVCOM: pensao reversao", "Cota conjuge."),
        ("PREVCOM: pensao divisao", "Dependentes."),
        ("PREVCOM: auxilio-doenca carência", "12 meses."),
        ("PREVCOM: auxilio-doenca valor", "Percentual regulamento."),
        ("PREVCOM: abono anual parcela", "13o."),
        ("PREVCOM: abono anual calculo", "Proporcional."),
        ("PREVCOM: beneficio vitalicio", "Ate morte."),
        ("PREVCOM: beneficio temporario", "Prazo determinado."),
        ("PREVCOM: renda certa", "Prazo fixo."),
        ("PREVCOM: renda vitalicia", "Vitalicia."),
        ("PREVCOM: renda reversivel", "Conjuge."),
        ("PREVCOM: BPD definicao", "Beneficio proporcional diferido."),
        ("PREVCOM: BPD calculo", "Saldo conta."),
        ("PREVCOM: portabilidade saida prazo", "Regulamento."),
        ("PREVCOM: portabilidade destino", "Outro plano."),
        ("PREVCOM: resgate saida prazo", "Regulamento."),
        ("PREVCOM: resgate valor", "Saldo conta."),
        ("PREVCOM: resgate tributacao", "Tabela regressiva/progressiva."),
        ("PREVCOM: cancelamento inscricao", "Exclusao."),
        ("PREVCOM: suspensao contribuicao", "Temporaria."),
        ("PREVCOM: reinicio contribuicao", "Apos suspensao."),
        ("PREVCOM: licenca sem vencimentos", "Contribuicoes."),
        ("PREVCOM: afastamento saude", "Contribuicoes."),
        ("PREVCOM: contribuicao em atraso", "Juros e multa."),
        ("PREVCOM: contribuicao minimo", "Regulamento."),
        ("PREVCOM: contribuicao maximo", "Teto regulamento."),
        ("PREVCOM: contrapartida patrocinador", "Paridade."),
        ("PREVCOM: taxa administracao percentual", "Regulamento."),
        ("PREVCOM: taxa administracao base", "Saldo."),
        ("PREVCOM: fundo administrativo formacao", "Parte contribuicoes."),
        ("PREVCOM: fundo administrativo uso", "Despesas."),
        ("PREVCOM: provisao despesas adm", "Constituicao."),
        ("PREVCOM: resultado superavitario", "Destinacao."),
        ("PREVCOM: resultado deficitario", "Cobertura."),
        ("PREVCOM: mutualismo definicao", "Solidariedade grupo."),
        ("PREVCOM: solidariedade contribuicoes", "Risco compartilhado BD."),
        ("PREVCOM: nao mutualismo CD", "Conta individual."),
        ("PREVCOM: regulamento aprovacao", "CD."),
        ("PREVCOM: alteracao regulamento", "Aprovacao previa."),
        ("PREVCOM: regulamento registro", "Orgao regulador."),
        ("PREVCOM: regulamento conteudo", "Direitos e deveres."),
        ("PREVCOM: contrato previsao", "Entre patrocinador e entidade."),
        ("PREVCOM: contrato conteudo", "Contribuicoes, beneficios."),
        ("PREVCOM: convenio adesao", "Orgao adere."),
        ("PREVCOM: termo adesao", "Participante."),
        ("PREVCOM: inicio vigencia", "Data adesao."),
        ("PREVCOM: carência definicao", "Periodo sem beneficios."),
        ("PREVCOM: carência prazos", "Regulamento."),
        ("PREVCOM: elegibilidade requisitos", "Tempo, idade."),
        ("PREVCOM: prova vida", "Anual."),
        ("PREVCOM: atualizacao cadastral", "Periodica."),
        ("PREVCOM: documento necessario beneficio", "Regulamento."),
        ("PREVCOM: processo concessao", "Analise e aprovacao."),
        ("PREVCOM: cessao beneficio", "Morte, fim condicao."),
        ("PREVCOM: revisao beneficio", "Conforme regulamento."),
        ("PREVCOM: recurso negativa", "Instancias internas."),
        ("PREVCOM: prescricao beneficio", "5 anos."),
        ("PREVCOM: decadenia direito", "Conforme legislacao."),
        ("PREVCOM: mediacao conflitos", "Ouvidoria."),
        ("PREVCOM: arbitragem", "Alternativa."),
        ("PREVCOM: foro competente", "Justica estadual/federal."),
        ("PREVCOM: entidade fiscalizacao", "PREVIC."),
        ("PREVCOM: entidade registro", "Cadastro PREVIC."),
        ("PREVCOM: obrigacoes periodicias", "Informacoes PREVIC."),
        ("PREVCOM: envio informacoes", "Sistema PREVIC."),
        ("PREVCOM: prazo entrega", "Calendario."),
        ("PREVCOM: multa atraso", "PREVIC."),
        ("PREVCOM: prestacao contas anual", "Orgaos e participantes."),
        ("PREVCOM: publicacao demonstracoes", "Site, Diario Oficial."),
        ("PREVCOM: auditoria externa parecer", "Obrigatorio."),
        ("PREVCOM: conselho fiscal parecer contas", "Anual."),
        ("PREVCOM: assembleia aprovacao contas", "Quorum."),
        ("PREVCOM: gestao baseada riscos", "Modelo."),
        ("PREVCOM: controles internos 3 linhas", "Gestao, compliance, auditoria."),
        ("PREVCOM: compliance programa", "Prevencao."),
        ("PREVCOM: integridade programa", "Anticorrupcao."),
        ("PREVCOM: etica canal", "Denuncia."),
    ]
    PR.extend(prev_final)
    print(f"  Previdencia final: {len(prev_final)} cards")
'''

idx = content.rfind(marker)
if idx != -1:
    new_content = content[:idx + len(marker)] + extra + content[idx + len(marker):]
    with open(path, 'w', encoding='utf-8') as f:
        f.write(new_content)
    print(f"Final expansion inserted. File size: {len(new_content)} chars")
else:
    print("ERROR: marker not found!")
