"""Builds programmatic_flashcards.py - part 6: TI section"""
import os

path = r'D:\Prevcom\prevcom_app\programmatic_flashcards.py'

def write(s):
    with open(path, 'a', encoding='utf-8') as f:
        f.write(s + '\n')

write('''    # ================================================================
    # 5. CONHECIMENTOS ESPECIFICOS EM TECNOLOGIA
    # ================================================================

    # --- Linguagens programacao ---
    python_basico = [
        ("Python: tipagem", "Fraca, dinamica, duck typing."),
        ("Python: list", "Mutavel, ordenada, indexada."),
        ("Python: tuple", "Imutavel, ordenada."),
        ("Python: dict", "Chave-valor. Hash table."),
        ("Python: set", "Nao ordenado, unico. Hash."),
        ("Python: for", "Itera sobre iteravel."),
        ("Python: while", "Repete enquanto condicao."),
        ("Python: if/elif/else", "Desvio condicional."),
        ("Python: def", "Define funcao."),
        ("Python: lambda", "Funcao anonima inline."),
        ("Python: list comprehension", "[expr for x in lista]."),
        ("Python: generator", "yield. Lazy."),
        ("Python: decorator", "@. Modifica funcao."),
        ("Python: context manager", "with. __enter__/__exit__."),
        ("Python: exception", "try/except/finally/raise."),
        ("Python: OOP class", "self, __init__, heranca."),
        ("Python: MRO", "Method Resolution Order. C3 linearizacao."),
        ("Python: GIL", "Global Interpreter Lock. Threads CPU."),
        ("Python: async/await", "Corrotinas assincronas."),
        ("Python: pytest", "Testes. fixture, assert."),
    ]
    TI.extend(python_basico)

    java_basico = [
        ("Java: JVM", "Maquina virtual. Portabilidade."),
        ("Java: JRE", "Runtime. JVM + bibliotecas."),
        ("Java: JDK", "Desenvolvimento. JRE + tools."),
        ("Java: OOP class", "public/private, heranca extends."),
        ("Java: interface", "Contrato. implements."),
        ("Java: abstract class", "Nao instanciavel. Metodos abstratos."),
        ("Java: static", "Nivel classe."),
        ("Java: final", "Constante/nao herda/nao sobreescreve."),
        ("Java: String immutavel", "Imutavel. Pool."),
        ("Java: StringBuilder", "Mutavel. Otimizado."),
        ("Java: ArrayList", "Lista redimensionavel."),
        ("Java: HashMap", "Chave-valor. Hash table."),
        ("Java: HashSet", "Set baseado hash."),
        ("Java: try-with-resources", "Auto close Autocloseable."),
        ("Java: lambda", "() -> {}. SAM."),
        ("Java: Stream API", "Operacoes pipeline colecoes."),
        ("Java: Optional", "Container valor ausente."),
        ("Java: generics", "<T>. Type safety."),
        ("Java: thread", "Thread/Runnable. synchronized."),
        ("Java: Spring Boot", "Framework web. Auto-config."),
    ]
    TI.extend(java_basico)

    js_basico = [
        ("JS: tipagem", "Fraca, dinamica."),
        ("JS: var/let/const", "Escopo funcao/bloco/constante."),
        ("JS: closure", "Funcao + escopo lexico."),
        ("JS: prototype", "Heranca prototipal."),
        ("JS: promises", "Async. then/catch."),
        ("JS: async/await", "Sintatica sobre promises."),
        ("JS: ES6 modules", "import/export."),
        ("JS: arrow function", "() => {}. Lexico this."),
        ("JS: destructuring", "Extrai valores arrays/objetos."),
        ("JS: spread/rest", "... espalha/agrupa."),
        ("JS: React component", "Props, state, lifecycle."),
        ("JS: hooks", "useState, useEffect, useMemo."),
        ("JS: Node.js", "Runtime JS server-side."),
        ("JS: npm/yarn", "Gerenciadores pacotes."),
        ("JS: event loop", "Single thread. Callback queue."),
    ]
    TI.extend(js_basico)

    sql = [
        ("SQL: SELECT", "SELECT col FROM table WHERE."),
        ("SQL: JOIN INNER", "Apenas correspondencias."),
        ("SQL: JOIN LEFT", "Todas esquerda + correspondencias."),
        ("SQL: JOIN RIGHT", "Todas direita + correspondencias."),
        ("SQL: JOIN FULL", "Todas ambos lados."),
        ("SQL: GROUP BY", "Agrupa registros. Usa com agregacao."),
        ("SQL: HAVING", "WHERE para grupos (apos GROUP BY)."),
        ("SQL: COUNT(*)", "Numero linhas."),
        ("SQL: SUM", "Soma valores."),
        ("SQL: AVG", "Media valores."),
        ("SQL: MAX/MIN", "Maior/menor valor."),
        ("SQL: DISTINCT", "Remove duplicatas."),
        ("SQL: ORDER BY", "Ordena ASC/DESC."),
        ("SQL: INSERT", "INSERT INTO table VALUES."),
        ("SQL: UPDATE", "UPDATE table SET col=val WHERE."),
        ("SQL: DELETE", "DELETE FROM table WHERE."),
        ("SQL: CREATE TABLE", "Define schema tabela."),
        ("SQL: ALTER TABLE", "ADD/DROP/MODIFY coluna."),
        ("SQL: INDEX", "Acelera busca."),
        ("SQL: UNIQUE", "Valor unico coluna."),
        ("SQL: PRIMARY KEY", "Unico + NOT NULL."),
        ("SQL: FOREIGN KEY", "Referencia outra tabela."),
        ("SQL: NOT NULL", "Obriga valor."),
        ("SQL: CHECK", "Valida valor coluna."),
        ("SQL: ACID", "Atomicidade, Consistencia, Isolamento, Durabilidade."),
        ("SQL: transaction", "BEGIN, COMMIT, ROLLBACK."),
        ("SQL: NORMALIZACAO 1FN", "Atomico. Sem grupos repetitivos."),
        ("SQL: NORMALIZACAO 2FN", "1FN + dep. total chave primaria."),
        ("SQL: NORMALIZACAO 3FN", "2FN + dep. transitiva."),
        ("SQL: view", "Tabela virtual."),
        ("SQL: stored procedure", "Bloco SQL armazenado."),
        ("SQL: trigger", "Executa automaticamente evento."),
    ]
    TI.extend(sql)

    nosql = [
        ("NoSQL: document (MongoDB)", "JSON/BSON. Flexivel."),
        ("NoSQL: key-value (Redis)", "Simples, rapido, cache."),
        ("NoSQL: column (Cassandra)", "Colunas largas. Escalabilidade."),
        ("NoSQL: graph (Neo4j)", "Nos+arestas. Relacionamentos."),
        ("MongoDB: collection", "Conjunto documentos."),
        ("MongoDB: document", "JSON-like. _id unico."),
        ("MongoDB: aggregation", "Pipeline processamento."),
        ("Redis: STRING", "Valor string."),
        ("Redis: LIST", "Lista ordenada."),
        ("Redis: SET", "Conjunto unico."),
        ("Redis: HASH", "Mapa campo-valor."),
        ("Redis: ZSET", "Set ordenado score."),
        ("Cassandra: partition key", "Distribui dados nos."),
        ("Cassandra: clustering key", "Ordena dentro particao."),
        ("Cassandra: CQL", "SQL-like, mas sem JOIN."),
        ("Neo4j: node", "Entidade."),
        ("Neo4j: relationship", "Conexao nos."),
        ("Neo4j: property", "Atributo no/relacionamento."),
        ("Neo4j: label", "Tipo no."),
    ]
    TI.extend(nosql)

    redes = [
        ("TCP/IP: camadas", "Aplicacao, Transporte, Rede, Enlace."),
        ("OSI: camadas", "Aplicacao, Apresentacao, Sessao, Transporte, Rede, Enlace, Fisica."),
        ("TCP: orientado conexao", "3-way handshake. Confiavel."),
        ("UDP: sem conexao", "Rapido, nao confiavel."),
        ("IP: roteamento", "Endereco destino."),
        ("DNS", "Traduz dominio <-> IP."),
        ("HTTP/HTTPS", "Protocolo web. 80/443."),
        ("HTTP metodos", "GET, POST, PUT, DELETE, PATCH."),
        ("HTTP status", "1xx info, 2xx sucesso, 3xx redirecionamento, 4xx cliente, 5xx servidor."),
        ("REST", "Recursos, metodos HTTP, stateless."),
        ("HTTP/2", "Multiplex, compressao headers, server push."),
        ("HTTP/3", "QUIC/UDP. Menor latencia."),
        ("WebSocket", "Full-duplex sobre TCP."),
        ("FTP", "Transferencia arquivos. 21 controle, 20 dados."),
        ("SSH", "Acesso remoto seguro. 22."),
        ("SMTP", "Envio email. 25."),
        ("POP3/IMAP", "Recebimento email. 110/143."),
        ("TLS/SSL", "Criptografia transporte. Handshake."),
        ("VPN", "Canal seguro sobre internet."),
        ("Proxy reverso", "Nginx, HAProxy. Balanceamento, cache."),
    ]
    TI.extend(redes)

    seguranca = [
        ("Criptografia simetrica", "Mesma chave cifra/decifra. AES, DES."),
        ("Criptografia assimetrica", "Par chaves. RSA, ECC."),
        ("Hash", "Funcao unidirecional. SHA-256, MD5."),
        ("Assinatura digital", "Hash + chave privada."),
        ("Certificado digital", "ICP-Brasil. Chave publica + identidade."),
        ("PKI", "Infraestrutura chave publica. AC, AR."),
        ("Firewall", "Filtra trafego regras."),
        ("IDS/IPS", "Detecta/previne intrusao."),
        ("WAF", "Firewall aplicacao web."),
        ("OWASP Top 10", "Principais vulnerabilidades web."),
        ("SQL Injection", "Injecao SQL query."),
        ("XSS", "Injecao script no navegador."),
        ("CSRF", "Requisicao falsa site autenticado."),
        ("Autenticacao: 2FA", "Dois fatores."),
        ("Autenticacao: OAuth2", "Delegada. Tokens."),
        ("Autenticacao: JWT", "JSON Web Token. Stateless."),
        ("Autenticacao: SAML", "XML. SSO corporativo."),
        ("Autenticacao: LDAP", "Diretorio usuarios."),
        ("Autenticacao: OpenID Connect", "Sobre OAuth2. Identity."),
        ("Autenticacao: SSO", "Login unico multiplos sistemas."),
        ("RBAC", "Controle acesso baseado papeis."),
        ("ABAC", "Controle acesso baseado atributos."),
        ("Lei Carolina Dieckmann", "Crimes informaticos. 12.737/2012."),
        ("Marco Civil Internet", "Direitos e deveres internet. 12.965/2014."),
        ("LGPD na TI", "Dados pessoais. Seguranca, privacidade."),
    ]
    TI.extend(seguranca)

    cloud = [
        ("IaaS", "Infraestrutura como servico. AWS EC2, Azure VM."),
        ("PaaS", "Plataforma como servico. Heroku, App Engine."),
        ("SaaS", "Software como servico. Office 365, Salesforce."),
        ("FaaS", "Funcao como servico. Lambda, Cloud Functions."),
        ("Publica", "Multitenancy. AWS, Azure, GCP."),
        ("Privada", "Dedicada empresa. OpenStack, VMware."),
        ("Hibrida", "Publica + privada + on-premise."),
        ("Multi-cloud", "Multiplos provedores publicos."),
        ("AWS EC2", "Maquina virtual."),
        ("AWS S3", "Armazenamento objetos."),
        ("AWS RDS", "Banco relacional gerenciado."),
        ("AWS Lambda", "Serverless."),
        ("AWS VPC", "Rede virtual isolada."),
        ("AWS CloudFront", "CDN."),
        ("AWS ELB", "Balanceamento carga."),
        ("AWS Auto Scaling", "Escalabilidade automatica."),
        ("AWS CloudWatch", "Monitoramento e logs."),
        ("AWS IAM", "Identidade e acesso."),
        ("AWS Route 53", "DNS gerenciado."),
        ("Azure VM", "Maquina virtual Azure."),
        ("Azure Blob", "Armazenamento objetos."),
        ("Azure SQL Database", "SQL gerenciado."),
        ("Azure Functions", "Serverless."),
        ("Azure AD", "Identity."),
        ("GCP Compute Engine", "VM Google."),
        ("GCP Cloud Storage", "Objetos."),
        ("GCP Cloud SQL", "Banco gerenciado."),
        ("GCP Cloud Functions", "Serverless."),
        ("GCP BigQuery", "Analytics SQL."),
        ("GCP Kubernetes (GKE)", "K8s gerenciado."),
    ]
    TI.extend(cloud)

    devops = [
        ("CI/CD", "Integracao/Entrega continua."),
        ("Git: commit", "Snapshot mudancas."),
        ("Git: branch", "Linha independente desenvolvimento."),
        ("Git: merge", "Une branches."),
        ("Git: rebase", "Reaplica commits outra base."),
        ("Git: pull request", "Solicitacao merge revisao."),
        ("Git: stash", "Salva mudancas temporarias."),
        ("Docker: image", "Template read-only."),
        ("Docker: container", "Instancia imagem executando."),
        ("Docker: Dockerfile", "Receita construir imagem."),
        ("Docker: Docker Compose", "Multi-container."),
        ("Docker: registry", "Repositorio imagens."),
        ("Docker: volume", "Persistencia dados."),
        ("Docker: network", "Comunicacao containers."),
        ("Kubernetes: pod", "Menor unidade. 1+ containers."),
        ("K8s: deployment", "Replicaset + rolling update."),
        ("K8s: service", "Acesso estavel pods."),
        ("K8s: ingress", "Roteamento externo."),
        ("K8s: configmap", "Configuracao chave-valor."),
        ("K8s: secret", "Dados sensiveis."),
        ("K8s: namespace", "Isolamento logico."),
        ("K8s: node", "Maquina cluster."),
        ("K8s: cluster", "Conjunto nodes."),
        ("K8s: helm", "Pacote K8s charts."),
        ("Ansible", "Automacao config. YAML, agentless."),
        ("Terraform", "IaC. Estados, providers, modules."),
        ("Jenkins", "Automacao CI/CD."),
        ("GitHub Actions", "CI/CD nuvem."),
        ("GitLab CI", "CI/CD integrado GitLab."),
        ("Prometheus", "Monitoramento, metricas."),
        ("Grafana", "Dashboards metricas."),
        ("ELK Stack", "Elasticsearch, Logstash, Kibana."),
        ("SonarQube", "Qualidade codigo, code smell, bug."),
    ]
    TI.extend(devops)

    engenharia_sw = [
        ("SDLC cascata", "Sequencial: requisitos, design, implementacao, teste, manutencao."),
        ("SDLC agil", "Iterativo, incremento, Scrum, Kanban."),
        ("Scrum: Sprint", "Timebox 1-4 semanas."),
        ("Scrum: Product Backlog", "Lista priorizada requisitos."),
        ("Scrum: Sprint Backlog", "Itens selecionados sprint."),
        ("Scrum: Daily", "Reuniao diaria 15 min."),
        ("Scrum: Review", "Demonstracao entrega."),
        ("Scrum: Retro", "Melhoria continua."),
        ("Scrum: PO", "Product Owner. Backlog."),
        ("Scrum: SM", "Scrum Master. Facilitador."),
        ("Scrum: Dev Team", "Equipe desenvolvimento."),
        ("Kanban: WIP limit", "Limita trabalho em andamento."),
        ("Kanban: pull", "Tarefa puxada quando capacidade."),
        ("Kanban: lead time", "Tempo inicio ao fim."),
        ("Kanban: cycle time", "Tempo trabalho ativo."),
        ("UML: diagrama classes", "Estrutura estatica sistema."),
        ("UML: diagrama sequencia", "Interacao temporal objetos."),
        ("UML: diagrama atividades", "Fluxo atividades processo."),
        ("UML: diagrama casos uso", "Funcionalidades atores."),
        ("UML: diagrama estados", "Ciclo vida objeto."),
        ("UML: diagrama componentes", "Modulos e dependencias."),
        ("SOLID: SRP", "Responsabilidade unica."),
        ("SOLID: OCP", "Aberto extensao, fechado modificacao."),
        ("SOLID: LSP", "Subtipo substitui tipo base."),
        ("SOLID: ISP", "Interface segregada."),
        ("SOLID: DIP", "Depende abstracoes."),
        ("Design Pattern: Singleton", "Unica instancia."),
        ("Design Pattern: Factory", "Cria objetos sem especificar classe."),
        ("Design Pattern: Observer", "Notifica mudancas."),
        ("Design Pattern: Strategy", "Algoritmos intercambiaveis."),
        ("Design Pattern: Decorator", "Adiciona comportamento."),
        ("Design Pattern: Adapter", "Converte interface."),
        ("Design Pattern: MVC", "Model, View, Controller."),
        ("TDD", "Teste primeiro, depois codigo, refatora."),
        ("BDD", "Comportamento. Given/When/Then."),
        ("DDD", "Dominio como coracao."),
        ("Clean Architecture", "Dependencia externa para dentro."),
        ("Hexagonal Architecture", "Ports and adapters."),
        ("Microservices", "Servicos independentes, autonomos, comunicacao API."),
        ("Monolith vs microservices", "Monolito simples inicio, microservices escalabilidade."),
    ]
    TI.extend(engenharia_sw)

    banco_dados_avancado = [
        ("Oracle: tablespace", "Unidade logica armazenamento."),
        ("Oracle: SGA", "System Global Area. Memoria compartilhada."),
        ("Oracle: PGA", "Program Global Area. Memoria sessao."),
        ("Oracle: redo log", "Registra mudancas recovery."),
        ("Oracle: undo", "Rollback e consistencia leitura."),
        ("Oracle: RMAN", "Backup e recovery."),
        ("Oracle: Data Guard", "Replicacao standby."),
        ("Oracle: RAC", "Real Application Cluster."),
        ("Oracle: PL/SQL", "Procedural. function, procedure, trigger."),
        ("PostgreSQL: MVCC", "Multi-version concurrency control."),
        ("PostgreSQL: WAL", "Write Ahead Log. Durabilidade."),
        ("PostgreSQL: VACUUM", "Reclama espaco."),
        ("PostgreSQL: EXPLAIN", "Plano execucao query."),
        ("PostgreSQL: partition", "Divisao tabela grande."),
        ("PostgreSQL: replication", "Streaming replication."),
        ("MySQL: InnoDB", "Engine padrao. ACID, FK."),
        ("MySQL: MyISAM", "Sem transacao. Full-text search."),
        ("MySQL: query cache", "Cache resultados (removido 8.0)."),
        ("MySQL: replication", "Master-slave, binlog."),
        ("NoSQL vs SQL quando usar", "SQL: relacoes, ACID. NoSQL: escala, schema flexivel."),
        ("Sharding", "Divisao horizontal dados."),
        ("Replicacao", "Copias dados. Leitura/alta disponibilidade."),
        ("Index: B-tree", "Balanceado. Ordenado. Range query."),
        ("Index: hash", "Igualdade. Unico valor."),
        ("Index: bitmat", "Baixa cardinalidade. Data warehouse."),
        ("Index: composto", "Multiplas colunas."),
        ("Full-text search", "Palavras texto. Inverted index."),
    ]
    TI.extend(banco_dados_avancado)

    gestao_ti = [
        ("ITIL: definicao", "Boas praticas gestao servicos TI."),
        ("ITIL: Service Strategy", "Estrategia, portfolio, financas."),
        ("ITIL: Service Design", "Desenho, nivel servico, disponibilidade."),
        ("ITIL: Service Transition", "Mudanca, ativo, configuracao."),
        ("ITIL: Service Operation", "Incidente, problema, acesso."),
        ("ITIL: Continual Service Improvement", "Melhoria continua."),
        ("COBIT: definicao", "Governanca TI. Controles."),
        ("COBIT: EDM", "Avaliar, Dirigir, Monitorar."),
        ("COBIT: APO", "Alinhar, Planejar, Organizar."),
        ("COBIT: BAI", "Construir, Adquirir, Implementar."),
        ("COBIT: DSS", "Entregar, Servir, Suportar."),
        ("COBIT: MEA", "Monitorar, Avaliar, Medir."),
        ("PMBOK: grupos processos", "Iniciacao, Planejamento, Execucao, Monitoramento, Encerramento."),
        ("PMBOK: areas conhecimento", "Escopo, Tempo, Custo, Qualidade, Recursos, Comunicacao, Risco, Aquisições, Stakeholders."),
        ("SCRUM vs PMBOK", "SCRUM: agil, flexivel. PMBOK: tradicional, preditivo."),
        ("BPM: definicao", "Gestao processos negocio. BPMN."),
        ("BPMN: elementos", "Eventos, atividades, gateways, fluxos."),
        ("BPM: ciclo", "Modelar, executar, monitorar, otimizar."),
    ]
    TI.extend(gestao_ti)

    ciencia_dados = [
        ("CRISP-DM", "Business understanding, Data understanding, Data prep, Modeling, Evaluation, Deployment."),
        ("Pandas: DataFrame", "Tabela bidimensional."),
        ("Pandas: Series", "Array rotulado."),
        ("Pandas: groupby", "Agrupa e agrega."),
        ("Pandas: merge/join", "Combina DataFrames."),
        ("NumPy: array", "Operacoes vetorizadas."),
        ("Matplotlib: plot", "Graficos 2D."),
        ("Scikit-learn: modelo", "Fit, predict, score."),
        ("Scikit-learn: regressao", "LinearRegression, Ridge, Lasso."),
        ("Scikit-learn: classificacao", "LogisticRegression, RandomForest, SVM."),
        ("Scikit-learn: cluster", "KMeans, DBSCAN, Hierarquico."),
        ("Scikit-learn: pre-processamento", "StandardScaler, MinMaxScaler."),
        ("Scikit-learn: metricas", "Accuracy, Precision, Recall, F1."),
        ("Overfitting", "Modelo decora dados. Regularizacao."),
        ("Underfitting", "Modelo simples demais. Mais features."),
        ("Cross-validation", "K-fold validacao."),
        ("Feature engineering", "Criacao/transformacao features."),
        ("Feature selection", "Seleciona mais relevantes."),
        ("PCA", "Reducao dimensionalidade."),
        ("Arvore decisao", "Nos e folhas. Interpretavel."),
        ("Random Forest", "Conjunto arvores. Bagging."),
        ("Gradient Boosting (XGBoost)", "Sequencial. Erro previo."),
        ("Neural network", "Neuronios, camadas, pesos, ativacao."),
        ("Deep learning", "Multiplas camadas. CNN, RNN, Transformer."),
        ("NLP basics", "Tokenizacao, stemming, bag-of-words, word2vec."),
        ("LLM: transformer", "Attention, encoder-decoder."),
        ("LLM: GPT", "Decoder-only. Geracao texto."),
        ("LLM: BERT", "Encoder-only. Compreensao."),
        ("RAG", "Retrieval-Augmented Generation. Busca + LLM."),
        ("Fine-tuning", "Ajuste modelo pre-treinado."),
        ("ETL", "Extract, Transform, Load."),
        ("Data warehouse", "Dados estruturados analise."),
        ("Data lake", "Dados brutos diversos formatos."),
        ("OLAP vs OLTP", "OLAP analise, OLTP transacoes."),
    ]
    TI.extend(ciencia_dados)

    sysadmin = [
        ("Linux: filesystem", "/, /home, /etc, /var, /tmp, /usr."),
        ("Linux: chmod", "rwx (4,2,1). u,g,o."),
        ("Linux: chown", "Altera owner/grupo."),
        ("Linux: ps aux", "Lista processos."),
        ("Linux: top/htop", "Monitora processos."),
        ("Linux: systemctl", "Systemd. start, stop, enable, status."),
        ("Linux: journalctl", "Logs systemd."),
        ("Linux: grep", "Busca texto."),
        ("Linux: sed", "Edicao stream."),
        ("Linux: awk", "Processamento texto."),
        ("Linux: find", "Busca arquivos."),
        ("Linux: netstat/ss", "Conexoes rede."),
        ("Linux: crontab", "Agendador tarefas."),
        ("Linux: bash script", "#!/bin/bash. Variaveis, loops, condicoes."),
        ("Windows: AD", "Active Directory. Dominio, GPO."),
        ("Windows: PowerShell", "Scripts objetos. Cmdlets."),
        ("Windows: IIS", "Servidor web Microsoft."),
        ("Windows: Event Viewer", "Logs sistema."),
        ("Windows: Task Scheduler", "Agendador tarefas."),
        ("Windows: Registry", "Configuracao hierarquica."),
        ("Windows: Group Policy", "Politicas centralizadas."),
        ("Virtualizacao: hypervisor", "Vmware ESXi, Hyper-V, KVM."),
        ("Virtualizacao: VM", "Maquina virtual. SO convidado."),
        ("Virtualizacao: container vs VM", "Container leve, kernel host. VM isolada, kernel proprio."),
        ("Storage: SAN", "Rede storage. Bloco. Fibre Channel."),
        ("Storage: NAS", "Rede storage. Arquivo. NFS, SMB."),
        ("Storage: RAID 0", "Striping. Desempenho. Sem tolerancia falha."),
        ("Storage: RAID 1", "Espelhamento. Tolerancia 1 disco."),
        ("Storage: RAID 5", "Striping+paridade. Tolerancia 1 disco."),
        ("Storage: RAID 6", "Striping+dupla paridade. Tolerancia 2 discos."),
        ("Storage: RAID 10", "RAID 1+0. Desempenho+tolerancia."),
        ("Backup: full", "Todos dados."),
        ("Backup: incremental", "Mudancas ultimo backup."),
        ("Backup: diferencial", "Mudancas ultimo full."),
        ("Backup: 3-2-1 regra", "3 copias, 2 midias, 1 offsite."),
        ("Disaster Recovery: RPO", "Perda maxima aceitavel dados."),
        ("Disaster Recovery: RTO", "Tempo maximo recuperacao."),
        ("Disaster Recovery: RPO vs RTO", "RPO perda dados, RTO tempo parado."),
        ("SLA", "Acordo nivel servico."),
        ("MTBF", "Tempo medio entre falhas."),
        ("MTTR", "Tempo medio reparo."),
    ]
    TI.extend(sysadmin)

    print(f"  Tecnologia programatico: {len(TI)} cards")
''')

print("Part 6 written (TI section)")
