"""Gerador de conteudo programatico para PREVCOM 2026
Gera 1000+ flashcards e questoes automaticamente por tema.
"""
from models import db, Questao, Flashcard
from programmatic_flashcards import gerar_flashcards_programaticamente

# ============================================================
# TEMPLATES DE FLASHCARDS POR DISCIPLINA
# ============================================================

FLASHCARDS_LP = [
    # (frente, verso)
    # -- Ortografia --
    ("Uso do 'por que' separado", "Em perguntas diretas ou indiretas. Ex: 'Por que voce foi?' / 'Nao sei por que ele foi.'"),
    ("Uso do 'porque' junto", "Em respostas ou explicacoes. Ex: 'Nao fui porque estava doente.'"),
    ("Uso do 'por que' separado com acento", "Substantivo = motivo/razao. Ex: 'Quero saber o por que disso.'"),
    ("Uso do 'porque' junto com acento", "Em perguntas ao final da frase. Ex: 'Voce nao foi por que?'"),
    ("Uso da crase: a + a", "Fusao da preposicao 'a' com artigo 'a'. Ex: 'Fui a + a reuniao = Fui a reuniao.'"),
    ("Crase antes de 'aquele'", "Obrigatoria: 'Refiro-me aquela proposta.' (a + aquela)"),
    ("Crase em locucoes adverbiais", "Obrigatoria: as vezes, as pressas, a vontade, a noite, a direita."),
    ("Crase proibida: antes de verbo", "Nunca ha crase antes de verbo. Ex: 'Comecou a estudar.'"),
    ("Crase proibida: palavras masculinas", "Nunca antes de palavras masculinas. Ex: 'Andava a cavalo.'"),
    ("Crase proibida: pronomes pessoais", "Nunca antes de pronomes. Ex: 'Entregue a ela.'"),
    # -- Acentuacao --
    ("Acentuacao: oxitonas", "Acentuam-se oxitonas terminadas em a(s), e(s), o(s), em/ens. Ex: cafe, jacare, parabens."),
    ("Acentuacao: paroxitonas", "Acentuam-se paroxitonas terminadas em i, is, us, um, uns, ao(s), ei, r, l, n, x, ps. Ex: lapis, virus, album."),
    ("Acentuacao: proparoxitonas", "Todas as proparoxitonas sao acentuadas. Ex: medico, arvore, fabrica."),
    ("Acentos diferenciais", "Ainda existem em pode/poe, tem/tem, ve/vee, por/per. Ex: 'Ele tem' vs 'Eles tem'."),
    ("Hiato", "Acentuam-se i e u tonicos quando formam hiato com vogal anterior e sao sozinhos na silaba. Ex: saude, balaustre."),
    # -- Morfologia --
    ("Substantivo: definicao", "Classe que nomeia seres, objetos, sentimentos, acoes. Ex: casa, beleza, amor, corrida."),
    ("Substantivo comum x proprio", "Comum: generico (cidade). Proprio: especifico (Sao Paulo)."),
    ("Substantivo concreto x abstrato", "Concreto: ser real (mesa). Abstrato: depende de outro ser (beleza, saudade)."),
    ("Adjetivo: definicao", "Caracteriza ou qualifica o substantivo. Ex: 'casa grande', 'funcionario eficiente'."),
    ("Locucao adjetiva", "Expressao com valor de adjetivo. Ex: 'amor de mae' (materno), 'dia de sol' (ensolarado)."),
    ("Artigo: definicao", "Determina ou indetermina o substantivo. Definido: o, a, os, as. Indefinido: um, uma, uns, umas."),
    ("Numeral: tipos", "Cardinal (um, dois), Ordinal (primeiro, segundo), Multiplicativo (dobro, triplo), Fracionario (metade, terco)."),
    ("Pronome pessoal: reto x obliquo", "Reto: eu, tu, ele/ela, nos, vos, eles/elas (sujeito). Obliquo: me, te, se, lhe, o, a, nos, vos (complemento)."),
    ("Pronome de tratamento", "Vossa Senhoria (tratamento respeitoso), Vossa Excelencia (altas autoridades), Vossa Magnificencia (reitores)."),
    ("Pronome possessivo", "Indica posse: meu, teu, seu, nosso, vosso, e flexoes. Ex: 'Este e meu livro.'"),
    ("Pronome demonstrativo", "Indica posicao: este(s)/esta(s) (proximo), esse(s)/essa(s) (medio), aquele(s)/aquela(s) (distante)."),
    ("Pronome indefinido", "Referencia vaga: algum, nenhum, todo, muito, pouco, qualquer, alguem, ninguem, tudo, nada."),
    ("Pronome relativo", "Retoma termo anterior: que (coisa/pessoa), quem (pessoa), onde (lugar), cujo (posse), qual (coisa/pessoa)."),
    ("Verbo: conceito", "Indica acao, estado, fenomeno da natureza, processo. Ex: correr, ser, chover, crescer."),
    ("Modos verbais", "Indicativo (certeza), Subjuntivo (duvida/possibilidade), Imperativo (ordem/pedido)."),
    ("Tempos verbais do indicativo", "Presente (estudo), Pret Perfeito (estudei), Pret Imperfeito (estudava), Pret Mais-que-perfeito (estudara), Fut Presente (estudarei), Fut Pret (estudaria)."),
    ("Tempos verbais do subjuntivo", "Presente (estude), Pret Imperfeito (estudasse), Futuro (estudar)."),
    ("Locucao verbal", "Dois verbos juntos = auxiliar + principal. Ex: 'Vou estudar', 'Tenho estudado', 'Estava estudando'."),
    ("Advrbio: definicao", "Modifica verbo, adjetivo ou outro advrbio. Invariável. Ex: 'Ele corre muito' (intensidade), 'Chegou cedo' (tempo)."),
    ("Advrbio: classificacao", "Modo (bem, mal), Tempo (ontem, hoje), Lugar (aqui, la), Intensidade (muito, pouco), Negacao (nao), Duvida (talvez), Afirmacao (sim)."),
    ("Preposicao: definicao", "Liga dois termos, estabelecendo relacao de dependencia. Essenciais: a, ante, ate, apos, com, contra, de, desde, em, entre, para, per, perante, por, sem, sob, sobre, tras."),
    ("Conjuncao coordenativa", "Liga oracoes independentes: aditiva (e), adversativa (mas), alternativa (ou), conclusiva (logo), explicativa (pois)."),
    ("Conjuncao subordinativa", "Liga oracao dependente: causal (porque), condicional (se), concessiva (embora), temporal (quando), final (para que), proporcional (a medida que), conformativa (conforme), consecutiva (tanto que), comparativa (como)."),
    ("Interjeicao", "Exprime emocao. Ex: 'Ah!', 'Uau!', 'Nossa!', 'Psiu!', 'Oba!', 'Ai!'."),
    # -- Sintaxe --
    ("Frase, oracao e periodo", "Frase: enunciado com sentido. Oracao: frase com verbo. Periodo: frase com uma ou mais oracoes."),
    ("Sujeito: tipos", "Simples (1 nucleo), Composto (2+ nucleos), Oculto/Desinencial, Indeterminado, Inexistente (verbos impessoais)."),
    ("Predicado: tipos", "Verbal (nucleo = verbo), Nominal (nucleo = predicativo), Verbo-nominal (2 nucleos)."),
    ("Complemento verbal: OD", "Objeto Direto: sem preposicao. Ex: 'Comprei um livro.'"),
    ("Complemento verbal: OI", "Objeto Indireto: com preposicao. Ex: 'Preciso de ajuda.'"),
    ("Complemento nominal", "Completa sentido de nome (adjetivo, advrbio, subst abstrato). Sempre com preposicao. Ex: 'Capaz de tudo.'"),
    ("Aposto: tipos", "Explicativo (com virgula), Enumerativo (dois-pontos), Resumitivo (tudo, nada), Especificador (sem virgula)."),
    ("Vocativo", "Chamamento/interpelacao. Sempre isolado por virgula. Ex: 'Maria, venha ca!'"),
    ("Adjunto adverbial", "Circunstancia: tempo, modo, lugar, causa, intensidade. Pode ser deslocado. Ex: 'Ontem, fui ao medico.'"),
    ("Adjunto adnominal", "Acompanha substantivo: artigo, pronome adj, numeral, adjetivo, locucao adj. Ex: 'Meu novo carro vermelho.'"),
    ("Predicativo do sujeito", "Caracteriza o sujeito. Com verbos de estado. Ex: 'O ceu esta azul'."),
    ("Predicativo do objeto", "Caracteriza o objeto. Ex: 'Ele considerou a prova facil'."),
    ("Agente da passiva", "Quem pratica a acao na voz passiva. Ex: 'O relatorio foi elaborado pelo analista'."),
    # -- Pontuacao --
    ("Virgula: usos principais", "Separar elementos de mesma funcao, isolar aposto, vocativo, adj adverbial deslocado, oracao adjetiva explicativa."),
    ("Virgula: uso proibido", "NUNCA separa: sujeito de verbo, verbo de objeto, nome de complemento."),
    ("Ponto e virgula", "Pausa maior que virgula. Separa itens de enumeracao complexa e oracoes coordenadas extensas."),
    ("Dois-pontos", "Introduz citacao, explicacao, enumeracao ou esclarecimento."),
    ("Travessao", "Indica fala de personagem, isola termos intercalados com enfase."),
    ("Aspas", "Citacao textual, estrangeirismos, ironia, destaque de palavra."),
    ("Reticencias", "Interrupcao, hesitacao, suspense, continuacao de ideia."),
    # -- Vozes verbais --
    ("Voz ativa", "Sujeito pratica a acao. Ex: 'O analista elaborou o relatorio.'"),
    ("Voz passiva analitica", "Sujeito sofre a acao. Verbo SER + participio. Ex: 'O relatorio foi elaborado pelo analista.'"),
    ("Voz passiva sintetica", "Verbo + SE (particula apassivadora). Ex: 'Elaborou-se o relatorio.' (relatorio = sujeito)"),
    ("Voz reflexiva", "Sujeito pratica e sofre a acao. Ex: 'O menino cortou-se.'"),
    # -- Figuras de linguagem --
    ("Metafora", "Comparacao implicita sem conectivo. Ex: 'Ele e uma rocha.' (= firme)"),
    ("Comparacao", "Comparacao com conectivo. Ex: 'Ele e forte como um touro.'"),
    ("Metonimia", "Substituicao por proximidade. Autor pela obra: 'Li Machado de Assis.'"),
    ("Catacrese", "Metafora ja incorporada a lingua. Ex: 'Pe da mesa', 'Braco da cadeira'."),
    ("Antitese", "Oposicao de ideias. Ex: 'Viver e morrer, amar e odiar.'"),
    ("Paradoxo", "Ideias contraditorias. Ex: 'O silencio e o melhor discurso.'"),
    ("Hiprbole", "Exagero. Ex: 'Ja te falei um milhao de vezes.'"),
    ("Eufemismo", "Suavizacao. Ex: 'Ele descansou' (morreu)."),
    ("Ironia", "Dizer o oposto. Ex: 'Que servico maravilhoso!' (quando deu errado)."),
    ("Prosopopeia", "Atribuir caracteristicas humanas a seres inanimados. Ex: 'O vento sussurrava.'"),
    ("Gradacao", "Sequencia crescente ou decrescente. Ex: 'Foi, correu, voou.'"),
    ("Silepse", "Concordancia com a ideia, nao com a forma. Ex: 'A multidao gritaram' (silepse de numero)."),
    # -- Coesao e coerencia --
    ("Coesao referencial", "Retomar termos por pronomes, sinonimos, elipses. Ex: 'Joao chegou. Ele estava cansado.'"),
    ("Coesao sequencial", "Conectar oracoes por conectivos. Ex: 'Estudou muito, portanto passou.'"),
    ("Coerencia textual", "Logica interna do texto. Respeita principios de nao-contradicao, nao-tautologia e relevancia."),
    ("Tipologia textual: narracao", "Conta historia com personagens, enredo, tempo, espaco. Verbos de acao."),
    ("Tipologia textual: descricao", "Caracteriza seres/objetos/lugares. Adjetivos, verbos de estado."),
    ("Tipologia textual: dissertacao", "Expoe e defende ideias. Estrutura: tese, argumentos, conclusao."),
    ("Tipologia textual: injuncao", "Instrui, orienta. Verbos no imperativo. Ex: manuais, receitas."),
    # -- Regencia --
    ("Regencia: assistir", "Sentido de 'ver' exige 'a': 'Assistiu ao filme.' Sentido de 'prestar assistencia' = VTD."),
    ("Regencia: aspirar", "Sentido de 'desejar' exige 'a': 'Aspirava ao cargo.' Sentido de 'sorver' = VTD."),
    ("Regencia: visar", "Sentido de 'objetivar' exige 'a': 'Visava ao sucesso.' Sentido de 'por visto' = VTD."),
    ("Regencia: implicar", "Sentido de 'acarretar' = VTD (sem 'em'). 'Implicou novos custos.'"),
    ("Regencia: obedecer", "Exige 'a': 'Obedeceu ao regulamento.'"),
    ("Regencia: proceder", "Sentido de 'executar' exige 'a': 'Procedeu a analise.' Sentido de 'ter fundamento' = VI."),
    # -- Concordancia --
    ("Conc verbal: 'a maioria'", "Pode concordar no singular ou plural: 'A maioria dos alunos chegou/chegaram.'"),
    ("Conc verbal: 'mais de um'", "Singular: 'Mais de um funcionario entregou o relatorio.'"),
    ("Conc verbal: 'haver' impessoal", "Sempre singular: 'Havia muitas pessoas na sala.'"),
    ("Conc verbal: 'fazer' temporal", "Sempre singular: 'Faz cinco anos que trabalho aqui.'"),
    ("Conc verbal: verbos impessoais", "Nao tem sujeito: Haver (existir), Fazer (tempo), Fenomenos naturais. Ficam na 3 singular."),
    ("Conc nominal: 'e proibido'", "Invariável sem artigo: 'E proibido entrada.' Variavel com artigo: 'E proibida a entrada.'"),
    ("Conc nominal: 'anexo'", "Concorda: 'Seguem anexas as planilhas.' Invariável: 'Em anexo seguem as planilhas.'"),
    ("Conc nominal: 'obrigado'", "Concorda com o genero: 'Ela disse: obrigada.' 'Ele disse: obrigado.'"),
    ("Conc nominal: 'menos'", "Invariável: 'Menos pessoas compareceram.' (nao existe 'menas')"),
    # -- Colocacao pronominal --
    ("Proclise: palavras negativas", "Pronome ANTES do verbo: 'Nunca me disseram a verdade.'"),
    ("Proclise: pronomes relativos", "Pronome ANTES: 'O amigo que me ajudou.'"),
    ("Proclise: advrbios", "Pronome ANTES: 'Sempre se dedicou aos estudos.'"),
    ("Proclise: conjuncoes subordinativas", "Pronome ANTES: 'Quando se formou, comecou a trabalhar.'"),
    ("Enclise: inicio de frase", "Pronome DEPOIS: 'Diga-me a verdade.'"),
    ("Enclise: imperativo afirmativo", "Pronome DEPOIS: 'Faca-o agora.'"),
    ("Mesoclise: futuro do presente", "Pronome no MEIO: 'Ajudar-lhe-ei.'"),
    ("Mesoclise: futuro do pretérito", "Pronome no MEIO: 'Far-se-ia.'"),
    # -- Estrutura e formacao de palavras --
    ("Derivacao prefixal", "Adiciona prefixo. Ex: 'in-feliz', 'des-governado', 're-fazer'."),
    ("Derivacao sufixal", "Adiciona sufixo. Ex: 'feliz-mente', 'govern-ador', 'real-izar'."),
    ("Derivacao parassintetica", "PrefixO + radical + sufixO simultaneamente. Ex: 'en-tard-ecer', 'a-noit-ecer'."),
    ("Composicao por justaposicao", "Palavras unidas sem perda. Ex: 'guarda-chuva', 'passatempo', 'mal-me-quer'."),
    ("Composicao por aglutinacao", "Palavras unidas com perda. Ex: 'planalto' (plano + alto), 'aguardente' (agua + ardente)."),
    ("Abreviacao / sigla", "Reducao de palavra. Ex: 'foto' (fotografia), 'ONU' (Organizacao das Nacoes Unidas)."),
    ("Onomatopeia", "Palavra que imita som. Ex: 'tic-tac', 'au-au', 'bum!'"),
    ("Estrangeirismo", "Palavra de outro idioma. Ex: 'mouse', 'software', 'feedback'."),
    # -- Periodo composto --
    ("Coordenacao sindetica", "Oracoes ligadas por conjuncao. Ex: 'Estudou e passou.'"),
    ("Coordenacao assindetica", "Oracoes justapostas sem conjuncao. Ex: 'Chegou, viu, venceu.'"),
    ("Subordinada substantiva subjetiva", "Exerce funcao de sujeito. Ex: 'E importante que voce estude.'"),
    ("Subordinada substantiva objetiva direta", "Exerce funcao de OD. Ex: 'Quero que voce passe.'"),
    ("Subordinada substantiva objetiva indireta", "Exerce funcao de OI. Ex: 'Preciso de que me ajude.'"),
    ("Subordinada adjetiva explicativa", "Entre virgulas, explica. Ex: 'O sol, que aquece a Terra, e vital.'"),
    ("Subordinada adjetiva restritiva", "Sem virgula, restringe. Ex: 'Alunos que estudam passam.'"),
    ("Subordinada adverbial causal", "Causa. Ex: 'Nao foi porque estava doente.'"),
    ("Subordinada adverbial condicional", "Condicao. Ex: 'Se estudar, passara.'"),
    ("Subordinada adverbial concessiva", "Concessao. Ex: 'Embora estivesse cansado, estudou.'"),
    ("Subordinada adverbial temporal", "Tempo. Ex: 'Quando chegar, me avise.'"),
    ("Subordinada adverbial final", "Finalidade. Ex: 'Estudou para que fosse aprovado.'"),
    ("Subordinada adverbial consecutiva", "Consequencia. Ex: 'Estudou tanto que passou.'"),
    ("Subordinada adverbial comparativa", "Comparacao. Ex: 'Ele estuda como um guerreiro.'"),
    ("Subordinada adverbial proporcional", "Proporcao. Ex: 'A medida que estudava, aprendia.'"),
    ("Subordinada adverbial conformativa", "Conformidade. Ex: 'Fez conforme foi orientado.'"),
    # -- Discurso direto x indireto --
    ("Discurso direto", "Fala reproduzida literalmente com aspas/travessao. Ex: 'Ele disse: Vou estudar.'"),
    ("Discurso indireto", "Fala relatada pelo narrador. Ex: 'Ele disse que iria estudar.'"),
]

FLASHCARDS_ETICA = [
    ("Principios Adm Publica: LIMPE", "Legalidade, Impessoalidade, Moralidade, Publicidade, Eficiencia (art. 37 CF)."),
    ("Legalidade vs Particular", "Adm: so pode fazer o que a lei permite. Particular: pode fazer o que a lei nao proibe."),
    ("Impessoalidade: conceito", "Atos visam interesse publico, sem beneficiar/prejudicar pessoas especificas. Isonomia, neutralidade."),
    ("Moralidade: conceito", "Exige probidade, honestidade, boa-fe. Nao basta ser legal, precisa ser etico."),
    ("Publicidade: conceito", "Transparencia dos atos adm. Excecoes: seguranca nacional e privacidade."),
    ("Eficiencia: conceito", "Melhor resultado com menores recursos. Qualidade, produtividade, economicidade."),
    ("Etica x Moral", "Etica: reflexao filosofica sobre a moral (estudo dos valores). Moral: regras e costumes socialmente aceitos."),
    ("Codigo de Etica: Decreto 1.171/94", "Aplica-se a servidores publicos federais. Termo de compromisso assinado na posse."),
    ("Vedacao: bens publicos", "E vedado usar bens, equipamentos e recursos publicos para fins particulares."),
    ("Vedacao: cargo", "E vedado usar o cargo para proveito pessoal ou de terceiros."),
    ("Vedacao: vantagem", "E vedado receber vantagem, presente ou beneficio indevido."),
    ("Vedacao: empresa privada", "E vedado participar de gerencia de empresa privada (salvo excecoes legais)."),
    ("Comissao de Etica", "Orgao que apura desvios eticos. Pena: censura etica (publica ou reservada)."),
    ("Lei 8.429/92: Improbidade", "Lei de Improbidade Administrativa. 3 categorias: enriquecimento ilicito, lesao ao erario, atentado aos principios."),
    ("Improbidade: enriquecimento ilicito", "Art. 9: receber vantagem economica indevida. Pena: perda da funcao, suspensao direitos politicos 8-14 anos."),
    ("Improbidade: lesao ao erario", "Art. 10: causar prejuizo ao patrimonio publico. Pena: perda da funcao, suspensao 5-10 anos."),
    ("Improbidade: atentado aos principios", "Art. 11: violar principios adm publica. Pena: perda da funcao, suspensao 3-5 anos."),
    ("Lei 14.230/2021: nova redacao", "Exige dolo para improbidade (nao mais culpa). Ato culposo deixou de ser improbidade."),
    ("Lei 12.846/2013: Anticorrupcao", "Responsabiliza administrativa e civilmente PESSOAS JURIDICAS por atos lesivos a adm publica."),
    ("Anticorrupcao: responsabilidade objetiva", "Independe de dolo ou culpa. Basta comprovar o ato lesivo."),
    ("Anticorrupcao: multa", "Multa de 0,1% a 30% do faturamento bruto do ultimo exercicio."),
    ("Anticorrupcao: Acordo de Leniência", "Reducao de penalidades em troca de colaboracao: identificar demais envolvidos e fornecer provas."),
    ("Conflito de interesses", "Interesses privados que podem influenciar o exercicio imparcial de funcoes publicas."),
    ("Integridade corporativa", "Fazer a coisa certa, mesmo sem supervisao. Alinhamento entre discurso e pratica."),
    ("Pilares da integridade", "Comprometimento alta direcao, Codigo de Conduta, Treinamento, Canal de Denuncia, Investigacoes, Consequencias, Monitoramento."),
    ("Accountability", "Dever de prestar contas e assumir responsabilidade por acoes e decisoes."),
    ("Programa de Integridade (Compliance)", "Sistema de prevencao, deteccao e correcao de desvios eticos e legais."),
    ("Compliance: diagnostico de riscos", "Mapeamento de vulnerabilidades, definicao de politicas, criacao de comite de etica."),
    ("Compliance: treinamentos", "Treinamentos obrigatorios presenciais ou EAD, campanhas de comunicacao, due diligence de terceiros."),
    ("Compliance: monitoramento", "Indicadores de efetividade, auditorias internas, revisao periodica do codigo, canal de denuncia ativo."),
    ("ESG: significado", "Environmental, Social, Governance. Criterios de sustentabilidade e impacto etico."),
    ("ESG: Ambiental (E)", "Mudancas climaticas, gestao de residuos, recursos hidricos, eficiencia energetica, pegada de carbono."),
    ("ESG: Social (S)", "Direitos humanos, diversidade, saude e seguranca, relacao com comunidades, trabalho decente."),
    ("ESG: Governanca (G)", "Transparencia, composicao do conselho, etica, compliance, remuneracao executiva."),
    ("Planejamento ESG", "Diagnostico de materialidade, metas (ex: carbono neutro), KPIs, reporte anual (GRI, SASB, TCFD)."),
    ("Governanca Corporativa", "Sistema pelo qual as organizacoes sao dirigidas e monitoradas, envolvendo relacionamentos entre socios, conselho, diretoria e orgaos de controle."),
    ("Conselho de Administracao", "Orgao colegiado responsavel pela direcao estrategica e fiscalizacao da gestao."),
    ("Comite de Auditoria", "Orgao de assessoramento ao conselho, responsavel por supervisionar controles internos e auditoria independente."),
    ("Auditoria interna", "Avalia controles internos, gestao de riscos e governanca. Independente e objetiva."),
    ("Auditoria independente", "Empresa externa que examina demonstracoes financeiras e emite opiniao sobre sua adequacao."),
    ("Gestao de riscos corporativos", "Identificar, avaliar e mitigar riscos: estrategicos, financeiros, operacionais, compliance, reputacionais."),
    ("Risco operacional", "Possibilidade de perdas por falhas em processos internos, pessoas, sistemas ou eventos externos."),
    ("Risco de compliance", "Risco de sancoes legais, perdas financeiras ou dano reputacional por descumprimento de leis e regulamentos."),
    ("Canal de denuncia", "Meio seguro e anonimo para reportar violacoes eticas e legais. Essencial no programa de integridade."),
    ("Due diligence de terceiros", "Processo de verificacao de antecedentes de parceiros, fornecedores e contratados para mitigar riscos."),
    ("Politica de presentes e hospitalidade", "Regras sobre aceitar ou oferecer brindes, presentes, convites e hospitalidade. Limites de valor e transparencia."),
    ("Privacidade e protecao de dados", "LGPD (Lei 13.709/2018): dados pessoais devem ser tratados com finalidade, adequacao, necessidade e transparencia."),
    ("LGPD: titulares de dados", "Pessoa natural a quem se referem os dados pessoais. Direitos: acesso, correcao, exclusao, portabilidade."),
    ("LGPD: controlador", "Pessoa juridica que toma decisoes sobre o tratamento de dados pessoais."),
    ("LGPD: operador", "Pessoa que realiza o tratamento em nome do controlador."),
    ("LGPD: ANPD", "Autoridade Nacional de Protecao de Dados. Orgao responsavel por fiscalizar e regulamentar a LGPD."),
    ("LGPD: bases legais", "Consentimento, obrigacao legal, execucao de contrato, exercicio regular de direitos, interesse legitimo, etc."),
    ("LGPD: multas", "Multa de ate 2% do faturamento da empresa (limitada a R$ 50 milhoes por infracao)."),
    ("Transparencia ativa", "Dever da adm publica de divulgar informacoes de interesse geral, independentemente de solicitacao."),
    ("Transparencia passiva", "Obrigacao de fornecer informacoes quando solicitadas por qualquer pessoa (Lei de Acesso a Informacao)."),
    ("LAI (Lei 12.527/2011)", "Regula o acesso a informacoes publicas. Prazos: 20 dias (prorrogaveis por +10)."),
    ("ODS (Objetivos de Desenvolvimento Sustentavel)", "17 objetivos da ONU para 2030: erradicacao da pobreza, educacao, igualdade de genero, acao climatica, etc."),
    ("ODS 16: Paz, Justica e Instituicoes Eficazes", "Promover sociedades pacificas e inclusivas, garantir acesso a justica e construir instituicoes eficazes."),
    ("ODS 8: Trabalho Decente e Crescimento Economico", "Promover crescimento economico sustentado, emprego pleno e trabalho decente para todos."),
    ("ODS 5: Igualdade de Genero", "Alcancar a igualdade de genero e empoderar todas as mulheres e meninas."),
    ("ODS 13: Acao Climatica", "Tomar medidas urgentes para combater a mudanca climatica e seus impactos."),
    ("Acordo de Paris", "Tratado internacional para limitar o aquecimento global a 1,5C acima dos niveis pre-industriais."),
    ("Greenwashing", "Pratica de empresas se apresentarem como ambientalmente responsaveis sem acoes efetivas."),
    ("Governanca publica", "Conjunto de mecanismos de lideranca, estrategia e controle para avaliar e direcionar a gestao publica."),
    ("Controles internos", "Processos operacionalizados pela gestao para mitigar riscos e assegurar alcance dos objetivos."),
    ("Corrupcao: conceito", "Abuso de poder confiado para beneficiar interesses privados. Pode ser publica ou privada."),
    ("Suborno", "Oferecer/dar vantagem indevida a agente publico para influenciar ato oficial."),
    ("Tráfico de influencia", "Vender ou comprar influencia sobre ato de agente publico."),
    ("Lavagem de dinheiro", "Ocultar origem ilicita de recursos financeiros. Etapas: colocacao, ocultacao, integracao."),
    ("Whistleblower (denunciante)", "Pessoa que reporta internamente ou externamente violacoes eticas/legais. Protecao contra retalhacao."),
    ("Cultura organizacional etica", "Valores, normas e praticas que promovem o comportamento etico na organizacao."),
    ("Lideranca etica", "Lideres que exemplificam integridade, transparencia e responsabilidade (tone at the top)."),
    ("Due diligence de integridade", "Verificacao de conformidade etica e legal de parceiros de negocios antes da contratacao."),
    ("Monitoramento de integridade", "Acompanhamento continuo de indicadores do programa de integridade: denuncias, investigacoes, sancoes."),
    ("Relatorio de sustentabilidade", "Documento com informacoes sobre desempenho economico, social e ambiental. Padroes GRI, SASB."),
]

FLASHCARDS_RL = [
    ("Proposicao", "Sentenca declarativa que pode ser V ou F. Nunca interrogativa, exclamativa ou imperativa."),
    ("Negacao ~", "Inverte o valor logico. ~p e V quando p e F, e vice-versa."),
    ("Conjuncao ^ (e)", "Verdadeira apenas quando AMBAS as proposicoes sao V."),
    ("Disjuncao inclusiva v (ou)", "Falsa apenas quando AMBAS sao F. Verdadeira se pelo menos uma for V."),
    ("Disjuncao exclusiva (ou...ou)", "Verdadeira quando os valores sao DIFERENTES. Falsa quando iguais."),
    ("Condicional -> (se...entao)", "Falsa apenas quando V -> F (Vera Fischer). Nos demais casos, V."),
    ("Bicondicional <-> (se e so se)", "Verdadeira quando valores IGUAIS. Falsa quando diferentes."),
    ("Tautologia", "Proposicao composta SEMPRE verdadeira. Ex: p v ~p."),
    ("Contradicao", "Proposicao composta SEMPRE falsa. Ex: p ^ ~p."),
    ("Contingencia", "Proposicao que pode ser V ou F dependendo dos valores."),
    ("Tabela verdade: 2^n linhas", "Para n proposicoes, a tabela tem 2^n linhas. 2 props = 4 linhas, 3 = 8, 4 = 16."),
    ("Equivalencia: p->q = ~p v q", "A condicional equivale a negar a primeira OU manter a segunda."),
    ("Equivalencia: p->q = ~q->~p", "Contrapositiva: inverte e nega ambas. Mantem o valor logico."),
    ("Equivalencia: p<->q", "(p->q) ^ (q->p). Bicondicional = duas condicionais."),
    ("Dupla negacao ~(~p) = p", "Negar duas vezes volta ao valor original."),
    ("Lei De Morgan: ~(p^q) = ~p v ~q", "Negar uma conjuncao = negar cada uma com OU."),
    ("Lei De Morgan: ~(p v q) = ~p ^ ~q", "Negar uma disjuncao = negar cada uma com E."),
    ("Negacao da condicional: ~(p->q)", "MANE: MAntem a primeira E NEga a segunda. p ^ ~q."),
    ("Negacao da bicondicional", "~(p<->q) = p v q (ou exclusivo). Valores diferentes."),
    ("Modus Ponens", "p->q, p :. q. Se p entao q, p e V, logo q e V."),
    ("Modus Tollens", "p->q, ~q :. ~p. Se p entao q, q e F, logo p e F."),
    ("Silogismo hipotetico", "p->q, q->r :. p->r."),
    ("Silogismo disjuntivo", "p v q, ~p :. q."),
    ("Falacia: afirmacao do consequente", "p->q, q :. p (INVALIDO!). Nao se pode concluir p."),
    ("Falacia: negacao do antecedente", "p->q, ~p :. ~q (INVALIDO!). Nao se pode concluir ~q."),
    ("Quantificador universal (Todo)", "'Todo A e B' = 'Se x e A, entao x e B'."),
    ("Quantificador existencial (Algum)", "'Algum A e B' = 'Existe x tal que x e A e x e B'."),
    ("Negacao de 'Todo A e B'", "'Algum A nao e B'. (Nem todo A e B)"),
    ("Negacao de 'Nenhum A e B'", "'Algum A e B'."),
    ("Negacao de 'Algum A e B'", "'Nenhum A e B' (ou 'Todo A nao e B')."),
    ("Negacao de 'Algum A nao e B'", "'Todo A e B'."),
    ("Diagramas de Venn", "Representacao grafica de conjuntos e relacoes entre eles."),
    ("n(A U B)", "n(A) + n(B) - n(A∩B). Elementos de A ou B."),
    ("n(A U B U C)", "n(A)+n(B)+n(C) - n(A∩B)- n(A∩C)- n(B∩C) + n(A∩B∩C)."),
    ("Principio da Casa dos Pombos", "Se n > m objetos em m gavetas, pelo menos 1 gaveta tem 2+ objetos."),
    ("PA: termo geral", "an = a1 + (n-1)*r. r = razao (diferenca constante)."),
    ("PA: soma dos n primeiros", "Sn = (a1 + an) * n / 2."),
    ("PG: termo geral", "an = a1 * q^(n-1). q = razao (multiplicacao constante)."),
    ("PG: soma finita", "Sn = a1 * (q^n - 1) / (q - 1)."),
    ("Sequencia de Fibonacci", "Cada termo e a soma dos dois anteriores: 1, 1, 2, 3, 5, 8, 13, 21..."),
    ("Anagrama", "Permutacao das letras de uma palavra. n! / (r1! * r2! * ...)."),
    ("Arranjo simples", "A(n,p) = n! / (n-p)!. Ordem importa. Ex: senhas, podium."),
    ("Combinacao simples", "C(n,p) = n! / (p! * (n-p)!). Ordem NAO importa. Ex: grupos, comissoes."),
    ("Permutacao simples", "Pn = n!. Ordenar n elementos distintos. Ex: anagramas sem repeticoes."),
    ("Probabilidade: definicao", "P(E) = casos favoraveis / casos possiveis. Valor entre 0 e 1."),
    ("Probabilidade: eventos independentes", "P(A∩B) = P(A) * P(B). A ocorrencia de um nao afeta o outro."),
    ("Probabilidade: eventos mutuamente exclusivos", "P(A U B) = P(A) + P(B). Nao podem ocorrer juntos."),
    ("Probabilidade condicional", "P(A|B) = P(A∩B) / P(B). Probabilidade de A dado que B ocorreu."),
    ("Teorema de Bayes", "P(A|B) = P(B|A) * P(A) / P(B). Atualiza probabilidade com nova informacao."),
    ("Analise combinatoria: principio multiplicativo", "Se evento A tem m possibilidades e B tem n, entao A e B tem m*n possibilidades."),
    ("Analise combinatoria: principio aditivo", "Se evento A tem m possibilidades OU B tem n, entao m + n (eventos mutuamente exclusivos)."),
    ("Regra de tres simples", "Relacao direta ou inversa entre duas grandezas."),
    ("Regra de tres composta", "Multiplica razoes direta/inversamente proporcionais."),
    ("Media aritmetica simples", "Soma dos valores dividida pelo numero de elementos."),
    ("Media aritmetica ponderada", "Soma (valor * peso) / soma dos pesos."),
    ("Mediana", "Valor central dos dados ordenados. Se n for par, media dos dois centrais."),
    ("Moda", "Valor que mais se repete no conjunto."),
    ("Raciocinio espacial", "Identificar padroes de rotacao, reflexao, translacao em figuras geometricas."),
    ("Raciocinio numerico", "Identificar padroes em sequencias numericas: diferenca, razao, operacao oculta."),
    ("Raciocinio abstrato", "Identificar analogias e padroes em figuras abstratas."),
    ("Argumento valido", "Se premissas sao V, conclusao e necessariamente V."),
    ("Argumento invalido (falacia)", "Mesmo com premissas V, conclusao pode ser F."),
    ("Dilema construtivo", "(p->q) ^ (r->s), p v r :. q v s."),
    ("Dilema destrutivo", "(p->q) ^ (r->s), ~q v ~s :. ~p v ~r."),
    ("Equivalencia: p v q = q v p", "Comutativa: a ordem dos fatores nao altera."),
    ("Equivalencia: p ^ q = q ^ p", "Comutativa na conjuncao."),
    ("Equivalencia: p ^ (q ^ r) = (p ^ q) ^ r", "Associativa."),
    ("Equivalencia: p v (q v r) = (p v q) v r", "Associativa."),
    ("Equivalencia: p ^ (q v r) = (p^q) v (p^r)", "Distributiva."),
    ("Equivalencia: p ^ p = p", "Idempotente."),
    ("Equivalencia: p v p = p", "Idempotente."),
    ("Equivalencia: p ^ (p v q) = p", "Absorcao."),
    ("Equivalencia: p v (p ^ q) = p", "Absorcao."),
    ("Condicional associada: p->q", "Equivale a ~p v q (negacao do antecedente OU afirmacao do consequente)."),
    ("Argumento dedutivo", "Conclusao decorre necessariamente das premissas. Logica formal."),
    ("Argumento indutivo", "Conclusao e provavel com base em observacoes. Generalizacao."),
    ("Argumento abdutivo", "Conclusao e a melhor explicacao para os fatos observados."),
    ("Raciocinio logico: dica", "Sempre desconfie de generalizacoes. Use diagramas de Venn para relacoes categoricas."),
    ("Verdade e validade", "Premissas verdadeiras + argumento valido = argumento solido (conclusao verdadeira)."),
]

FLASHCARDS_PREV = [
    ("Regime de capitalizacao", "Cada participante acumula recursos para formar sua propria reserva para aposentadoria."),
    ("Regime de reparticao simples", "Geracao atual paga aposentadoria da geracao anterior. Usado no RGPS."),
    ("RGPS", "Regime Geral de Previdencia Social. Gerido pelo INSS. Obrigatorio para trabalhadores privados."),
    ("RPPS", "Regime Proprio de Previdencia Social. Para servidores publicos titulares de cargo efetivo."),
    ("RPC", "Regime de Previdencia Complementar. Facultativo, autonomo em relacao ao RGPS/RPPS."),
    ("CNPC", "Conselho Nacional de Previdencia Complementar. Orgao normativo do RPC."),
    ("PREVIC", "Superintendencia Nacional de Previdencia Complementar. Fiscaliza as EFPC (fundos de pensao)."),
    ("SUSEP", "Superintendencia de Seguros Privados. Fiscaliza as EAPC (bancos, seguradoras)."),
    ("EFPC", "Entidades Fechadas de Previdencia Complementar. Fundos de pensao, sem fins lucrativos."),
    ("EAPC", "Entidades Abertas de Previdencia Complementar. Bancos e seguradoras, com fins lucrativos."),
    ("EFPC: acesso restrito", "Destinadas a empregados de uma empresa, servidores publicos ou associados."),
    ("EAPC: acesso publico", "Abertas a qualquer pessoa fisica. Produtos: PGBL, VGBL."),
    ("LC 109/2001", "Lei Complementar que dispoe sobre o Regime de Previdencia Complementar."),
    ("LC 108/2001", "Regula a relacao entre entes publicos e suas EFPC (patrocinio publico)."),
    ("Plano BD (Beneficio Definido)", "Beneficio futuro conhecido. Contribuicoes calculadas atuarialmente. Risco da entidade."),
    ("Plano CD (Contribuicao Definida)", "Contribuicao fixa. Beneficio variavel conforme saldo. Risco do participante."),
    ("Plano CV (Contribuicao Variavel)", "Misto: acumulacao como CD, beneficio pode ter caracteristicas de BD."),
    ("PGBL", "Plano Gerador de Beneficio Livre. Deducao fiscal ate 12% da renda bruta. IR incide sobre o total no resgate."),
    ("VGBL", "Vida Gerador de Beneficio Livre. Sem deducao fiscal. IR incide apenas sobre rendimentos."),
    ("Portabilidade", "Transferir recursos acumulados para outro plano de previdencia, sem IR no momento."),
    ("Resgate", "Retirar recursos acumulados. Incide IR conforme tabela regressiva ou progressiva."),
    ("BPD (Beneficio Proporcional Diferido)", "Manter recursos no plano sem continuar contribuindo, recebendo beneficio proporcional no futuro."),
    ("Autopatrocínio", "Participante desligado continua contribuindo, assumindo ambas as partes (sua + do patrocinador)."),
    ("Elegibilidade", "Conjunto de requisitos para ter direito ao beneficio: idade, tempo de contribuicao, carencia."),
    ("Reserva matematica", "Valor atuarialmente calculado para cobrir compromissos futuros do plano."),
    ("Saldo de conta", "Contribuicoes (participante + patrocinador) + rentabilidade liquida - taxas."),
    ("Taxa de carregamento", "Taxa sobre cada contribuicao. Cobre despesas administrativas e de comercializacao."),
    ("Taxa de administracao", "Percentual sobre o saldo acumulado."),
    ("Taxa de performance", "Sobre rentabilidade acima de meta (em alguns planos)."),
    ("Tributacao regressiva IR", "Aliquotas de 10% a 27,5% conforme prazo de acumulacao. Quanto maior prazo, menor aliquota."),
    ("Tributacao progressiva IR", "Aliquotas de 0% a 27,5% (mesma tabela do IRPF). Vantajosa para renda menor na aposentadoria."),
    ("Funpresp", "Fundacao de Previdencia Complementar do Servidor Publico Federal. EFPC federal."),
    ("PREVCOM (SP)", "Fundacao de Previdencia Complementar do Estado de SP. EFPC estadual."),
    ("PREVCOM: Lei 14.653/2011", "Autorizou criacao da PREVCOM SP. Entidade fechada, sem fins lucrativos."),
    ("PREVCOM: Decreto 57.785/2012", "Aprovou o Estatuto Social da PREVCOM. Estrutura: CD, CF, DIREX."),
    ("Conselho Deliberativo (CD)", "Define politicas, avalia gestao, aprova regulamentos dos planos."),
    ("Conselho Fiscal (CF)", "Fiscaliza atos da administracao, examina demonstracoes financeiras."),
    ("Diretoria Executiva (DIREX)", "Administra a entidade, executa as deliberacoes do CD."),
    ("Plano Prevcom RP", "Servidores publicos titulares de cargo efetivo do Estado de SP (Regime Proprio)."),
    ("Plano Prevcom RG", "Servidores celetistas (Regime Geral)."),
    ("Resolucao PREVIC 23/2023", "Normas de governanca, gestao de riscos e controles internos das EFPC."),
    ("Politica de investimentos", "Documento formal aprovado pelo CD com diretrizes de alocacao de recursos."),
    ("Limites de alocacao", "Renda fixa, renda variavel, imoveis, investimentos estruturados. Definidos pelo CMN."),
    ("Risco de mercado", "Variacao de precos dos ativos: acoes, taxas de juros, cambio."),
    ("Risco de credito", "Possibilidade de contraparte nao honrar compromissos financeiros."),
    ("Risco de liquidez", "Dificuldade de vender ativo sem perda significativa de valor."),
    ("Risco operacional", "Perdas por falhas em processos, pessoas, sistemas ou eventos externos."),
    ("Risco legal", "Perdas por descumprimento de leis, regulamentos ou contratos."),
    ("ALM (Asset Liability Management)", "Gestao integrada de ativos e passivos para garantir solvencia do plano."),
    ("Segmentacao de massas", "Separacao de participantes em grupos: ativos, assistidos, autopatrocinados, BPD."),
    ("Avaliacao atuarial", "Calculo anual das obrigacoes do plano com base em hipoteses demograficas e financeiras."),
    ("Hipotese atuarial", "Premissas: taxa de juros, mortalidade, rotatividade, crescimento salarial, inflacao."),
    ("Deficit tecnico", "Passivo atuarial maior que ativos do plano. Exige equacionamento."),
    ("Superavit tecnico", "Ativos maiores que passivo atuarial. Pode resultar em melhoria de beneficios."),
    ("Equacionamento de deficit", "Medidas: aumento de contribuicoes, reducao de beneficios, aporte do patrocinador."),
    ("Patrocinador", "Pessoa juridica que institui e mantem plano para seus empregados."),
    ("Participante", "Pessoa fisica vinculada ao plano de previdencia complementar."),
    ("Assistido", "Participante que ja recebe beneficio do plano."),
    ("Beneficiario", "Pessoa indicada pelo participante para receber beneficios em caso de morte."),
    ("Contribuicao normal", "Contribuicao regular do participante e patrocinador durante fase de acumulacao."),
    ("Contribuicao extraordinaria", "Contribuicao adicional para equacionamento de deficit."),
    ("Renda vitalicia", "Beneficio pago mensalmente ate a morte do assistido."),
    ("Renda por prazo certo", "Beneficio pago por periodo determinado (ex: 20 anos)."),
    ("Renda certa", "Valor fixo por periodo determinado, sem risco de longevidade."),
    ("Peculio por morte", "Valor pago aos beneficiarios em caso de morte do participante."),
    ("Beneficio de risco", "Cobertura de risco: morte, invalidez, sobrevivencia."),
    ("Excedente de rentabilidade", "Rentabilidade acima da meta atuarial. Pode ser distribuido aos participantes."),
    ("Meta atuarial", "Taxa de retorno esperada dos investimentos para garantir compromissos do plano."),
    ("IGP-M + x% aa", "Indexador comum para metas atariais de planos de previdencia."),
    ("CDI como referencia", "Taxa de referencia para investimentos em renda fixa."),
    ("IPCA + x% aa", "Indexador de inflacao para metas atariais de longo prazo."),
    ("Fundos de pensao: origem", "Surgiram no Brasil na decada de 1970 com a Previ (Banco do Brasil) e Petros (Petrobras)."),
    ("Previ", "Fundo de pensao dos funcionarios do Banco do Brasil. Maior EFPC da America Latina."),
    ("Petros", "Fundo de pensao dos funcionarios da Petrobras."),
    ("Funcesp", "Fundo de pensao dos funcionarios da CESP (energia eletrica)."),
    ("Portabilidade: prazo", "Apos cumprido prazo de permanencia minima do regulamento."),
    ("Resgate: prazo", "Depende do regulamento de cada plano."),
    ("BPD: requisitos", "Nao continuar contribuindo, manter recursos no plano, receber beneficio proporcional no futuro."),
    ("Autopatrocínio: valor", "Participante contribui com valor correspondente a sua parte + a do patrocinador."),
    ("Migracao de planos", "Possibilidade de migrar entre planos (ex: BD para CD) conforme regulamento."),
    ("Retorno de investimentos", "Rentabilidade dos investimentos do plano. Essencial para formacao da reserva."),
    ("Custodia de ativos", "Servico de guarda e controle dos ativos financeiros do plano."),
]

FLASHCARDS_TI = [
    ("Modelo cascata (Waterfall)", "Ciclo de vida sequencial: requisitos, projeto, implementacao, testes, implantacao, manutencao."),
    ("Scrum: Papeis", "Product Owner (requisitos), Scrum Master (impedimentos), Time (entrega)."),
    ("Scrum: Cerimonias", "Sprint Planning, Daily Scrum, Sprint Review, Sprint Retrospective."),
    ("Scrum: Artefatos", "Product Backlog, Sprint Backlog, Incremento."),
    ("Scrum: Sprint", "Periodo fixo (1-4 semanas) para entregar incremento utilizaavel."),
    ("Daily Scrum", "Reuniao diaria de 15 min. O que fez? O que vai fazer? Impedimentos?"),
    ("Kanban", "Metodo agil baseado em fluxo continuo. Visualiza trabalho em colunas."),
    ("SOLID: SRP", "Single Responsibility: uma classe deve ter um unico motivo para mudar."),
    ("SOLID: OCP", "Open/Closed: classes abertas para extensao, fechadas para modificacao."),
    ("SOLID: LSP", "Liskov Substitution: classes derivadas devem substituir classes base."),
    ("SOLID: ISP", "Interface Segregation: interfaces especificas, nao gerais."),
    ("SOLID: DIP", "Dependency Inversion: depender de abstracoes, nao de implementacoes."),
    ("UML: Diagrama de Casos de Uso", "Mostra atores e funcionalidades do sistema."),
    ("UML: Diagrama de Classes", "Mostra classes, atributos, metodos e relacoes (associacao, heranca, dependencia)."),
    ("UML: Diagrama de Sequencia", "Interacao temporal entre objetos com troca de mensagens."),
    ("UML: Diagrama de Atividades", "Fluxo de atividades e decisoes em um processo."),
    ("UML: Diagrama de Estados", "Estados e transicoes de um objeto ao longo do ciclo de vida."),
    ("MVC (Model-View-Controller)", "Model (dados), View (interface), Controller (logica de controle)."),
    ("SQL: SELECT", "Consulta dados: SELECT colunas FROM tabela WHERE condicao."),
    ("SQL: JOIN", "Combina registros de tabelas. INNER: so matches. LEFT: todos da esquerda."),
    ("SQL: GROUP BY", "Agrupa registros com valores iguais em colunas especificadas."),
    ("SQL: HAVING", "Filtra grupos apos GROUP BY. Diferente de WHERE (filtra antes)."),
    ("SQL: ORDER BY", "Ordena resultados: ASC (crescente) ou DESC (decrescente)."),
    ("SQL: INSERT", "Insere dados: INSERT INTO tabela (colunas) VALUES (valores)."),
    ("SQL: UPDATE", "Atualiza dados: UPDATE tabela SET coluna=valor WHERE condicao."),
    ("SQL: DELETE", "Remove registros: DELETE FROM tabela WHERE condicao."),
    ("SQL: TRUNCATE", "Remove TODOS os registros rapidamente. Nao pode usar WHERE. Mantem estrutura."),
    ("SQL: DROP", "Remove a estrutura da tabela: DROP TABLE nome."),
    ("SQL: CREATE TABLE", "Cria tabela: CREATE TABLE nome (colunas, constraints)."),
    ("SQL: ALTER TABLE", "Modifica estrutura: ADD, DROP, MODIFY colunas."),
    ("SQL: PRIMARY KEY", "Identifica unicamente cada registro. UNIQUE + NOT NULL."),
    ("SQL: FOREIGN KEY", "Garante integridade referencial entre tabelas."),
    ("SQL: INDEX", "Acelera consultas. CREATE INDEX ON tabela (coluna)."),
    ("SQL: VIEW", "Tabela virtual baseada em consulta SQL armazenada."),
    ("SQL: subconsulta", "SELECT dentro de SELECT. Pode ser correlacionada ou nao."),
    ("SQL: funcoes agregadas", "COUNT, SUM, AVG, MIN, MAX. Usadas com GROUP BY."),
    ("Normalizacao: 1FN", "Atributos atomicos (indivisiveis). Sem grupos repetitivos."),
    ("Normalizacao: 2FN", "1FN + dependencia funcional completa da chave primaria."),
    ("Normalizacao: 3FN", "2FN + dependencia transitiva eliminada."),
    ("NoSQL: tipos", "Chave-valor (Redis), Documentos (MongoDB), Colunas (Cassandra), Grafos (Neo4j)."),
    ("NoSQL: MongoDB", "Banco orientado a documentos. Dados em JSON/BSON. Schema flexivel."),
    ("NoSQL: Redis", "Banco chave-valor em memoria. Alta performance. Cache, sessoes."),
    ("ACID", "Atomicidade, Consistencia, Isolamento, Durabilidade. Propriedades transacionais."),
    ("BASE", "Basically Available, Soft state, Eventually consistent. Modelo NoSQL."),
    ("Modelo TCP/IP: camadas", "Aplicacao, Transporte, Internet, Enlace/Fisica."),
    ("Modelo OSI: camadas", "Fisica, Enlace, Rede, Transporte, Sessao, Apresentacao, Aplicacao."),
    ("HTTP: porta 80", "Protocolo de transferencia de hipertexto. Sem criptografia."),
    ("HTTPS: porta 443", "HTTP com TLS/SSL. Comunicacao criptografada."),
    ("DNS", "Domain Name System. Traduz nomes de dominio em enderecos IP."),
    ("DHCP", "Atribui enderecos IP automaticamente a dispositivos na rede."),
    ("FTP: porta 21", "File Transfer Protocol. Transferencia de arquivos."),
    ("SMTP: porta 25", "Simple Mail Transfer Protocol. Envio de emails."),
    ("TCP", "Orientado a conexao, confiavel, com controle de fluxo. HTTP, FTP, SMTP usam TCP."),
    ("UDP", "Nao orientado a conexao, rapido, sem garantia de entrega. DNS, VoIP usam UDP."),
    ("IP", "Internet Protocol. Roteamento de pacotes entre redes."),
    ("Mascara de sub-rede /24", "255.255.255.0 = 24 bits de rede, 8 bits de host. 254 hosts viaveis."),
    ("Classe C de IP", "192-223 no primeiro octeto. Ex: 192.168.0.1."),
    ("OWASP Top 10: Injection", "Dados nao confiaveis enviados a interpretador. SQL, OS, LDAP injection."),
    ("OWASP: XSS", "Cross-Site Scripting. Scripts maliciosos injetados em paginas web."),
    ("OWASP: Broken Authentication", "Falhas em autenticacao e gerenciamento de sessoes."),
    ("OWASP: Sensitive Data Exposure", "Exposicao de dados sensiveis (senhas, CPF, dados bancarios)."),
    ("OWASP: XXE", "XML External Entities. Ataque a processadores XML."),
    ("OWASP: Broken Access Control", "Falhas no controle de acesso. Usuarios acessam recursos nao autorizados."),
    ("Criptografia simetrica", "Mesma chave para cifrar e decifrar. AES, DES, 3DES. Rapida."),
    ("Criptografia assimetrica", "Par de chaves (publica + privada). RSA, ECC. Mais lenta, segura."),
    ("AES", "Advanced Encryption Standard. Simetrico. Padrao mundial."),
    ("RSA", "Rivest-Shamir-Adleman. Assimetrico. Usado em SSL/TLS."),
    ("Hash: definicao", "Funcao unilateral que gera resumo (digest) de dados. MD5, SHA-256."),
    ("Assinatura digital", "Garante autenticidade e integridade. Chave privada assina, publica verifica."),
    ("Certificado digital", "Documento eletronico que vincula identidade a chave publica. ICP-Brasil."),
    ("Firewall", "Dispositivo que controla trafego de rede com base em regras de seguranca."),
    ("VPN", "Rede privada virtual. Criptografa comunicacao entre ponto A e B pela internet."),
    ("IDS/IPS", "Intrusion Detection/Prevention System. Detecta e bloqueia ataques."),
    ("Phishing", "Ataque que usa mensagens ou sites fraudulentos para obter dados confidenciais."),
    ("Ransomware", "Malware que sequestra dados e exige resgate para liberacao."),
    ("DDoS", "Distributed Denial of Service. Sobrecarrega servidor com multiplas requisicoes."),
    ("ISO 27001", "Sistema de Gestao de Seguranca da Informacao (SGSI). Ciclo PDCA."),
    ("PDCA", "Plan (Planejar), Do (Executar), Check (Verificar), Act (Agir). Melhoria continua."),
    ("ITIL: Gerenciamento de Incidentes", "Restaurar servico normal o mais rapido possivel, minimizando impacto."),
    ("ITIL: Gerenciamento de Problemas", "Identificar causas raiz de incidentes e prevenir recorrencia."),
    ("ITIL: Gerenciamento de Mudancas", "Controlar ciclo de vida de mudancas para minimizar riscos."),
    ("ITIL: Gerenciamento de Nivel de Servico", "Definir, negociar, monitorar e reportar niveis de servico acordados."),
    ("COBIT 5: 5 Principios", "Necessidades stakeholders, Cobertura ponta a ponta, Modelo unico, Holistica, Separar governanca/gestao."),
    ("PMBOK 7: 12 Principios", "Administracao, Equipe, Stakeholders, Valor, Pensamento sistemico, Lideranca, Tailoring, Qualidade, Complexidade, Risco, Adaptabilidade, Transformacao."),
    ("IaaS", "Infrastructure as a Service. Maquinas virtuais, storage, redes. Cliente gerencia SO e apps."),
    ("PaaS", "Platform as a Service. Plataforma para desenvolver e implantar apps. Sem gerenciar infra."),
    ("SaaS", "Software as a Service. Software pronto, usado via navegador. Ex: Gmail, Salesforce."),
    ("Nuvem publica", "Recursos compartilhados via internet. AWS, Azure, Google Cloud."),
    ("Nuvem privada", "Recursos exclusivos de uma organizacao. Maior controle e seguranca."),
    ("Nuvem hibrida", "Combina nuvens publicas e privadas. Compartilha recursos entre ambas."),
    ("AWS Lambda", "Servico serverless da AWS. Executa codigo em resposta a eventos."),
    ("Azure Virtual Machines", "Servico IaaS da Azure para criar e gerenciar maquinas virtuais."),
    ("Escalabilidade vertical (scale up)", "Aumentar recursos de uma instancia: mais RAM, CPU, disco."),
    ("Escalabilidade horizontal (scale out)", "Adicionar mais instancias para distribuir carga."),
    ("Docker: Dockerfile", "Arquivo com instrucoes (FROM, RUN, COPY, CMD) para construir imagem."),
    ("Docker: container", "Ambiente isolado e leve que executa uma aplicacao."),
    ("Docker: imagem", "Template read-only para criar containers. Construida a partir do Dockerfile."),
    ("Docker: docker run", "Comando para criar e iniciar container a partir de uma imagem."),
    ("Kubernetes: Pod", "Menor unidade do K8s. Um ou mais containers que compartilham recursos."),
    ("Kubernetes: Deployment", "Garante numero desejado de replicas de pods. Suporta rolling updates."),
    ("Kubernetes: Service", "Expoe pods como servico de rede. IP estavel e DNS."),
    ("Kubernetes: ConfigMap", "Armazena configuracoes nao confidenciais em pares chave-valor."),
    ("CI/CD", "Integracao Continua (automacao build/teste) + Implantacao Continua (automacao deploy)."),
    ("Jenkins", "Ferramenta de automatizacao de pipelines CI/CD. Open source."),
    ("Git: commit", "Salva alteracoes no repositorio local com mensagem descritiva."),
    ("Git: branch", "Ramo separado para desenvolver funcionalidades sem afetar codigo principal."),
    ("Git: merge", "Une alteracoes de branches diferentes."),
    ("Git: pull request", "Solicitacao para revisar e incorporar alteracoes de uma branch."),
    ("Python: list vs tuple", "List (mutavel) vs Tuple (imutavel). Ambos sequenciais."),
    ("Python: dict", "Estrutura mutavel de pares chave-valor. Acesso rapido por chave."),
    ("Python: set", "Conjunto mutavel de elementos unicos. Operacoes: uniao, intersecao, diferenca."),
    ("Estrutura: Pilha (Stack)", "LIFO (Last In, First Out). Push (inserir), Pop (remover)."),
    ("Estrutura: Fila (Queue)", "FIFO (First In, First Out). Enqueue (inserir), Dequeue (remover)."),
    ("BFS (Busca em Largura)", "Usa FILA. Explora vertices vizinhos antes de avancar nivel."),
    ("DFS (Busca em Profundidade)", "Usa PILHA. Explora o maximo possivel antes de voltar."),
    ("Arvore binaria", "Estrutura hierarquica com no maximo 2 filhos por no."),
    ("Tabela hash", "Insercao e busca O(1) medio. Colisoes: encadeamento, enderecamento aberto."),
    ("POO: Heranca", "Classe filha herda atributos e metodos da classe pai. Reuso de codigo."),
    ("POO: Polimorfismo", "Metodo com mesmo nome se comporta de forma diferente em classes diferentes."),
    ("POO: Encapsulamento", "Ocultar detalhes internos e expor apenas interface publica."),
    ("POO: Abstrato", "Classe que nao pode ser instanciada. Serve como modelo para subclasses."),
    ("POO: Interface", "Define contrato (metodos abstratos) que classes devem implementar."),
    ("REST: GET", "Recupera recurso. Idempotente, seguro (nao altera estado)."),
    ("REST: POST", "Cria novo recurso. Nao idempotente."),
    ("REST: PUT", "Atualiza recurso completamente. Idempotente."),
    ("REST: PATCH", "Atualiza recurso parcialmente."),
    ("REST: DELETE", "Remove recurso. Idempotente."),
    ("API RESTful", "API que segue principios REST: recursos, metodos HTTP, stateless, JSON/XML."),
    ("Machine Learning: supervisionado", "Dados rotulados (entrada-saida conhecida). Algoritmo aprende mapeamento."),
    ("Machine Learning: nao supervisionado", "Dados nao rotulados. Algoritmo encontra padroes (clusters)."),
    ("Machine Learning: reforco", "Agente aprende por tentativa e erro com recompensas/punicoes."),
    ("Random Forest", "Conjunto de arvores de decisao. Reduz overfitting. Algoritmo ensemble."),
    ("K-Means", "Algoritmo de clusterizacao nao supervisionado. Agrupa dados em K grupos."),
    ("Overfitting", "Modelo decora dados de treino mas nao generaliza para novos dados."),
    ("Underfitting", "Modelo muito simples, nao captura padroes dos dados."),
    ("Pandas (Python)", "Biblioteca para manipulacao de dados tabulares. DataFrame, Series."),
    ("NumPy (Python)", "Biblioteca para computacao numerica. Arrays multidimensionais."),
    ("HTML5: tags semanticas", "header, nav, main, section, article, aside, footer."),
    ("CSS Flexbox", "Layout unidimensional. display: flex. Itens se ajustam ao container."),
    ("JavaScript: map()", "Cria novo array aplicando funcao a cada elemento."),
    ("JavaScript: filter()", "Cria novo array com elementos que passam em um teste."),
    ("JavaScript: reduce()", "Reduz array a um unico valor aplicando funcao acumuladora."),
    ("React: State", "Dados mutaveis que afetam renderizacao. useState, setState."),
    ("React: Props", "Dados imutaveis passados de componente pai para filho."),
    ("React: Componente", "Bloco reutilizavel de UI. Pode ser funcional ou de classe."),
    ("LGPD: consentimento", "Base legal para tratamento de dados. Deve ser livre, informado e inequivoco."),
    ("Big Data: 5 Vs", "Volume, Velocidade, Variedade, Veracidade, Valor."),
    ("Power BI", "Ferramenta de visualizacao e analise de dados da Microsoft. Dashboards interativos."),
    ("Linux: ps", "Exibe processos em execucao. ps aux mostra todos os processos."),
    ("Linux: chmod", "Altera permissoes de arquivos: r (4), w (2), x (1). Ex: chmod 755."),
    ("Linux: grep", "Busca padroes em arquivos. grep 'erro' arquivo.log."),
    ("Linux: awk", "Processamento de texto por colunas. awk '{print $1}' arquivo."),
    ("Windows Server: AD", "Active Directory. Gerenciamento centralizado de usuarios e recursos."),
]

FLASHCARDS_PREV_CONT = [
    # Continuacao Previdencia (para completar 200)
    ("CMN: Conselho Monetario Nacional", "Define regras de investimento dos recursos das EFPC (resolucao CMN)."),
    ("CNPC: composicao", "Representantes do governo, patrocinadores, participantes e assistidos."),
    ("PREVIC: autarquia federal", "Vinculada ao Ministerio da Previdencia. Orgao fiscalizador das EFPC."),
    ("SUSEP: autarquia federal", "Vinculada ao Ministerio da Fazenda. Fiscaliza EAPC e seguros."),
    ("Planos PREVCOM: MULTI", "Para servidores de diferentes areas e orgaos do Estado de SP."),
    ("Planos PREVCOM: MS", "Para servidores da area de seguranca publica de SP."),
    ("Planos PREVCOM: MT", "Para servidores do magisterio estadual paulista."),
    ("SP-PREVidencia", "Plano BD para servidores que ingressaram antes da criacao do RPC estadual."),
    ("Contribuicao patrocinador", "Percentual definido no regulamento. Paridade com participante (LC 108)."),
    ("Contribuicao participante", "Percentual do salario de contribuicao. Definido no regulamento do plano."),
    ("Salario de contribuicao", "Base de calculo para contribuicoes previdenciarias."),
    ("Teto do RGPS (2026)", "Aproximadamente R$ 7.786,00. Valor maximo pago pelo INSS."),
    ("Limite do RPPS", "Teto do RGPS + previdencia complementar para quem optar."),
    ("Insolvencia do plano", "Situacao em que o plano nao tem recursos para pagar beneficios."),
    ("Liquidacao do plano", "Processo de encerramento definitivo do plano com pagamento de obrigacoes."),
    ("Regulamento do plano", "Documento que estabelece regras de elegibilidade, contribuicoes e beneficios."),
    ("Prospecto do plano", "Documento informativo sobre caracteristicas, riscos e custos do plano."),
    ("Relatorio anual", "Prestacao de contas anual do plano para participantes: demonstracoes financeiras, investimentos, atuarial."),
    ("Extrato de beneficios", "Documento periodico com saldo de conta, rentabilidade e projecoes."),
    ("Assembleia geral", "Orgao maximo de deliberacao das EFPC. Participantes elegem representantes."),
    ("Voto nas EFPC", "Participantes e assistidos votam para escolher representantes nos conselhos."),
]

# ============================================================
# EXPANSAO - MAIS FLASHCARDS PARA ATINGIR ~1000
# ============================================================

FLASHCARDS_LP_MAIS = [
    ("Sujeito: como identificar", "Pergunte 'Quem?' ou 'O que?' antes do verbo. Ex: 'O aluno estudou.' - Quem estudou? O aluno."),
    ("Objeto direto preposicionado", "OD com preposicao facultativa. Ex: 'Amar a Deus', 'Beijou a mae'."),
    ("Verbo transitivo direto (VTD)", "Verbo que pede complemento sem preposicao. Ex: 'Comprei um carro'."),
    ("Verbo transitivo indireto (VTI)", "Verbo que pede complemento com preposicao. Ex: 'Preciso de ajuda'."),
    ("Verbo intransitivo (VI)", "Verbo que nao pede complemento. Ex: 'O sol nasceu'."),
    ("Verbo de ligacao (VL)", "Liga sujeito ao predicativo. Ex: ser, estar, parecer, permanecer, continuar, ficar."),
    ("Adjunto adnominal x complemento nominal", "Adj adnominal: agente (de+algo). Compl nominal: paciente (de+algo). Ex: 'A descoberta do medico' (adj) vs 'Descoberta da cura' (compl)."),
    ("Oracao coordenada sindetica aditiva", "Conjuncao aditiva: e, nem, mas tambem. Ex: 'Estudou e passou'."),
    ("Oracao coordenada sindetica adversativa", "Conjuncao adversativa: mas, porem, todavia, contudo, entretanto. Ex: 'Quis ir, mas nao pude'."),
    ("Oracao coordenada sindetica alternativa", "Conjuncao alternativa: ou, ora...ora, quer...quer. Ex: 'Ou estuda ou trabalha'."),
    ("Oracao coordenada sindetica conclusiva", "Conjuncao conclusiva: logo, pois (posposto), portanto, por isso. Ex: 'Estudou, logo passou'."),
    ("Oracao coordenada sindetica explicativa", "Conjuncao explicativa: porque, pois (anteposto), que. Ex: 'Nao fui, pois estava doente'."),
    ("Funcao sintatica do pronome relativo", "O pronome relativo exerce funcao dentro da oracao adjetiva. Ex: 'O livro que li' (que = OD)."),
    ("Funcao sintatica de 'que'", "Pode ser: conj integrante, pron relativo, conj explicativa, particula expletiva, adv interrogativo."),
    ("Funcao sintatica de 'se'", "Pode ser: pron obliquo, particula apassivadora, indice de indeterminacao, conj condicional, parte integrante do verbo."),
    ("Particula apassivadora (SE)", "VTD + SE. Verbo concorda com sujeito. Ex: 'Vendem-se casas' (casas = sujeito)."),
    ("Indice de indeterminacao do sujeito (SE)", "VTI + SE. Verbo sempre singular. Ex: 'Precisa-se de funcionarios'."),
    ("Parte integrante do verbo", "Verbo pronominal: arrepender-se, queixar-se, candidatar-se. SE nao tem funcao."),
    ("Palavras denotativas", "Nao sao advrbios mas tem funcao similar: inclusive, apenas, aliás, isto e, por exemplo, ou seja."),
    ("Oracao reduzida", "Oracao sem conjuncao, com verbo no infinitivo, gerundio ou particpio. Ex: 'Ao chegar, avise-me'."),
    ("Oracao desenvolvida", "Oracao com conjuncao e verbo conjugado. Ex: 'Quando chegar, avise-me'."),
    ("Elipse", "Omissao de termo identificavel pelo contexto. Ex: 'Ela prefere cafe; ele, cha' (omite 'prefere')."),
    ("Zeugma", "Tipo de elipse: omissao de termo ja mencionado. Ex: 'Ele gosta de musica; ela, de pintura'."),
    ("Pleonasmo", "Repeticao intencional para enfase. Ex: 'Vi com meus proprios olhos.' Vicioso: 'subir para cima'."),
    ("Anfora", "Retomar termo anterior. Ex: 'Comprei um livro. Ele e otimo.'"),
    ("Catfora", "Antecipar termo posterior. Ex: 'Ela chegou. Maria estava cansada.'"),
    ("Hiponimo x hiperonimo", "Hiponimo: especifico (rosa). Hiperonimo: generico (flor)."),
    ("Campo semantico", "Conjunto de palavras relacionadas pelo sentido. Ex: 'medico, hospital, cirurgia' = saude."),
    ("Denotacao x Conotacao", "Denotacao: literal. Conotacao: figurado. Ex: 'A cobra picou' (literal) vs 'Ela e uma cobra' (figurado)."),
    ("Intertextualidade", "Dialogo entre textos. Parodia, citacao, alusao, epigrafe, referencia."),
    ("Texto argumentativo", "Defende tese com argumentos. Estrutura: tese, argumentos (dados, exemplos, autoridades), contra-argumentacao, conclusao."),
    ("Texto expositivo", "Apresenta informacoes de forma objetiva. Ex: artigos cientificos, verbetes, enciclopédias."),
    ("Genero textual: oficio", "Comunicacao oficial entre orgaos publicos. Padrao: protocolo, assunto, texto, fecho."),
    ("Genero textual: e-mail profissional", "Linguagem formal, clara e objetiva. Assunto claro, saudacao inicial, corpo, despedida, assinatura."),
    ("Genero textual: relatorio", "Documento tecnico que apresenta resultados de analise, pesquisa ou trabalho. Estrutura: introducao, metodologia, resultados, conclusao."),
    ("Genero textual: parecer", "Opiniao tecnica sobre determinado assunto. Estrutura: relatorio, opiniao, conclusao."),
    ("Genero textual: ata", "Registro fiel de reuniao. Discurso indireto, linguagem formal, sem rasuras."),
    ("Genero textual: requerimento", "Solicitacao formal a autoridade. Estrutura: vocativo, preambulo, pedido, fecho."),
    ("Carta comercial", "Comunicacao formal entre empresas. Estrutura: timbre, data, destinatario, assunto, texto, despedida, assinatura."),
    ("Artigo de opiniao", "Texto jornalistico com opiniao do autor sobre tema atual. Estrutura: titulo, introducao, argumentos, conclusao."),
    ("Editorial", "Artigo que expressa opiniao oficial do veiculo de comunicacao. Nao e assinado."),
    ("Cronica", "Narrativa curta sobre cotidiano. Tom leve, humoristico ou reflexivo."),
    ("Conto", "Narrativa curta com poucos personagens, tempo e espaco reduzidos. Clímax e desfecho."),
    ("Poesia lirica", "Expressa sentimentos e emocões do eu-lirico. Verso, estrofe, rima, ritmo."),
    ("Vicios de linguagem: barbarismo", "Erro na pronuncia (cacoépia) ou grafia (cacografia). Ex: 'adevogado' (advogado)."),
    ("Vicios: solecismo", "Erro de sintaxe: concordancia, regencia ou colocacao. Ex: 'Fazem dois anos' (haver impessoal)."),
    ("Vicios: ambiguidade", "Dupla interpretacao. Ex: 'Vi o homem com o telescopio' (quem usava o telescopio?)."),
    ("Vicios: pleonasmo vicioso", "Repeticao desnecessaria. Ex: 'subir para cima', 'entrar para dentro', 'monopólio exclusivo'."),
    ("Vicios: eco", "Rima involuntaria. Ex: 'A remuneracao nao teve aprovacao da administracao'."),
    ("Vicios: cacofonia", "Som desagradavel. Ex: 'Eu vi ela' (vi ela = viela), 'Foi por isso' (foipor = fopr)."),
    ("Vicios: estrangeirismo desnecessario", "Uso de palavra estrangeira quando ha equivalente em portugues. Ex: 'feedback' (retorno), 'delivery' (entrega)."),
    ("Funcao emotiva da linguagem", "Foco no emissor. Expressao de sentimentos. Ex: 'Estou muito feliz!'"),
    ("Funcao referencial da linguagem", "Foco na mensagem/contexto. Informacao objetiva. Ex: noticias, artigos cientificos."),
    ("Funcao conativa da linguagem", "Foco no receptor. Persuasao, ordem, pedido. Ex: propagandas, discursos politicos."),
    ("Funcao poetica da linguagem", "Foco na mensagem/estetica. Elaboracao da linguagem. Ex: poesia, literatura."),
    ("Funcao metalinguistica", "Foco no codigo. Linguagem falando de si mesma. Ex: dicionario, gramatica, poesia sobre poesia."),
    ("Funcao fatica da linguagem", "Foco no canal. Manter contato. Ex: 'Alo?', 'Entendeu?', 'Como assim?'"),
    ("Variacao linguistica: diatópica", "Variacao geografica/regional. Ex: 'aipim' (RJ) vs 'mandioca' (SP) vs 'macaxeira' (NE)."),
    ("Variacao diastrática", "Variacao social (classe, idade, profissao). Ex: girias, jargões, linguagem formal x coloquial."),
    ("Variacao diacronica", "Variacao historica. Ex: 'vosmecê' > 'voce' > 'ce'."),
    ("Variacao diafásica", "Variacao situacional/estilo. Ex: formal (entrevista) vs informal (conversa com amigos)."),
    ("Preconceito linguistico", "Desvalorizacao de variedades linguisticas diferentes do padrao culto. Deve ser combatido."),
    ("Norma culta x norma popular", "Norma culta: uso formal, regras gramaticais. Norma popular: uso cotidiano, regras proprias."),
    ("Linguagem formal x informal", "Formal: respeito as regras gramaticais, vocabulário erudito. Informal: coloquial, expressoes cotidianas."),
    ("Redacao oficial: principios", "Clareza, precisao, objetividade, concisao, coesao, coerencia, impessoalidade, formalidade, padronizacao."),
    ("Pronome de tratamento: enderecamento", "A Sua Excelencia (em envelope). Ex: 'A Sua Excelencia o Senhor Juiz...' (para autoridades)."),
    ("Pronome de tratamento: vocativo", "Excelentissimo Senhor Juiz, Prezado Senhor, Senhor Doutor."),
    ("Fecho em comunicacoes oficiais", "'Respeitosamente' (autoridades superiores) e 'Atenciosamente' (autoridades de mesma hierarquia)."),
    ("Padrao oficio: partes", "Tipo/n° do documento + data + assunto + destinatario + texto + fecho + assinatura."),
    ("Memorando", "Comunicacao entre unidades do mesmo orgao. Padrao: timbre, n°, data, assunto, texto, fecho, assinatura."),
    ("Exposicao de motivos", "Documento que explica e justifica decisões ou propostas a autoridade superior."),
    ("E-mail oficial", "Formal como oficio mas sem protocolizacao. Assunto claro, linguagem formal, arquivamento impresso."),
]

FLASHCARDS_ETICA_MAIS = [
    ("Lei de Acesso a Informacao (12.527/2011)", "Garante acesso a informacoes publicas. Prazos: 20 dias + 10 de prorogacao."),
    ("Classificacao de informacoes", "Ultrassecreta (25 anos), Secreta (15 anos), Reservada (5 anos). Prorogavel uma vez."),
    ("Comite de Etica publico", "Instancia para apurar desvios eticos de servidores. Pode aplicar censura etica."),
    ("Sancoes na Lei Anticorrupcao", "Multa de 0,1% a 30% do faturamento, publicacao extraordinaria, proibicao de contratar, dissolucao da empresa."),
    ("Contrato de integridade", "Compromisso formal de empresa contratada com adm publica de seguir praticas de integridade."),
    ("Politica de gestao de riscos", "Processo estruturado de identificacao, avaliacao, tratamento e monitoramento de riscos."),
    ("Apetite a risco", "Nivel de risco que a organizacao esta disposta a aceitar para alcancar seus objetivos."),
    ("Tone at the top", "Lideranca comprometida com a etica. Exemplo vindo da alta direcao."),
    ("Tone from the middle", "Lideranca media reforcando valores eticos no dia a dia operacional."),
    ("Tone at the bottom", "Compromisso de todos os colaboradores com a cultura de integridade."),
    ("Comite de Auditoria Estatutario", "Orgao de assessoramento ao Conselho de Administracao. Membros independentes."),
    ("Auditoria interna: principios", "Integridade, objetividade, confidencialidade, competencia. IIA."),
    ("ISO 37001 (Sistema Antissuborno)", "Norma internacional para implementar programa antissuborno em organizacoes."),
    ("ISO 37301 (Sistema de Compliance)", "Norma internacional para sistema de gestao de compliance."),
    ("ISO 31000 (Gestao de Riscos)", "Norma internacional para gestao de riscos. Principios, estrutura e processo."),
    ("Integridade em licitacoes", "Mecanismos: contrato de integridade, due diligence, clausulas anticorrupcao, monitoramento."),
    ("Lei 14.133/2021 (Nova Lei de Licitações)", "Nova lei de licitacoes e contratos administrativos. Moderniza processos, exige programa de integridade."),
    ("Compliance: clausulas contratuais", "Inserir clausulas anticorrupcao, direito de auditoria, rescisao por violacao de integridade."),
    ("Investigacao interna: 5 fases", "1. Planejamento. 2. Coleta de provas. 3. Entrevistas. 4. Relatorio. 5. Recomendacao."),
    ("Canal de denuncia: principios", "Confidencialidade, anonimato, imparcialidade, nao retalhacao, tratamento adequado."),
    ("Denuncia de boa-fe", "Denuncia feita com conviccao genuina, mesmo que nao confirmada. Protecao ao denunciante."),
    ("Denuncia de ma-fe", "Denuncia falsa ou caluniosa. O denunciante pode ser responsabilizado."),
    ("Retencao de documentos", "Politica de retencao e descarte de documentos conforme prazos legais e regulatorios."),
    ("Privacidade desde o conceito (Privacy by Design)", "Privacidade incorporada na arquitetura de sistemas e processos desde o inicio."),
    ("Privacidade por padrao (Privacy by Default)", "Configuracoes padrao que maximizam a privacidade do usuario."),
    ("Direitos dos titulares (LGPD)", "Confirmacao, acesso, correcao, anonimizacao, bloqueio, portabilidade, eliminacao, informacao."),
    ("Bases legais: interesse legitimo", "Tratamento necessario para atender interesses do controlador ou terceiros, respeitando direitos do titular."),
    ("Bases legais: cumprimento obrigacao legal", "Tratamento necessario para cumprir obrigacao legal ou regulatoria."),
    ("Bases legais: execucao de contrato", "Tratamento necessario para execucao de contrato com o titular."),
    ("Bases legais: exercicio regular de direitos", "Tratamento necessario para exercicio de direitos em processo judicial, adm ou arbitral."),
    ("Relatorio de Impacto a Protecao de Dados (RIPD)", "Documento que descreve processo de tratamento e riscos a privacidade dos titulares."),
    ("ANPD: autarquia", "Autoridade Nacional de Protecao de Dados. Orgao central de regulamentacao e fiscalizacao da LGPD."),
    ("Encarregado (DPO)", "Pessoa indicada pelo controlador para canal de comunicacao com titulares e ANPD."),
    ("LGPD: consentimento", "Manifestacao livre, informada e inequivoca pela qual titular concorda com tratamento."),
    ("LGPD: dados sensiveis", "Origem racial, conviccao religiosa, opiniao politica, saude, vida sexual, dados geneticos e biometricos."),
    ("LGPD: multas e sancoes", "Advertencia, multa simples (ate 2% faturamento, limitada a R$ 50 milhoes), multa diaria, publicizacao, bloqueio/eliminacao."),
    ("Lei do Cadastro Positivo (12.414/2011)", "Cria cadastro de historico de credito. Consentimento do consumidor."),
    ("Marco Civil da Internet (12.965/2014)", "Principios: neutralidade de rede, privacidade, guarda de registros, responsabilidade de provedores."),
    ("Neutralidade de rede", "Tratamento isonomico a todos os pacotes de dados, sem discriminacao por conteudo."),
    ("ESG: investimento sustentavel", "Integracao de criterios ESG na analise de investimentos. PRI (Principles for Responsible Investment)."),
    ("ESG: green bonds", "Titulos de divida para financiar projetos ambientais ou climaticos."),
    ("ESG: social bonds", "Titulos de divida para financiar projetos sociais."),
    ("ESG: sustainability-linked bonds", "Titulos vinculados a metas de sustentabilidade do emissor."),
    ("Politica de diversidade", "Diretrizes para promover inclusao de grupos sub-representados na organizcao."),
    ("Equidade de genero", "Igualdade de oportunidades e tratamento entre generos no ambiente de trabalho."),
    ("Equidade racial", "Igualdade de oportunidades e tratamento entre grupos raciais."),
    ("Inclusao de pessoas com deficiencia", "Remocao de barreiras e adaptacoes para garantir participacao plena de PcD."),
    ("Trabalho escravo contemporaneo", "Condicoes degradantes, jornada exaustiva, servidao por divida. Empresas devem monitorar cadeia."),
    ("Trabalho infantil", "Proibido abaixo de 16 anos (18 para atividades noturnas/perigosas). Aprendiz a partir de 14."),
    ("Assedio moral no trabalho", "Conduta abusiva reiterada que exponha trabalhador a situacoes humilhantes."),
    ("Assedio sexual no trabalho", "Constrangimento de natureza sexual, com superioridade hierarquica ou nao."),
    ("Politica de denuncia: anonimato", "Garantia de anonimato ao denunciante. Canal externo (ouvidoria independente)."),
    ("Ouvidoria", "Orgao de interlocucao com cidadao/colaborador. Recebe denuncias, sugestoes, reclamações, elogios."),
    ("Transparencia fiscal", "Divulgacao de tributos pagos, beneficios fiscais. Ex: Padrao GRI 207 (tax transparency)."),
    ("Paraísos fiscais", "Jurisdicoes com tributacao privilegiada ou sigilo bancario exacerbado. Risco de planejamento tributario agressivo."),
    ("Politica de conflito de interesses", "Regras para identificar, declarar e mitigar situacoes de conflito entre interesse privado e corporativo."),
    ("Politica de transacao com partes relacionadas", "Regras para transacoes com partes relacionadas (controladores, administradores)."),
    ("Insider trading", "Uso de informacao privilegiada para negociar valores mobiliarios. Crime."),
    ("Politica de investimentos pessoais", "Regras para investimentos pessoais de administradores e colaboradores. Controla insider trading."),
    ("Doacoes politicas", "Regras e limites para contribuicoes a campanhas politicas. Transparencia."),
    ("Lobby: regulamentacao", "Atividade de representacao de interesses. Exige transparencia e registro."),
    ("Brinde corporativo", "Item de valor simbolico (ex: caneta, calendario). Sem valor comercial."),
    ("Presente corporativo", "Item de valor significativo. Deve ser recusado ou doado conforme politica."),
    ("Hospitalidade corporativa", "Convites para eventos, refeicoes, viagens. Deve ter proporcionalidade e transparencia."),
    ("Registro de brindes e presentes", "Controle centralizado com valores, origem e destinacao. Transparencia."),
]

FLASHCARDS_RL_MAIS = [
    ("Negacao de proposicao quantificada", "Troca o quantificador e nega o predicado. Ex: ~(∀x P(x)) = ∃x ~P(x)."),
    ("Logica de primeira ordem", "Usa quantificadores sobre individuos. Ex: 'Todo homem e mortal.' = ∀x (Homem(x) -> Mortal(x))."),
    ("Logica proposicional", "Usa proposicoes simples e conectivos. Sem quantificadores."),
    ("Prefixo de tabela verdade: 2^n", "Para n variaveis, 2^n combinacoes. Exemplo: 5 variaveis = 32 linhas."),
    ("Propriedade comutativa: p^q = q^p", "A conjuncao e comutativa. A ordem das proposicoes nao altera o resultado."),
    ("Propriedade associativa: (p^q)^r = p^(q^r)", "A conjuncao e associativa. Agrupamento nao altera."),
    ("Propriedade distributiva: p^(qvr) = (p^q) v (p^r)", "Conjuncao distribui sobre disjuncao."),
    ("Propriedade distributiva: pv(q^r) = (pvq) ^ (pvr)", "Disjuncao distribui sobre conjuncao."),
    ("Lei da absorcao: p^(pvq) = p", "Se p e verdadeiro, a conjuncao de p com (p ou q) e p."),
    ("Lei da absorcao: pv(p^q) = p", "Se p e verdadeiro, a disjuncao de p com (p e q) e p."),
    ("Equivalencia: p->q = ~pvq", "Negacao do antecedente OU afirmacao do consequente. Equivalencia logica fundamental."),
    ("Equivalencia: p->q = ~q->~p", "Contrapositiva. Forma mais comum de validar argumentos condicionais."),
    ("Equivalencia: p<->q = (p->q)^(q->p)", "Bicondicional = duas condicionais (ida e volta)."),
    ("Equivalencia: p<->q = (p^q) v (~p^~q)", "Bicondicional: ambos verdadeiros ou ambos falsos."),
    ("Regra da exportacao: (p^q)->r = p->(q->r)", "Transforma conjuncao na premissa em condicional aninhada."),
    ("Regra da importacao: p->(q->r) = (p^q)->r", "Inverso da exportacao."),
    ("Reductio ad absurdum", "Para provar p, assume ~p e deriva contradicao. Logo p e V."),
    ("Prova condicional", "Para provar p->q, assume p e tenta derivar q."),
    ("Prova por casos", "Se p->r e q->r, e pvq, entao r e verdadeiro."),
    ("Raciocinio contraditorio", "Mostrar que a negacao da conclusao e inconsistente com as premissas."),
    ("Formula booleana: forma normal conjuntiva (FNC)", "Conjuncao de disjuncoes. Ex: (p v q) ^ (~p v r)."),
    ("Formula booleana: forma normal disjuntiva (FND)", "Disjuncao de conjuncoes. Ex: (p ^ q) v (~p ^ r)."),
    ("SAT (satisfabilidade)", "Problema de determinar se existe atribuicao de valores que torna formula V."),
    ("3-SAT", "Variante do SAT onde cada clausula tem exatamente 3 literais. NP-completo."),
    ("Algoritmo de resolucao", "Metodo de prova por refutacao na logica proposicional."),
    ("Clausula na resolucao", "Disjuncao de literais. Ex: p v q v ~r."),
    ("Resolvente", "Nova clausula gerada de duas clausulas-pai. Regra: (p v q) e (~p v r) geram (q v r)."),
    ("Logica de predicados: quantificador existencial", "Existe pelo menos um individuo que satisfaz a propriedade."),
    ("Logica de predicados: quantificador universal", "Todos os individuos satisfazem a propriedade."),
    ("Escopo de quantificador", "Parte da formula onde o quantificador atua."),
    ("Variavel livre x ligada", "Livre: nao esta no escopo de nenhum quant. Ligada: esta no escopo."),
    ("Substituicao em logica", "Trocar variavel livre por termo. Cuidado com captura de variavel."),
    ("Unificacao em logica", "Processo de encontrar substituicao que torna duas formulas identicas."),
    ("Logica: consequencia logica", "Formula e consequencia logica de premissas se toda interpretacao que satisfaz as premissas tambem satisfaz a formula."),
    ("Logica: consistencia", "Conjunto de formulas e consistente se existe interpretacao que satisfaz todas simultaneamente."),
    ("Logica: independencia de axiomas", "Axioma e independente se nao pode ser derivado dos demais axiomas."),
    ("Teoria dos conjuntos: conjunto vazio", "Conjunto sem elementos. Simbolo: ∅ ou {}. Subconjunto de qualquer conjunto."),
    ("Teoria: subconjunto proprio", "A ⊂ B significa que A e subconjunto de B mas A ≠ B."),
    ("Teoria: conjunto universo (U)", "Conjunto que contem todos os elementos considerados em determinado contexto."),
    ("Teoria: conjunto complementar", "Elementos de U que nao pertencem a A. Simbolo: A', A^c ou U - A."),
    ("Teoria: produto cartesiano (AxB)", "Conjunto de pares ordenados (a,b) com a∈A e b∈B."),
    ("Teoria: relacao binaria", "Subconjunto do produto cartesiano AxB. Relaciona elementos de A com B."),
    ("Teoria: funcao", "Relacao binaria onde cada elemento de A se relaciona com EXATAMENTE um de B."),
    ("Teoria: injetora", "Funcao onde elementos diferentes de A tem imagens diferentes em B."),
    ("Teoria: sobrejetora", "Funcao onde todo elemento de B e imagem de pelo menos um de A."),
    ("Teoria: bijetora", "Funcao simultaneamente injetora e sobrejetora. Correspondencia biunivoca."),
    ("Progressao geometrica infinita", "Soma de PG infinita com |q| < 1: S∞ = a1 / (1 - q)."),
    ("Propriedades de potencias", "a^m * a^n = a^(m+n). (a^m)^n = a^(m*n). a^0 = 1 (a≠0)."),
    ("Propriedades de logaritmos", "log_a(b*c) = log_a(b) + log_a(c). log_a(b/c) = log_a(b) - log_a(c). log_a(b^n) = n * log_a(b)."),
    ("Mudanca de base de log", "log_a(b) = log_c(b) / log_c(a)."),
    ("Analise combinatoria: permutacao circular", "Pc(n) = (n-1)!. Dispor n elementos em circulo."),
    ("Analise combinatoria: permutacao com repeticoes", "P(n; r1, r2, ..., rk) = n! / (r1! * r2! * ... * rk!)."),
    ("Analise combinatoria: combinacao com repeticoes", "CR(n,p) = C(n+p-1, p). Escolher p elementos com repeticoes."),
    ("Probabilidade: esperanca (valor esperado)", "E[X] = Σ x_i * P(X = x_i). Media ponderada das probabilidades."),
    ("Probabilidade: variancia", "Var(X) = E[(X - μ)^2] = E[X^2] - E[X]^2."),
    ("Probabilidade: desvio padrao", "σ = √Var(X). Medida de dispersao na mesma unidade dos dados."),
    ("Probabilidade: distribuicao binomial", "P(X = k) = C(n,k) * p^k * (1-p)^(n-k). n tentativas independentes."),
    ("Probabilidade: distribuicao normal", "Distribuicao continua em formato de sino. Media μ, desvio σ. Regra 68-95-99,7."),
    ("Probabilidade: teorema de Bayes generalizado", "P(Ai|B) = P(B|Ai)*P(Ai) / ΣP(B|Aj)*P(Aj). Atualiza probabilidade com evidencia."),
    ("Estatistica: media ponderada", "Media com pesos diferentes para cada valor. Σ (xi * pi) / Σ pi."),
    ("Estatistica: quartis", "Dividem dados ordenados em 4 partes: Q1 (25%), Q2/mediana (50%), Q3 (75%)."),
    ("Estatistica: desvio interquartil (IQR)", "IQR = Q3 - Q1. Mede dispersao dos 50% centrais."),
    ("Estatistica: boxplot", "Grafico que mostra: minimo, Q1, mediana, Q3, maximo e outliers."),
    ("Estatistica: correlacao de Pearson (r)", "Mede relacao linear entre variaveis. -1 ≤ r ≤ +1. Nao implica causalidade."),
    ("Estatistica: regressao linear simples", "Y = β0 + β1*X + ε. β1 = cov(X,Y) / Var(X)."),
    ("ESTATISTICA: R²", "Coeficiente de determinacao. Proporcao da variancia de Y explicada por X."),
]

FLASHCARDS_PREV_MAIS2 = [
    ("Meta de rentabilidade", "Objetivo de retorno dos investimentos do plano. Deve superar meta atuarial."),
    ("Benchmark de investimentos", "Indice de referencia para comparar desempenho. Ex: CDI, IBOV, IMA."),
    ("Duration de carteira", "Prazo medio ponderado dos fluxos de caixa dos ativos. Mede sensibilidade a juros."),
    ("Duration x prazo do passivo", "Devem ser compatíveis para evitar descasamento (ALM)."),
    ("Renda fixa: titulos publicos", "Tesouro Direto: Selic, Prefixado, IPCA+. Baixo risco de credito."),
    ("Renda fixa: titulos privados", "CDB, debentures, CRIs, CRAs, LCIs, LCAs. Risco de credito do emissor."),
    ("Renda variavel: acoes", "Participacao societaria em empresa. Rendimento: dividendos + valorizacao."),
    ("Renda variavel: fundos imobiliarios (FII)", "Investimento em imoveis e ativos imobiliarios. Rendimento: aluguel + valorizacao."),
    ("Investimentos estruturados", "Fundos multimercados, hedge funds, private equity, venture capital."),
    ("Investimentos no exterior", "Alocacao em ativos internacionais. Diversificacao geografica e cambial."),
    ("Risco cambial", "Variacao da taxa de cambio entre moedas. Impacta investimentos no exterior."),
    ("Risco de inflacao", "Perda de poder de compra dos recursos. Protecao: titulos indexados ao IPCA."),
    ("Risco de longevidade", "Participante vive mais que o esperado. Plano precisa pagar beneficio por mais tempo."),
    ("Risco de mortalidade", "Participante morre antes do esperado. Impacta calculo de reservas."),
    ("Risco de desemprego/rotatividade", "Participante sai do plano antes da aposentadoria. Impacta massa de participantes."),
    ("Reserva de contingencia", "Reserva adicional para cobrir variacoes adversas nas hipoteses atuariais."),
    ("Reserva de oscilacao de riscos", "Reserva para cobrir oscilacoes nos riscos de morte, invalidez e sobrevivencia."),
    ("Plano de custeio", "Definicao das fontes de financiamento: contribuicoes normais, extraordinarias, aportes."),
    ("Custeio administrativo", "Recursos para cobrir despesas administrativas da EFPC. Taxa de administracao."),
    ("Custeio dos beneficios", "Recursos para pagamento dos beneficios previstos no regulamento."),
    ("Regime financeiro: reparticao simples", "Contribuicoes do periodo pagam beneficios do periodo. Sem acumulo."),
    ("Regime financeiro: capitalizacao", "Acumulo de recursos para pagar beneficios futuros. Adocao obrigatoria no RPC."),
    ("Metodo atuarial: credito unitario projetado", "Metodo mais comum para planos BD. Projeta beneficios e distribui custo ao longo do tempo."),
    ("Metodo atuarial: idade de entrada", "Custo nivelado como percentual do salario desde a entrada ate a aposentadoria."),
    ("Hipotese: taxa de juros", "Taxa de desconto para calcular valor presente dos compromissos futuros."),
    ("Hipotese: tábua de mortalidade", "Tabela que estima probabilidade de morte em cada idade. Ex: AT-2000, BR-EMS."),
    ("Hipotese: entrada em aposentadoria", "Idade presumida de aposentadoria dos participantes."),
    ("Hipotese: crescimento salarial", "Projecao de aumento real dos salarios ao longo do tempo."),
    ("Hipotese: rotatividade", "Taxa estimada de desligamentos de participantes antes da aposentadoria."),
    ("Hipotese: composicao familiar", "Estimativa de dependentes para calculo de pensao por morte."),
    ("Auditoria atuarial", "Revisao independente das hipoteses, metodos e calculos atuariais do plano."),
    ("Due diligence atuarial", "Analise detalhada de passivo atuarial em processos de migracao ou reestruturacao."),
    ("Solvencia do plano", "Capacidade do plano de cumprir suas obrigacoes de longo prazo."),
    ("Teste de solvencia", "Avaliacao periodica se ativos sao suficientes para cobrir passivos."),
    ("Equacionamento: prazo", "Deficit deve ser equacionado em ate 15 anos (prorogavel excepcionalmente)."),
    ("Equacionamento: contribuicao extraordinaria", "Percentual adicional sobre salario de contribuicao para cobrir deficit."),
    ("Equacionamento: reducao de beneficio", "Reducao do valor dos beneficios futuros para equacionar deficit (se previsto)."),
    ("Portabilidade: para onde?", "Para outro plano de previdencia complementar (EFPC ou EAPC). Nao para INSS."),
    ("Portabilidade: tributacao", "Sem incidencia de IR no momento da transferencia. Diferimento fiscal."),
    ("Resgate: tributacao", "IR sobre o valor resgatado. Tabela regressiva ou progressiva."),
    ("Resgate: parcial ou total", "Participante pode resgatar parte ou todo o saldo de conta."),
    ("Resgate: quando ocorre", "Cancelamento do plano, desligamento do patrocinador, apos prazo de carencia."),
    ("Beneficio: renda vitalicia", "Pagamento mensal vitalicio. Protege contra risco de longevidade."),
    ("Beneficio: renda temporaria", "Pagamento por prazo certo. Ex: 10, 15, 20 anos."),
    ("Beneficio: renda vitalicia com prazo minimo", "Garantia de pagamento por prazo minimo mesmo se falecer antes."),
    ("Forma de pagamento: 50% conjuge", "Renda vitalicia com continuacao de 50% do valor ao conjuge apos morte."),
    ("Forma de pagamento: 100% conjuge", "Renda vitalicia com continuacao integral ao conjuge."),
    ("Beneficio de risco: auxilio-doenca", "Beneficio temporario por incapacidade temporaria. Prazo maximo definido."),
    ("Beneficio de risco: pensao por morte", "Beneficio pago aos dependentes em caso de morte do participante."),
    ("Beneficio de risco: invalidez", "Beneficio por incapacidade permanente total. Aposentadoria por invalidez."),
    ("Reversao de beneficios", "Beneficio do assistido pode reverter para dependentes apos sua morte."),
    ("Decaimento de beneficios", "Reducao do valor do beneficio ao longo do tempo (geralmente nao aplicavel em planos BD)."),
    ("13 salario previdenciario", "Pagamento adicional de uma parcela do beneficio no ano."),
]

FLASHCARDS_TI_MAIS = [
    ("Metodologia agil: XP (eXtreme Programming)", "Foco em qualidade de software. Pair programming, TDD, integracao continua, refactoring."),
    ("Metodologia agil: Lean", "Eliminar desperdicios, entregar rapido, ampliar conhecimento, adiar decisoes, respeitar pessoas."),
    ("Metodologia agil: FDD (Feature Driven Development)", "Baseada em funcionalidades. Modelagem, lista de features, planejamento, design, construcao."),
    ("Metodologia agil: Crystal", "Familia de metodos ageis. Foco em comunicacao e ajuste conforme tamanho da equipe."),
    ("Metodologia agil: TDD (Test-Driven Development)", "Escrever teste antes do codigo. Ciclo: vermelho-verde-refatora."),
    ("Metodologia agil: BDD (Behavior-Driven Development)", "Testes baseados em comportamento. Formato: Dado-Quando-Entao (Given-When-Then)."),
    ("UML: relacionamento de associacao", "Ligacao estrutural entre classes. Ex: Cliente -> Pedido."),
    ("UML: relacionamento de agregacao", "Todo-parte debil. Parte existe sem o todo. Ex: Time -> Jogador (losango vazio)."),
    ("UML: relacionamento de composicao", "Todo-parte forte. Parte nao existe sem o todo. Ex: Casa -> Comodo (losango preenchido)."),
    ("UML: relacionamento de dependencia", "Classe usa servico de outra. Setinha tracejada. Ex: Controller -> Service."),
    ("UML: relacionamento de heranca", "Classe filha herda de classe pai. Seta com triangulo vazio."),
    ("UML: relacionamento de realizacao", "Classe implementa interface. Seta tracejada com triangulo vazio."),
    ("UML: multiplicidade", "Quantos objetos se relacionam. 1, 0..1, 0..*, 1..*, *."),
    ("UML: Diagrama de Pacotes", "Agrupa classes em pacotes/modulos. Mostra dependencias entre pacotes."),
    ("UML: Diagrama de Componentes", "Componentes de software e suas interfaces. Fisico (JAR, DLL, EXE)."),
    ("UML: Diagrama de Implantacao", "Nos fisicos (servidores) e artefatos implantados."),
    ("UML: Diagrama de Objetos", "Instancias de classes em determinado momento. 'Fotografia' da memoria."),
    ("UML: Diagrama de Comunicação", "Interacao entre objetos com foco na ligacao estrutural (nao temporal)."),
    ("UML: Diagrama de Tempo (Timing)", "Estado de objetos ao longo do tempo. Linhas de vida."),
    ("UML: Diagrama de Visao Geral da Interacao", "Combina diagramas de sequencia e controle de fluxo."),
    ("Design Patterns: Singleton", "Garante unica instancia de classe. Acesso global."),
    ("Design Patterns: Factory Method", "Define interface para criar objeto, mas subclasses decidem qual classe instanciar."),
    ("Design Patterns: Abstract Factory", "Cria familias de objetos relacionados sem especificar classes concretas."),
    ("Design Patterns: Builder", "Separa construcao de objeto complexo de sua representacao."),
    ("Design Patterns: Prototype", "Cria novos objetos clonando um prototipo."),
    ("Design Patterns: Adapter", "Converte interface de uma classe para outra interface esperada pelo cliente."),
    ("Design Patterns: Bridge", "Separa abstracao de implementacao para que possam variar independentemente."),
    ("Design Patterns: Composite", "Compoe objetos em estrutura de arvore para representar hierarquias todo-parte."),
    ("Design Patterns: Decorator", "Adiciona responsabilidades a objeto dinamicamente."),
    ("Design Patterns: Facade", "Interface unificada para conjunto de interfaces de um subsistema."),
    ("Design Patterns: Flyweight", "Compartilha objetos granulares para suportar grande quantidade."),
    ("Design Patterns: Proxy", "Controla acesso a outro objeto (virtual, remoto, protecao)."),
    ("Design Patterns: Chain of Responsibility", "Passa requisicao ao longo de cadeia de handlers ate alguem tratar."),
    ("Design Patterns: Command", "Encapsula requisicao como objeto. Permite fila, log, undo."),
    ("Design Patterns: Iterator", "Acessa elementos de colecao sequencialmente sem expor representacao interna."),
    ("Design Patterns: Mediator", "Define objeto que centraliza comunicacao entre objetos."),
    ("Design Patterns: Memento", "Captura e externaliza estado interno de objeto sem violar encapsulamento."),
    ("Design Patterns: Observer", "Notifica multiplos observadores sobre mudancas em objeto."),
    ("Design Patterns: State", "Altera comportamento de objeto conforme seu estado interno."),
    ("Design Patterns: Strategy", "Define familia de algoritmos intercambiaveis."),
    ("Design Patterns: Template Method", "Define esqueleto de algoritmo, subclasses implementam etapas."),
    ("Design Patterns: Visitor", "Separa algoritmo da estrutura de objetos sobre a qual opera."),
    ("Arquitetura: Monolito", "Aplicacao unica, todas as funcionalidades acopladas. Simples inicio, dificil escalar."),
    ("Arquitetura: Microsservicos", "Servicos independentes, cada um com responsabilidade unica. Comunicacao via API."),
    ("Arquitetura: Serverless", "Funcoes executadas sob demanda (AWS Lambda, Azure Functions). Sem gerenciar servidor."),
    ("Arquitetura: Event-Driven", "Servicos comunicam via eventos. Produtores publicam, consumidores reagem."),
    ("Arquitetura: CQRS", "Command Query Responsibility Segregation. Separa operacoes de leitura e escrita."),
    ("Arquitetura: Hexagonal (Ports & Adapters)", "Isola o nucleo da aplicacao de tecnologias externas (banco, API, UI)."),
    ("Arquitetura: Clean Architecture", "Camadas concêntricas: entidades, casos de uso, adaptadores, frameworks."),
    ("Message Queue: RabbitMQ", "Sistema de fila de mensagens. Protocolo AMQP. Troca de mensagens assincrona."),
    ("Message Queue: Apache Kafka", "Plataforma de streaming de eventos. Log commit distribuido."),
    ("API Gateway", "Ponto unico de entrada para microsservicos. Roteamento, autenticacao, rate limiting."),
    ("Service Mesh (Istio, Linkerd)", "Camada de infra para comunicacao entre microsservicos. Proxy sidecar."),
    ("Container orchestration: Kubernetes", "Orquestracao de containers. Auto scaling, service discovery, rolling updates."),
    ("Container orchestration: Docker Swarm", "Orquestracao nativa do Docker. Mais simples que K8s."),
    ("IaC: Terraform", "Infrastructure as Code. Declarativo, multi-cloud (AWS, Azure, GCP). HCL."),
    ("IaC: Ansible", "Automacao de configuracao. Agentless, YAML, push-based."),
    ("IaC: CloudFormation", "IaC da AWS. Template JSON/YAML para criar recursos AWS."),
    ("Monitoramento: Prometheus", "Sistema de monitoramento e alerta. Coleta metricas em time-series."),
    ("Monitoramento: Grafana", "Visualizacao de metricas. Dashboards interativos. Fontes: Prometheus, InfluxDB."),
    ("Monitoramento: Datadog", "Plataforma SaaS de monitoramento de infra e aplicacoes."),
    ("Observabilidade: logs", "Registros de eventos. ELK Stack (Elasticsearch, Logstash, Kibana)."),
    ("Observabilidade: metricas", "Valores numericos ao longo do tempo. CPU, memoria, latencia, throughput."),
    ("Observabilidade: tracing", "Rastreamento de requisicao em microsservicos. Jaeger, Zipkin."),
    ("Log: ELK Stack", "Elasticsearch (busca), Logstash (processamento), Kibana (visualizacao)."),
    ("Log: Graylog", "Plataforma de gerenciamento de logs. Coleta centralizada, alertas."),
    ("Log: Splunk", "Plataforma de analise de dados de maquina. Busca, monitoramento, alertas."),
    ("DevOps: cultura", "Integracao entre dev e ops. Automacao, colaboracao, medicao, compartilhamento."),
    ("DevOps: SRE (Site Reliability Engineering)", "Engenharia de confiabilidade. Google. SLIs, SLOs, SLAs, error budgets."),
    ("SRE: SLI", "Service Level Indicator. Metrica real do servico. Latencia, disponibilidade, throughput."),
    ("SRE: SLO", "Service Level Objective. Meta para o SLI. Ex: 99.9% disponibilidade."),
    ("SRE: SLA", "Service Level Agreement. Acordo formal com cliente sobre nivel de servico."),
    ("SRE: Error Budget", "Orcamento de erros: 100% - SLO. Quanto pode falhar sem violar acordo."),
    ("Seguranca: Zero Trust", "Nunca confie, sempre verifique. Acesso baseado em identidade e contexto."),
    ("Seguranca: Defense in Depth", "Multiplas camadas de defesa: firewall, IDS, criptografia, controle de acesso."),
    ("Seguranca: SAST", "Static Application Security Testing. Analise estatica de codigo."),
    ("Seguranca: DAST", "Dynamic Application Security Testing. Teste de seguranca em aplicacao rodando."),
    ("Seguranca: IAST", "Interactive Application Security Testing. Combina SAST e DAST em tempo de execucao."),
    ("Seguranca: RASP", "Runtime Application Self-Protection. Protege aplicacao em tempo de execucao."),
    ("Seguranca: WAF", "Web Application Firewall. Filtra trafego HTTP malicioso."),
    ("Seguranca: SIEM", "Security Information and Event Management. Correlacao de logs de seguranca."),
    ("Seguranca: SOAR", "Security Orchestration, Automation and Response. Automacao de resposta a incidentes."),
    ("Seguranca: Pentest", "Teste de penetracao. Simula ataque para identificar vulnerabilidades."),
    ("Seguranca: Red Team", "Equipe que simula atacantes reais. Testa defesas da organizacao."),
    ("Seguranca: Blue Team", "Equipe defensiva. Monitora, detecta e responde a incidentes."),
    ("Seguranca: Purple Team", "Integracao Red+Blue. Compartilha conhecimento para melhorar defesas."),
    ("Criptografia: TLS/SSL", "Protocolo de seguranca para comunicacao na internet. Handshake, cifra, autenticacao."),
    ("Criptografia: chave publica x privada", "Publica: compartilhada. Privada: secreta. RSA, ECC, Diffie-Hellman."),
    ("Criptografia: certificado digital ICP-Brasil", "Padrao brasileiro de certificacao digital. A3 (token) e A1 (arquivo)."),
    ("Hash: SHA-256", "Funcao hash de 256 bits. Usada em blockchain, TLS, assinatura digital."),
    ("Hash: bcrypt", "Hash de senhas com salt. Mais lento (protecao contra brute force)."),
    ("Autenticacao: OAuth 2.0", "Framework de autorizacao. Tokens de acesso. Flows: authorization code, implicit."),
    ("Autenticacao: OpenID Connect", "Camada de identidade sobre OAuth 2.0. ID Token (JWT)."),
    ("Autenticacao: SAML", "Security Assertion Markup Language. SSO corporativo. XML-based."),
    ("Autenticacao: JWT", "JSON Web Token. Token compacto e autocontido. Header, payload, signature."),
    ("Autenticacao: MFA", "Multi-Factor Authentication. Dois ou mais fatores: senha + biometria + token."),
    ("Autenticacao: SSO", "Single Sign-On. Autentica uma vez, acessa varios sistemas."),
    ("Banco de dados: relacional x NoSQL", "Relacional: esquema fixo, ACID. NoSQL: flexivel, BASE, horizontal."),
    ("Banco de dados: PostgreSQL", "Relacional open source. Suporta JSON, full-text search, extensoes."),
    ("Banco de dados: MySQL", "Relacional open source. Popular em aplicacoes web. LAMP stack."),
    ("Banco de dados: SQL Server", "Relacional Microsoft. T-SQL, SSIS, SSRS, SSAS."),
    ("Banco de dados: Oracle", "Relacional Oracle. PL/SQL, RAC, particionamento."),
    ("Banco de dados: Cassandra", "NoSQL orientado a colunas. Alta disponibilidade, sem master."),
    ("Banco de dados: DynamoDB", "NoSQL AWS. Chave-valor e documentos. Totalmente gerenciado."),
    ("Banco de dados: Elasticsearch", "Busca e analise. Baseado em Lucene. JSON, REST API."),
    ("Banco de dados: Neo4j", "NoSQL orientado a grafos. Nos e relacionamentos. Cypher query."),
    ("Banco de dados: sharding", "Particionamento horizontal de dados entre servidores."),
    ("Banco de dados: replicacao", "Copiar dados para outro servidor. Master-slave, multi-master."),
    ("Banco de dados: backup", "Estrategias: full, diferencial, incremental. RPO e RTO."),
    ("Banco de dados: RPO", "Recovery Point Objective. Perda maxima aceitavel de dados."),
    ("Banco de dados: RTO", "Recovery Time Objective. Tempo maximo para recuperar servico."),
]

_PROG = gerar_flashcards_programaticamente()

ALL_FLASHCARD_TEMPLATES = {
    "Lingua Portuguesa": FLASHCARDS_LP + FLASHCARDS_LP_MAIS + _PROG["Lingua Portuguesa"],
    "Etica e Integridade": FLASHCARDS_ETICA + FLASHCARDS_ETICA_MAIS + _PROG["Etica e Integridade"],
    "Raciocinio Logico e Analitico": FLASHCARDS_RL + FLASHCARDS_RL_MAIS + _PROG["Raciocinio Logico e Analitico"],
    "Previdencia Complementar no Brasil": FLASHCARDS_PREV + FLASHCARDS_PREV_CONT + FLASHCARDS_PREV_MAIS2 + _PROG["Previdencia Complementar no Brasil"],
    "Conhecimentos Especificos em Tecnologia": FLASHCARDS_TI + FLASHCARDS_TI_MAIS + _PROG["Conhecimentos Especificos em Tecnologia"],
}


def generate_all_flashcards():
    """Gera todos os flashcards a partir dos templates."""
    cards = []
    for disciplina, templates in ALL_FLASHCARD_TEMPLATES.items():
        for frente, verso in templates:
            cards.append(Flashcard(frente=frente, verso=verso, disciplina=disciplina))
    return cards


def seed_flashcards(app, force=False):
    """Insere flashcards se nao existirem ou se force=True."""
    with app.app_context():
        from models import db, Flashcard
        existing = Flashcard.query.count()
        if existing > 0 and not force:
            print(f"Flashcards ja existem ({existing}). Pulando geracao.")
            return existing
        
        if force:
            Flashcard.query.delete()
            db.session.commit()
            print("Flashcards existentes removidos. Regenerando...")

        cards = generate_all_flashcards()
        for c in cards:
            db.session.add(c)
        db.session.commit()
        total = len(cards)
        print(f"GERADOS {total} FLASHCARDS:")
        for disc in sorted(set(c.disciplina for c in cards)):
            count = sum(1 for c in cards if c.disciplina == disc)
            print(f"  - {disc}: {count}")
        return total


if __name__ == "__main__":
    from app import app
    total = seed_flashcards(app, force=True)
    print(f"\nTotal: {total} flashcards gerados com sucesso!")
